### PR TITLE
Changed gym icons into shields/badges

### PR DESCRIPTION
**Pull request by MikeDuister**
## Description
Changed gym icons

**this PR is a redo of #1868 because of mistake due to lack of experience**

## Motivation and Context
The old variety of gym icons looked 'out of style'

## How Has This Been Tested?
map fully tested with icon, see #1671 

## Screenshots (if appropriate):
screenshot_106

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by QuadTog** [comment]
Much better! Although I'd love to see a Harmony badge as well. The poo one was okay but... well ya know :P

**Comment by MikeDuister** [comment]
@QuadTog Good suggestion, new commit with icon has been added

**Comment by MonkeyLeeT** [comment]
+1. Any other collab please just merge!

**Comment by Spodess** [comment]
Thanks!

**Comment by DerScreever** [comment]
@MonkeyLeeT 
done

**Comment by 123456abcdef** [comment]
What about the uncontested gyms? Could you also make one for those?

**Pull request merged**
