### PR TITLE
Added tracker page

### PR DESCRIPTION
**Pull request by adamhwang**
## Description

Added /tracker page to play PoGo as it was meant to be played
- Follows user and refreshes every 5 seconds
- Pokemon on your notify list will be shown as shadowed

## Motivation and Context

Made it because Niantic won't

## How Has This Been Tested?

Tested on Chrome desktop and mobile and FF mobile

## Screenshots (if appropriate):
image

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by marauder37** [comment]
cute

**Comment by adamhwang** [comment]
Pokemon on your notify list will be shown as a shadow now:
image

**Comment by Zerotask** [comment]
var excludedPokemon = JSON.parse(localStorage["remember_select_notify"] || "[]");  this should be remember_select_exclude I guess.

Maybe it would be good to set a reload page every x seconds

**Comment by adamhwang** [comment]
"remember_select_exclude" are the mons you don't want.  I used "remember_select_notify" for the ones you're looking for (i.e. shadowed).  I think the variable is probably poorly named.

The page reloads every 5 seconds.  It does pretty much the same thing as the "Follow Location" flag in the map where the scanner follows you around as you move.

**Comment by AHAAAAAAA** [comment]
Hah! I love this.

**Comment by LcTrKiD** [comment]
How can i try this? Do I need to grunt build and run the script again after the changes?

**Comment by adamhwang** [comment]
Yes, grab the feature branch, grunt build, then navigate to /tracker to test.  Let me know if you run into any issues

**Comment by LcTrKiD** [comment]
@adamhwang I did that but I only see "NEARBY" and a blank page.

**Comment by adamhwang** [comment]
any javascript errors (developer console/F12)?  what browser/os?  also, keep in mind Chrome only lets you send location over https

**Comment by LcTrKiD** [comment]
@adamhwang I could track this error on safari for iOS
screen shot 2016-08-02 at 23 29 25

**Comment by LcTrKiD** [comment]
I found the error. I was using -fl modifier

**Comment by adamhwang** [comment]
Glad to hear it!  @LcTrKiD might want to remove screen with your ip

**Comment by adamhwang** [comment]
Matched colors and font's slightly better:
image


Does anybody have (or can re-create) the step icons?  I don't have access to unity

**Comment by darkdefiled** [comment]
So where is this "feature branch" im kinda new to GitHub, and i'd love to have this new feature on the pokemap!

**Comment by adamhwang** [comment]
Updated the step icons to match :smile:

**Comment by Pranav44** [comment]
Does this work on ios?

**Comment by neutron666** [comment]
How do i check this out ?

**Comment by adamhwang** [comment]
scanner is down so probably not of use right now, but whenever it comes back, the feature branch is at: https://github.com/adamhwang/PokemonGo-Map/tree/dev-tracker

**Pull request closed without merging**
