### PR TITLE
Add support for custom database port

### PR DESCRIPTION
**Pull request by nevrending**
## Description

Added support (field to fill out the port) for databases that run on non-default port

## Motivation and Context

To make it easier to config it

## How Has This Been Tested?

Tested locally and on staging server

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Have you tested negative cases when port is not set, set as random stuff, out of range, etc.?

**Comment by nevrending** [comment]
@MonkeyLeeT would d019333 suffice?

**Comment by AHAAAAAAA** [comment]
rebase this and I'll merge

**Comment by invisiblek** [comment]
Didn't see this here, already merged here: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3210

**Pull request closed without merging**
