### PR TITLE
Beehive generator for swarms of workers covering a single area

### PR DESCRIPTION
**Pull request by hgentry**
A script for generating worker locations in a hexagonal grid given a central point and a script for running that swarm

## Description

location_generator.py creates a list of locations in a hexagonal grid pattern around a central point.

Arguments: -st: steps -lp: leaps (like steps, but for number of workers) -lat: start latitude -lon start longitude

beehive_builder.sh is a bash script that calls location_generator.py with given arguments and creates a script that will run workers at all the generated locations and a server-only process.

Usage: ./beehive_builder.sh "steps" "leaps" "center latitude" "center longitude"

## Motivation and Context
People keep doing this manually and it takes them hours.

## How Has This Been Tested?
location_generator.py has been thoroughly tested in a point-plotting website.

beehive_generator.sh and the generated beehive.sh have been tested manually at several locations and latitudes, with no apparent issues.

Minor gaps exist, which can be solved by finding out EXACTLY how wide a scan is. I'm working from the community's best guesses.

## Screenshots (if appropriate):

A demonstration of what all the generated coordinates look like on a map when seeded with downtown Indianapolis (4 steps, 8 leaps)

beehive -st 4 lp 8

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cNyhuus** [comment]
This would simply be awesome to have!

**Comment by louispires** [comment]
How do I stop all the workers? (bash.exe and python)

**Comment by hgentry** [comment]
pkill -9 python

This kills all of the processes, server included. Not sure of a way to kill
just the workers.

**Comment by Cliffield** [comment]
I am sorry, but how do i start it?
sh beehive_builder.sh  -some -arguments gives me:

```
location_generator.py: error: argument -st/--steps: expected one argument
beehive_builder.sh: 3: beehive_builder.sh: [[: not found
Beehive generated. Run ./beehive.sh to unleash the swarm.
```

**Comment by hgentry** [comment]
./beehive_builder.sh "steps" "radius of hive" "center latitude" "center
longitude"

Put the appropriate values in each of the quotes.

./beehive.sh will start the workers and server after builder successfully
runs. Take a look at this file if you're curious what workers you're
actually starting :)

**Comment by BullHorn7** [comment]
This is a great feature, really hope it makes it into the program.

**Comment by hgentry** [comment]
I don't think code-quality/landscape knows how to deal with bash files

**Comment by Olathurl** [comment]
awesome work Hgentry, far beyond what i have in spreadsheet :D

**Comment by hgentry** [comment]
Thanks! What we talked about the other day got stuck in my head and I put my insomnia to good use.

**Comment by marauder37** [comment]
I recognise reverse Haversine, so I'm willing to test this

**Comment by Olathurl** [comment]
haha, i actually slept a lil last night.. or ida been up all night trying to figure it out xD

**Comment by reyqn** [comment]
"Minor gaps exist, which can be solved by finding out EXACTLY how wide a scan is. I'm working from the community's best guesses."
Try generating hexagones like on the right (not the left like you're doing now). This should help.
geogebra-export3 1
Also  1426/19? 75 should be good

**Comment by Olathurl** [comment]
the math i provided him, is for -st 10.. using anything other than -st 10 will yield gaps/overlaps.. because.. well.. i dont know the math of the other -st yet :c

**Comment by hgentry** [comment]
Yeah, I'd love to measure the km at the equator, too. That's the only spot where it's reliable data. The gaps are really minor right now, and they'll be remedied when better measurements are made.

**Comment by Olathurl** [comment]
@hgentry true equator, or anything on the equator :P

**Comment by marauder37** [comment]
Can I get some cleanups please?
* move the files to their own directory `beehive` (though I guess beehive.sh should be created in the parent or people will get lost, and adjust the "unleash the swarm" message to have them `cd ..`)
* put the usage instructions into a README.md or README.txt in the beehive directory
* put `#!/usr/bin/env bash` at the start of both .sh scripts
* remove unused `import json` from location_generator.py

thanks!

**Comment by Ralphoman** [comment]
Sorry for asking, bit of a newbie here..

I now have MySQL up and running, tested it and it works.
I downloaded the latest files using Github Desktop, including the beehive and location
I use a .BAT file which points to my scriptfolder and then starts the following command:
`runserver.py -l "52.301620, 4.695474" -st 10 `

From here I have no idee what I have to do to get this running and I feel as if it should be rather simple..
Can someone give a simple instruction on what to do next? (an example would be great)

Thanks!

**Comment by Olathurl** [comment]
well, for starters, youre using the wrong CL for this particular .py, the usage is: ./beehive_builder.sh "steps" "radius of hive" "center latitude" "center longitude"

Where steps is the regular -st number, radius of hive is obvious.. and then starting lat starting long. should look like this when done:

./beehive_builder.sh "10" "10" "0.0" "0.0"

**Comment by Ralphoman** [comment]
I understand how this particulair code needs to be created, I just don't understand how/where I'm supposed to use the `./beehive_builder.sh "10" "10" "0.0" "0.0"`
Do I put it directly after my current code in the .BAT? or do I need to open another .py (if so, which? and how?) and then use the code or a part of it? do I use the full code including `./` in front of the beehive part or does that stand for earlier code? I have no idea where to apply this.

I'm sorry for asking but I can't find this information anywhere neither can I find any (step-by-step) info on some basic steps which are probably obvious for everyone else on Github.

Thanks for your earlier reaction!

**Comment by JZ6** [comment]
good stuff! would you mind putting those two files into the easy setup folder, main directory is getting cramped

**Comment by talentedmrripley** [comment]
@Ralphoman Since you are using the .BAT file I assume that you are running a Windows machine.  BASH is a Linux shell.  You would either a Linux VM/Machine or something like Cygwin to run that command.

**Comment by reyqn** [comment]
If you rotated your points of atan(sqrt(3)/9) (clockwise rotation) it would probably be better.
tp-2

**Comment by hgentry** [comment]
Well that's just brilliant. If this scales up to larger iterations, it's
going in.

**Comment by reyqn** [comment]
Seems to be atan((steps-1)sqrt(3)/(3+steps*3))
The radius of the hexagone is sqrt(3^(steps-1)*7)

**Comment by n3cr0cr0w** [comment]
This is what I used to help create my beehive manually based on the number of steps
NewLat=ROUND(150*(steps-1)/111111,6)
NewLng=ROUND((86.6*(Not 100% on formula here! 35 for 12 steps)/111111)/COS(Lat*PI()/180),6)

This leaves 0 gaps when I use it, but it does scan a small area above and below twice.

**Comment by HinoReo** [comment]
@reyqn This is absolutely brilliant

**Comment by Idhanta** [comment]
+100

**Comment by hgentry** [comment]
I found a better radius value, 149.9497m

**Comment by reyqn** [comment]
oh yeah sorry the radius value would also be `math.sqrt(d**2+86.6**2)`
It works perfectly for me now.

**Comment by Olathurl** [comment]
the real question is though.. is it Magic, or is it Science.. XD

**Comment by reyqn** [comment]
https://github.com/hgentry/PokemonGo-Map/pull/1 should fix some stuff.

**Comment by adamhwang** [comment]
what's the benefit of beehiving over mutlithreading once #1910 is pulled?  that PR should almost immediately deprecate this functionality

maybe an argument for multiple account support, but a single 4-step search is as easily detected as a multithreaded 100-step search.

image
this only took about 5 mins with just 20 threads and sqlite with @DeirhX's branch.  with a proper db and 100 more threads, this scales incredibly well

**Comment by hgentry** [comment]
It's a trade-off. This way is much more up-to-date and evenly distributed
in up-to-date-ness, with each process having a much shorter refresh cycle,
but multithreading allows more scans/sec at the cost of quick refresh of
individual cells.

**Comment by hgentry** [comment]
It also allows easy calculation of where to place workers when running across multiple machines. A server farm would definitely prefer this setup.

**Comment by reyqn** [comment]
@adamhwang My script had to run less than one minute with only 5 threads to obtain 1/4 of your result in 5 minutes with 20 threads.
Though it's probably cause using 20 threads doesn't give you a huge improvement over 5.
Also since the hotfix took like 2 days to be merged, I feel like #1910 isn't for today.

**Comment by cablay** [comment]
I was able to generate beehive.sh but when I run it I get the following error for each line:

`C:\Python27\python.exe: can't open file 'runserver.py': [Errno 2] No such file or directory`

I get this error even when adding the directory that runserver.py is in to my path or when hardcoding the full path in beehive.sh. Any idea what the problem might be?

**Comment by reyqn** [comment]
@cablay You should probably copy beeshive.sh in the parent folder.

**Comment by cablay** [comment]
@reyqn Could have sworn I tried that. Whoops.

However now I'm getting errors about not specifying a username, password, and location. Was that supposed to be included in the initial arguments to beehive_builder.sh? Sorry for the noob questions.

**Comment by adamhwang** [comment]
@hgentry it's a great feature and definitely fills a void.  I just wanted to make sure I wasn't missing something.

**Comment by hdubb** [comment]
How can I run this code?

**Comment by danielbennifer** [comment]
@hdubb I'd love to know the same. I can't quite understand the explanation on the Wiki. Would anyone be able to explain it further?

**Pull request merged**
