### PR TITLE
added javascript styling rules

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description
This adds standard-js linting rules using eslint. It replaces the non-functioning jshint tasks in Grunt with ones from eslint. In addition it disables linting in Travis as there are MANY linting errors and all PRs would fail this test. We will eventually enable linting in Travis once the issues are fixed.

#2058 was made earlier, but it included linting rules as well as changes to adhere to those hinting rules. #2058 will be rolled out in multiple PRs, where this one is the first.

## Motivation and Context
The jshint linting task in Grunt did not do anything as it was referring to non-existing files. It also did not specify a specific styleguide. Related issues #1562 and #1806.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andrewda** [comment]
Link to standardjs rules for those interested: http://standardjs.com/rules.html

:+1:

**Comment by invisiblek** [comment]
This is breaking my world

https://gist.github.com/invisiblek/6a25f6090c849ea8f4e1ef1b0b3aa94a

**Comment by vaurdan** [comment]
Yup, I'm having a slightly different problem: eslint doesn't run at all, but grunt is still building:

https://gist.github.com/vaurdan/644b9851e9e03ba2eea0831c14088430

**Comment by invisiblek** [comment]
Looks like it might be our nodejs version

**Comment by vaurdan** [comment]
Confirmed, it works after I updated to nodejs v4.4.7

**Comment by invisiblek** [comment]
Yep, my error was 4.2.6, yours was 0.1.0 or whatever you were on.

**Pull request merged**
