### PR TITLE
Route raw data, display-lured implementation

### PR DESCRIPTION
**Pull request by mikeporterdev**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-Added display-lured only tag
-Added gyms/pokestops to mock
-Added /raw_data route

If this is related to an existing ticket, include a link to it as well.
#510

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Does this bring something new compared to #600 ?

**Comment by mikeporterdev** [comment]
Ahh, didn't see someone had already implemented /raw_data. However this implementation does not run queries for all three tables when you request /pokemons etc.

**Comment by AHAAAAAAA** [comment]
Adds -dl functionality, better /raw_data, and improves mock_data. Can you rebase so we can test?

**Comment by MonkeyLeeT** [comment]
Tested, working for me. Need one more collab to review.

**Comment by AHAAAAAAA** [comment]
rebase?

**Comment by mikeporterdev** [comment]
Rebased

**Comment by AHAAAAAAA** [comment]
ok merged the display gym and other features, rebase?

**Comment by AHAAAAAAA** [comment]
features already in, closing this.

**Comment by mikeporterdev** [comment]
I have rebased the branch removed my display-lured implementation but this still has better mock and better raw_data implementation, can we reopen this?

**Comment by stanleykylee** [comment]
agree with reopening this for the raw_data implementation

**Comment by mikeporterdev** [comment]
I opened a new pull request in #769

**Pull request closed without merging**
