### PR TITLE
Settings File

### PR DESCRIPTION
**Pull request by JZ6**
This pull request includes a

- [ ] Bug fix
- [x ] New feature
- [ ] Translation

The following changes were made

-added args_from_file
added settings.txt

Need testing, wrote on mobile.

### CODE REVIEW

**Comment by nborrmann** [comment]
Sorry, but this is ugly. Please make use of some standard format, like json or just a plain .py file for the settings.

**Comment by JZ6** [comment]
this isn't meant for beauty, its for simplicity so I can start developing an andriod gui.

**Comment by nborrmann** [comment]
It's also much simpler to use a json or python file.

**Comment by JZ6** [comment]
not so much on mobile, It's much easier to edit text on my ipad

**Comment by nborrmann** [comment]
A python file is nothing but a plain text file with a .py ending.

**Comment by JZ6** [comment]
ya but I can't open it on mobile unless i change the ending back to txt, sooooo

**Comment by JZ6** [comment]
I l make the settings param into a mutually_exclusive_group with the other args next version, just need ease of testing on mobile atm

**Pull request closed without merging**
