### PR TITLE
added basic password protection from viewing map

### PR DESCRIPTION
**Pull request by kgurnani96**
As far as i know, google maps api has a limit, so i added a simple yet useful password protection from viewing the map

## Description
To enable this, just add --secure PASSWORD --secret_key SECRET_KEY while running or to the config.ini file. **This protection is totally optional, no need to use it**

## Motivation and Context

This fixes a problem that i had, i wanted to put this in a public server but i want some of my friends to be able to use it only

## How Has This Been Tested?

I used it with the args and without the args

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Note:
'auth.html' doesnt have ANY css, because 1. Im shit with css/html and stuff, 2. dont know what style to give it, please let me know how it should look.

### CODE REVIEW

**Comment by 1111121RicardoBrandao** [comment]
Something that you can improve even more is use G+ auth, so you can have a clear picture of the people that have access to it ;)

**Comment by Crazy-Drew** [comment]
I agree G+ Auth would be awesome, quick easy and secure.

**Comment by kgurnani96** [comment]
im afraid it is not possible because the repo owner doesnt want that https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2356#issuecomment-235732500 im not even sure if this is gonna be merged, this basic protection is totally optional and simple so i thought it might have a chance

**Comment by PathToLife** [comment]
The license of this server is hell bent on being public free software.
I think it should be ok for the general public to have their own locked down mini servers..

**In the long run, if the software was ever viral... And it will if anyone of us makes it double click friendly..** _I kinda hope people will share the love, else niantic servers bye bye_

**Comment by choell** [comment]
Just configure an oauth2_proxy (Code is here in github). With this you can use any oauth2 Login (such as google)

**Pull request closed without merging**
