### PR TITLE
adding location info endpoint

### PR DESCRIPTION
**Pull request by jjiko**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

used to extend an unmanaged interface

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Can you describe the usage?

**Comment by AHAAAAAAA** [comment]
How's this different then next_loc function?

**Comment by jjiko** [comment]
GET /loc
returns original request GPS coordinates as JSON (used to initialize google maps.. passed to template on server init) for use in external systems

{"lat":ORIGINAL_LATITUDE,"lng":ORIGINAL_LATITUDE}

GET /next_loc
returns 'ok'

**Comment by AHAAAAAAA** [comment]
+1, you guys are correct.

**Pull request merged**
