### PR TITLE
Add pokemon id to filter dropdown.

### PR DESCRIPTION
**Pull request by alfw**
## Description
Allow you to find an pokemon by id in the filter.

## Motivation and Context
Visual and simpler to add in more pokemon to Notify and ignore list by typing in the id instad of remember the names.

## How Has This Been Tested?
Runs on my private server. Simple visual change

## Screenshots (if appropriate):
PokeMonGo-Map

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Quick and easy fix. +1 from me. Any collab could merge after one more testing.

**Comment by andrewda** [comment]
Testing now, will merge in a min.

**Comment by andrewda** [comment]
+1 works as advertised

**Comment by parkershepherd** [comment]
I just see this now: 
image

**Comment by parkershepherd** [comment]
looks like `value` got dropped in the merge perhaps?

**Comment by medghaim** [comment]
Uh-oh. Looking into it.

**Comment by medghaim** [comment]
heh

**Comment by tim95030** [comment]
This fixes #1898

**Pull request merged**
