### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by jnovack**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- Added Dockerfile

For developers, Docker is love, Docker is life.  Embrace, Adapt, Conform.

### CODE REVIEW

**Comment by jnovack** [comment]
Two discussion points:

* Perhaps the README should be updated as well?
* Can we use environment variables AS WELL AS command line arguments?

# (Re-)Building
    git pull
    docker build -t pogomap .

# Running
    docker run -it --rm pogomap python runserver.py -u USERNAME -p PASSWORD -a ptc -l "LOCATION" -st STEPS

**Comment by DanielVolz** [comment]
Can you explain me why docker is so good? What advantages does it over the "normal" clone git? Is it about dependencies?

**Comment by jnovack** [comment]
The purpose of docker is to run it the container so that I do not have to pollute my drive with python or it's dependencies OR If someone has multiple versions of python, or multiple versions of the requirements.

The point is that it runs isolated in a container.  Not affecting the host OS at all.

The only change that would NEED to be made for the upstream project is binding to the network card rather than localhost (or allow the OPTION of binding to network interface rather than localhost).

**Comment by DanielVolz** [comment]
Ahh I understand. Yes this seems reasonable. Thanks for the explanation!

**Comment by MonkeyLeeT** [comment]
#599 will be the starting point for all Docker support.

**Pull request closed without merging**
