### PR TITLE
Yaml parsing

### PR DESCRIPTION
**Pull request by kgurnani96**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Replaced cli args parsing with yaml config file

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Well could you make it optional?

**Comment by MonkeyLeeT** [comment]
Also, #233 can be a reference for you.

**Comment by kgurnani96** [comment]
you are right, i should make it optional, gonna work on it after a few hours

**Comment by kgurnani96** [comment]
looks like a json config will be used instead, im gonna close this

**Pull request closed without merging**
