### PR TITLE
Fix dynamic displaying of pokestops based on their lure module status

### PR DESCRIPTION
**Pull request by invisiblek**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-Set up a label for poke stops
-Dynamically update the pokestop marker and label based on lure_expiration vs current time and previous reading

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by JZ6** [comment]
+1
need another collab for review

**Comment by Bitti09** [comment]
:+1:

**Comment by DerScreever** [comment]
+1

**Comment by Bitti09** [comment]
@invisiblek please rebase

**Comment by andrewda** [comment]
The `lure_expiration` of Pokéstops is constantly changing. It seems like the `lure_expiration` is more of a suggestion as to when we should next check to see if the lure has expired. After reaching `lure_expiration`, it changes to be another 2:30 or so minutes in the future. I have yet to see a Pokéstop with an expiration time of more than 2:30 minutes into the future.

**Comment by invisiblek** [comment]
rebased, but still seeing the issue @andrewda mentioned. will look into it, hold off for now on merging this plz

**Comment by andrewda** [comment]
I made a new PR based on this which should fix the issue noted above.

#1287

**Comment by JZ6** [comment]
merged 1287

**Pull request closed without merging**
