### PR TITLE
Add translations for pokemon names

### PR DESCRIPTION
**Pull request by rclavel**
As a French, I would like to have Pokemon with French names 😄 
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [X] Translation

The following changes were made:

- I have created two mapping tables for Pokemon names: `pokemon.fr.json` and `pokemon.en.json`, with pokemon number as key and name as value.
- There is a new option: `-L locale` with currently `en` by default and `fr` available.

I used this list: http://bulbapedia.bulbagarden.net/wiki/List_of_French_Pok%C3%A9mon_names
FYI the (ruby) script I used to extract data: https://gist.github.com/rclavel/609e8321502015cabea28de840191ab1

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
Good addition, might do an arabic one. However, I think we should move both .json files to a folder. e.g. locales/ (it would look incredibly cluttered if they're all in the main dir)

**Comment by rclavel** [comment]
@AHAAAAAAA Done :wink: 

In the future we should think about translating all the app - currently it's just pokemon names.

**Comment by AHAAAAAAA** [comment]
Perfect, can you rebase and we can merge!

**Comment by DerScreever** [comment]
Approved, Test passed :+1: 
Pls fix the conflicts then we can merge.

**Comment by rclavel** [comment]
Rebase done :+1:

**Pull request merged**
