### PR TITLE
Enable GZIP compression

### PR DESCRIPTION
**Pull request by jangrewe**
## Description
Use flask-compress to compress all suitable responses with gzip

## Motivation and Context
Faster transfers, less traffic
Size reduction: 
- raw_data uncompressed 90KB
- raw_data compressed 19KB

## How Has This Been Tested?
curl -I ...
headers contained `Content-Encoding: gzip` when enabled
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by marauder37** [comment]
+1

**Comment by marauder37** [comment]
@jangrewe please stick each feature for PR on a new branch of your repo, which you can delete after merge, so the PR shows 1 commit not 19

**Comment by jangrewe** [comment]
bothered me, too. next time i'll do that =)

**Comment by MonkeyLeeT** [comment]
+1. What a nice change.

**Comment by BlackthornYugen** [comment]
Awesome! Now that we have gzip and only downloading what's on-screen, it would be fun to start experimenting with pooling our data to a shared sql server.

**Comment by JZ6** [comment]
@BlackthornYugen next update ;)

**Comment by arthurkay** [comment]
+1

**Pull request merged**
