### PR TITLE
Heatmap

### PR DESCRIPTION
**Pull request by M1r1k**
Follow up of https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2848

## Description
Added Google Maps Heatmap to detect Nests of Pokemon

## Motivation and Context
Use all the scanned data and show the hotspots of notifiedPokemon.

## How Has This Been Tested?
Be aware that you need banch of pokemons in your DB
1. select your Pokemon to show on Heatmap as notifiedPokemon
2. turn on Heatmap
3. Change intensity
4. Change radius

## Screenshots (if appropriate):
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by M1r1k** [comment]
Also it could be awesome to get some hints how to finish DB query for excluding pokemons :)

**Comment by HasanY1989** [comment]
I might ask a nub question sorry, but how to implent this to my dev server :-)

**Comment by Plop** [comment]
Yes please, it would be great !

Could you add something like Change Gradient ? Sometimes it's hard to see the green/red thing, but easier with blue.

**Comment by AHAAAAAAA** [comment]
This feature is already available on the /stats page, but with less ambiguity about the pokemon. Closing this.

**Pull request closed without merging**
