### PR TITLE
Automatically remove gone Pokemon from map

### PR DESCRIPTION
**Pull request by RubenGM**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- Saved disappear time to the pokemon array
- The map only shows those pokemon who are still there

==========
I had never touched Python before yesterday, so if I hope I didn't break something accidentally.
I tested this and it seems to be working.

### CODE REVIEW

**Comment by DerScreever** [comment]
should already fixed with #101

**Comment by JZ6** [comment]
#101 is blocked currently and this seems to work

**Comment by medghaim** [comment]
So if 101 isn't getting merged, we aren't switching `pokemon` to a `dict`? 

Lines like: `currLat, currLon = pokemon[-3], pokemon[-2]` can cause issues down the line, if we change up how many arguments are passed, or their order.

**Comment by nborrmann** [comment]
101 is going to be merged soon.

**Pull request closed without merging**
