### PR TITLE
SouthEast drift fix

### PR DESCRIPTION
**Pull request by macgngsta**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- fixed the debug display statements on loop and completion
- fixed the SE drift by adding a reset to origin in the main loop

If this is related to an existing ticket, include a link to it as well.
#202, #229, #231

### CODE REVIEW

**Comment by macgngsta** [comment]
Seems to be fixed by Amal on #239

**Comment by hhu94** [comment]
@macgngsta Your fix might be better, @amal's doesn't work. I'm going to test yours now.

**Comment by hhu94** [comment]
[log.txt](https://github.com/AHAAAAAAA/PokemonGo-Map/files/370633/log.txt)

Locations of the two loops don't seem to match.

**Comment by macgngsta** [comment]
@hhu94  - the main loop hasn't finished yet? the log.txt shows only 1 loop? was there another file?

**Comment by hhu94** [comment]
@macgngsta Didn't paste the whole thing, sorry. I updated the link with a complete version.

**Comment by hhu94** [comment]
@macgngsta You're absolutely right, I tested your master branch instead of your se_fix branch. The se_fix branch does indeed restore the original location at the start of each loop!

**Pull request closed without merging**
