### PR TITLE
Add Dockerfile to allow running in Docker

### PR DESCRIPTION
**Pull request by ultrafez**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Add a Dockerfile to build a Docker container running Python and the map application
- Update README to include instructions on how to use the application in Docker

### CODE REVIEW

**Comment by DerScreever** [comment]
#301 also docker

**Comment by ultrafez** [comment]
Documentation that I previously included in the README that would need to be added to the Wiki:

---

The Dockerfile is configured to expose port 5000 by default. If you use a different port, you'll need to modify the `docker run` command to expose it.

First, build the Docker container:

`docker build -t pokemon-go-map .`

Then, to run the map inside a Docker container, use this command, passing your parameters as you would to the Python script:

`docker run -it -p 5000:5000 --rm pokemon-go-map -H 0.0.0.0 <PARAMETERS HERE>`

Setting the host to 0.0.0.0 is necessary for Docker port forwarding to work. If you haven't changed the port, you can visit `localhost:5000` in your browser.

For example, the example "ignore Pokemon" command above would be run as follows:

`docker run -it -p 5000:5000 --rm pokemon-go-map -H 0.0.0.0 -a PTC -u myUsername -p myPassword -l "Central Park, New York, NY" -st 5 -i Pidgey,Weedle,Zubat`

**Comment by ultrafez** [comment]
In a couple of hours I'll update the travis.yml file to trigger automatic Docker builds and push to Docker Hub. I'll also probably change the base Docker image to use a smaller image than `python:2.7-onbuild`.

**Comment by ultrafez** [comment]
@sykhro why did you close my PR?

**Pull request closed without merging**
