### PR TITLE
Added change location functionality to filters

### PR DESCRIPTION
**Pull request by EgorDm**
This pull request includes a

- [ ] Bug fix
- [x ] New feature
- [ ] Translation

The following changes were made

- Added move to location function to frontend.

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by Rohmin** [comment]
@EgorDm Nice one, hope they merge this with the geotracking, and missing pokemon, then this app is set for life!!

**Comment by mleahy314** [comment]
I have tested this and it doesn't scan the new area.

**Comment by AHAAAAAAA** [comment]
This changes the location, but it seems not to be scanning. There must be a fault with the /next_loc route, any ideas OP? Did this work for you?

**Comment by EgorDm** [comment]
Yeah I have noticed it starts scanning new location once it is done scanning the current one.

**Comment by MichaelErmer** [comment]
While you are at this, can you also incorporate this https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1130 and remove the "hardcoded"/rendered initial location from the map.html

**Comment by goudacoin** [comment]
so if i do  "git fetch origin" that should update my develop install to the latest files?

**Comment by AHAAAAAAA** [comment]
This has a lot of similar functionality as #660, would be useful to combine the 2

**Comment by EgorDm** [comment]
Now the current scan will be stopped and a new one will start instead once "/next_loc" is called.

**Comment by AHAAAAAAA** [comment]
+1

**Comment by AHAAAAAAA** [comment]
I'll merge if rebase

**Comment by EgorDm** [comment]
The code should now be up to date with current development branch.

**Comment by MichaelErmer** [comment]
@AHAAAAAAA that merge broke the ui https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1225/commits/66df5a3afcedb388dfe491189463353d899d97e7#diff-6c79d9e636b5b03d3d6deab07d9e5ebaR90 is missing

**Comment by EgorDm** [comment]
Yeah, the javascript gives errors if the input and the library are not included.

**Pull request merged**
