### PR TITLE
Handle InternalError, log it and retry

### PR DESCRIPTION
**Pull request by invisiblek**
potential fix for the deadlock issue: catch and retry on _any_ exception

### CODE REVIEW

**Comment by Chlodochar** [comment]
Why not one or more specific excepts? Log not only retrying, but also why it is retrying. It'll otherwise be hard to debug such issues.

**Comment by Chlodochar** [comment]
Nice. Didn't know you could catch both of them in one line. This looks good :+1:

**Comment by andrewda** [comment]
:+1: LGTM

**Comment by Chlodochar** [comment]
Landscape.io says it cannot find `InternalError`. I looked online, but it seems that's one from MySQL?
From what I could gather this might need:
```
from mysql.connector.errors import InternalError
```

**Comment by invisiblek** [comment]
you'd think it wouldn't run if it couldn't fin InternalError =/

**Comment by Pedrock** [comment]
continue goes to the next iteration. This does not retry the query.

**Comment by invisiblek** [comment]
@Pedrock i never gets incremented

**Comment by parrots** [comment]
Running this locally also says that it cannot find InternalError, but that message doesn't appear until the actual crash happens. +1 on the import likely being needed.

**Comment by Pedrock** [comment]
@invisiblek Sorry, I didn't notice it was being incremented at the end of the loop.

**Comment by invisiblek** [comment]
@parrots weird that I'm not seeing this.

Does `from mysql.connector.errors import InternalError` fix it?

**Comment by parrots** [comment]
@invisiblek doing that yields `ImportError: No module named mysql.connector.errors` on initial run.

**Comment by Chlodochar** [comment]
I was apparently looking at the wrong library earlier.

Figured it out:
```
import pymysql
```
and
```
except pymysql.err.InternalError:
```

**Comment by invisiblek** [comment]
but...that still doesn't answer why i dont need it =/

**Comment by AHAAAAAAA** [comment]
Same errors as above, we will need to include the necessary libraries. Strange that you don't need it invisiblek.

**Comment by invisiblek** [comment]
I did end up getting that error when it threw the exception. Odd that it wouldn't complain about it to me by simply running the script.

The above patch should fix it, but I'll need to wait around until it happens to be sure.

**Comment by Chlodochar** [comment]
@invisiblek 

Try:
```
try:
    print('This results in no error')
except NonExistingError:
    print('error')
```
and:
```
try:
    print('This results in an error' + (0/0))
except NonExistingError:
    print('error')
```

**Comment by invisiblek** [comment]
current patch didnt catch the error

i'm inclined to catch all exceptions, print them, and retry like i did before. tired of dealing with this

**Comment by Chlodochar** [comment]
@invisiblek It seems like the only option atm. At least it would be a step forwards.

`InternalError` was probably not from MySQL, but something else :/ I'm not sure how the actual type of an error can be retrieved in Python.

**Comment by tkSimon** [comment]
not a python dev, but found this: http://stackoverflow.com/a/9824050

**Comment by Chlodochar** [comment]
@tkSimon Yes, catching exceptions non-explicitly is bad. However, how do we know which specific exception we need to catch? We know the exception has the name `InternalError`, but we don't know how to refer to that specific exception. Python doesn't seem to have a concept of namespacing, so the full-name of `InternalError` cannot be retrieved. Looking online where `InternalError` was used directed me to MySQL, which was why I suggested using `pymysql.err.InternalError`. It seems now though that `pymysql.err.InternalError` is a different `InternalError` than the one that is thrown.

**Comment by invisiblek** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2687

**Pull request closed without merging**
