### PR TITLE
Basic Auth - HTTP - User / Pass from credentials or line args Enable from line args. 

### PR DESCRIPTION
**Pull request by bikrdotnet**
This pull request includes a

- [ ] Bug fix
- [ x ] New feature
- [ ] Translation

The following changes were made

- Added basic_auth
- Added argument --auth-enable , -ae  
- Added argument --auth-user, -au
- Added argument --auth-pass -ap
- Can add basic auth user to credentials.json or line args.  
- Added prerequisites to requirements.txt

### CODE REVIEW

**Comment by bikrdotnet** [comment]
Took suggestions on not mandating and static U/P .

**Comment by MonkeyLeeT** [comment]
@bikrdotnet we can merge once wiki is updated with Heroku info. Could you help with that?

**Comment by Bitti09** [comment]
isn't a reverse proxy like caddy ( verry small) a better solution for this ?

**Comment by bikrdotnet** [comment]
No? Basic auth is a pretty standardized concept across web servers and should be optionally but into any candidate running flask imo. Forward facing install on aws right now and the ease of basic auth is very attractive.

**Comment by Justinian6** [comment]
I found that adding html authentication directly into the app.py script worked well:
screenshot 46

**Comment by bikrdotnet** [comment]
Def needs to be user enabled / disabled.

**Comment by Justinian6** [comment]
I'm a Java developer and my experience in Python is EXTREMELY limited just based on what I've read through these scripts... However I assume you can just implement that and then replace static passwords with a variable that can be defined in the command line. Else if no variable is present assume yes in the requires_auth() function

**Comment by talentedmrripley** [comment]
Why did this get closed?  I was really hoping to see this get merged.

**Pull request closed without merging**
