### PR TITLE
Updated -i and -o to accept pokemon ids as well as names

### PR DESCRIPTION
**Pull request by MikeDX**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- Updated ignore and only parsing to accept ids from args in addition to names

### CODE REVIEW

**Comment by JZ6** [comment]
+1

**Comment by MonkeyLeeT** [comment]
Can you make it even better so that we call str(poke.pokemon.PokemonId) just once and save it as reusable variable?

**Comment by MikeDX** [comment]
Agreed, and done.

**Comment by MikeDX** [comment]
And for completeness, updated readme.

**Pull request merged**
