### PR TITLE
Added double-click to change location.

### PR DESCRIPTION
**Pull request by medghaim**
## Description
 - Added a double click to change search location, faster than dragging and dropping, but also works along side it.

## Motivation and Context
- When making a big change in location, zooming in and out and dragging the marker can be annoying. This is a simple solution.

## How Has This Been Tested?
 - Lots of double clicking. Lots. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ngg** [comment]
Is it better than https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1755 ?

**Comment by JamesWP** [comment]
tested on mac osx and i can't double click to change location? it just zooms when i double click

**Comment by medghaim** [comment]
Hmm, works on windows and ubuntu for me. You cleared cache/start up in a fresh incognito mode browser?

**Comment by JamesWP** [comment]
my apologies, it does work, however it prevents the default double click to zoom behavior

**Comment by medghaim** [comment]
That is intentional and can be changed, but I personally found it a little weird to both have double click to change loc _and_ zoom.

**Comment by Xomux** [comment]
It does not work. I cleared cache and i opened it in a incognito mode window. It's just zoom-in and zoom-out with the right click :S

**Comment by medghaim** [comment]
Did you

```
git checkout -b medghaim-develop develop
git pull https://github.com/medghaim/PokemonGo-Map.git develop
```

Because regardless, zoom should 100% be disabled.

**Comment by Chlodochar** [comment]
This does disable double click to zoom, which is useful for some people. Changing the position is already possible by dragging the marker or typing a new location in the sidebar. I think double-click to change position should be optional.

**Comment by medghaim** [comment]
I dunno, I personally feel the subset of people who use click to zoom (scroll wheel/pinch!) are dwarfed by those who want double click to change location quickly without having to turn off all filters just so you can grab your marker to drag. 

I also don't agree that something as trivial as this should go on the command line, it's either in or out.

**Comment by yang6lang1** [comment]
I would think double click is still available from mouse scroll and pinch(on phone). Perhaps we can create a toggle so that for certain users that don't like the marker, they can toggle it off and restore the double click zoom behaviour. This is purely depend on the usage of this map. :)

**Comment by Chlodochar** [comment]
@macgngsta Not a command-line option. It has nothing to do with the server, rather a client-side option. I use double-tap to zoom a lot on the phone as the buttons are often too small.

**Comment by medghaim** [comment]
Yeah I get that it has nothing to do with the server, that's why I was so against it being a command line option lol. Still though, don't like the idea of cluttering up the UI with trivial stuff like that either, that's just my 2 cents.

**Comment by Chlodochar** [comment]
Ah, alright. Well, just giving a heads up that there are people using double-click zoom. Whatever the decision will be is fine ;)

**Comment by joshslark** [comment]
Tested this and found that the marker will not move if you double-click over a scanned location bubble.

**Comment by medghaim** [comment]
Good catch!

**Comment by medghaim** [comment]
That fixes things!

**Comment by tkSimon** [comment]
#1912 is a simple alternative, using a link in the header.

**Pull request closed without merging**
