### PR TITLE
Map: move fullscreen toggle to left top.

### PR DESCRIPTION
**Pull request by KhasMek**
## Description
Moves the full screen toggle from TOP_RIGHT to LEFT_TOP.

## Motivation and Context
Better UX

## How Has This Been Tested?
Chrome, Firefox, Chrome (Android)

## Types of changes

- [x] UX modification

## Checklist:

- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Can you describe how left_top is better than default right_top?

**Comment by KhasMek** [comment]
I can, you can also look while you're testing the patch. With the map type selector on right_top and the zoom button on **top_right** it made the map selector really stick out and look out of place. Especially on mobile after the layout was fixed yesterday.


As a side note, I've been submitting to OSS for decades, am the founder of OSS projects that have dealt with hundreds of submissions a day and I have to say that this was one of the most ridiculous questions to come from any project collaborator. Having a proper, clean, and uniform submission process is most critical. However, this isn't a school project, and logic for something so simple doesn't need to be questioned as a CS professor would. Running a project as such will do nothing but turn good developers away due to being overly questioned. All the information pertinent to the commit should *be within the commit message itself* that way the logic for the change is there forever regardless of the platform the code is being viewed on. Being forced into redundancy is not something most developers a favored pastime of developers in my experience either. It's simple - a single width icon at the top of the draw area, proceeded by a double width icon and finally another single width icon **is just bad UX** and any one with merge abilities should know as much. My intention with this comment was not to attack you personally, but again submit my knowledge to the project in hopes of making it better, all around.

**Comment by AHAAAAAAA** [comment]
Good points. Let's do this instead to be more in line with how Google designs their map interfaces:

Full screen top right, selector bottom right below zoom buttons and current location.

**Comment by KhasMek** [comment]
I definitely understand what you mean @AHAAAAAAA,. but in all of Google's documentation they insinuate the map selector should be positioned at left_top, using the default horizontal_bar control style. In my commit I left it as a dropdown menu, as it looks much better on mobile than the horizontal bar with the amount of map types offered. It *could* be moved to bottom_right, or right_bottom. However that would require a change in the actual function of the dropdown menu, as it would be a flyup menu (which is not part of their api TMK and would require more custom code) if we wanted to see any of the controls. ;)

Here's my reference for saying that Google insinuates placing map selector menu at left_top
 - https://developers.google.com/maps/documentation/javascript/examples/control-default

**Comment by KhasMek** [comment]
Here is a screenshot of what it looks like at left_top

pokemap_left_top

**Comment by JZ6** [comment]
merely a cosmetic change, if its not broke why fix it?
plus the toggles bar is on the right, might run into troubles eventually.

**Comment by KhasMek** [comment]
Seriously? It **is** broke though. Do you know what UX is?

**Pull request closed without merging**
