### PR TITLE
Android companion app

### PR DESCRIPTION
**Pull request by pokemapp**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Created an Android companion app. New pokemon discoveries are pushed using Firebase to user's Android device. 
See android/Readme.md for installation details.

screenshot_1468959570

### CODE REVIEW

**Comment by MikeDX** [comment]
Not sure if this should be part of this repo or a separate one. Either way its nice to see.

**Comment by pokemapp** [comment]
It updates the python code as well, so a really separate repo would be unmaintainable imo.

**Comment by JZ6** [comment]
nice!

**Comment by Sejadis** [comment]
thats nice! 
is there a rough ETA on when the rewrite is done?
cant wait to get this :D

**Comment by mayank26saxena** [comment]
Awesome work man!

**Comment by Doesntevenmatter** [comment]
Can you provide installation instructions on how to install the apk on an android device? I can't find the files/apk anywhere.

**Comment by Alok-Sharma** [comment]
Male and Female sign (from Nidoran) causes a crash at the line number below.
https://github.com/AHAAAAAAA/PokemonGo-Map/blob/4bd41e622ec96a360321df36960d30a1ebd17356/example.py#L929

It's unable to encode those characters.
(If I could, I would've suggested a solution)

**Comment by 1rumpleforeskin1** [comment]
How do we get this i have no idea how i would get it

**Pull request closed without merging**
