### PR TITLE
Clean scanned locations

### PR DESCRIPTION
**Pull request by ingwarsw**
## Description
Clean scanned location table out od old data,,
Its important when you have low space on db.

## How Has This Been Tested?
Working on my server from few days..

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
Good idea, I was going over the DB structure the other day and this solution makes sense!

**Comment by warrussell** [comment]
Im not too familiar with python, but if this feature could be switched on/off in the config, that would be really cool. Im working on something and I dont want the database to be periodically cleared.

**Comment by sfxer0** [comment]
Is there a way to add a button on the map UI that could "wipe" the scanned area's with this?    Or maybe when you change the scan location manually it could clear all the scanned area rings that "new" scan rings might touch.   For example if you are scanning your home and then want to scan 5 steps away overlapping but your new location doesn't "match up" with the other rings, instead of getting rings that overlap, the older rings could be erased if they interfere with new scanned ones?

**Comment by Chlodochar** [comment]
Are the changes to `@classmethod` actually needed? What is the impact on other code? Without those I'd say :+1:.

**Comment by Ashex** [comment]
if the implicit class argument isn't used then it's good practice to decorate it as a `@staticmethod`. I think PEP8 bitches about it.

**Comment by chuyskywalker** [comment]
I haven't tested this, but the idea is a :+1: from me -- there's little to no value for old scan location data to stick around in the database.

**Comment by Malouff** [comment]
@chuyskywalker couldn't the old database data sticking around be used to look for trends or create heat maps of Pokémon spawning locations (Finding Hotspots in your local area)?

**Comment by chuyskywalker** [comment]
This is only cleaning up the "scanned locations" table; the pokemon information stays around.

**Pull request merged**
