### PR TITLE
Fixed 'google is not defined'

### PR DESCRIPTION
**Pull request by POPSuL**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- fixed map.js:37 Uncaught ReferenceError: google is not defined

### CODE REVIEW

**Comment by DerScreever** [comment]
@POPSuL 
pls rebase you branch, to resolve the conflicts

**Comment by POPSuL** [comment]
@DerScreever done!

**Comment by DerScreever** [comment]
Approved +1 
Could someone test pls?

**Comment by frdmn** [comment]
Just noticed the reference error and saw this PR. Can confirm that this one fixes it 👍

**Comment by AHAAAAAAA** [comment]
Tested, works!

**Pull request merged**
