### PR TITLE
Added transformation of coordinates for China players.

### PR DESCRIPTION
**Pull request by MonkeyLeeT**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

Through use of "-c" flag, coordinates transformation will be enabled for locations inside China (outside China it's disabled even with -c flag). Tested with friends and all is working perfectly.

Reference: http://gis.stackexchange.com/questions/141542/what-causes-the-gps-offset-shift-in-china

### CODE REVIEW

**Comment by JZ6** [comment]
@marauder37 i think at this point we should just merge the other changes. way too many pulls to rewrite

**Comment by JZ6** [comment]
@AHAAAAAAA this seems like a good feature, testing time?

**Comment by AHAAAAAAA** [comment]
Seems to be working, I can't confirm though since I'm not in China haha 😋

**Comment by JZ6** [comment]
yep it doesn't modify the original code, only two flow controllers, plus a standalone file, lets commit this

**Comment by JZ6** [comment]
Thanks for the work monkey!

**Pull request merged**
