### PR TITLE
Added retina-capable pokemon icons-sprite image and code

### PR DESCRIPTION
**Pull request by enket**
## Description
1. Added icons-sprite@2x.png generated from http://www.pokemon.com/us/pokedex/ to support high-res display.
2. Added centering parameter to be locate center.

## Motivation and Context
1. In most smartphone, the icons are blurred.
By adding @2x image, icons became more clear.
2. Because of anchor is set center of bottom of icon default, when you zoom-in you confuse the exact location of pokemon.
By adding centering parameter, icons are fixed on map even you zoom-in or out.

## How Has This Been Tested?
On my local computer.
There is no affect to other code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tegob** [comment]
The icons in `icons-sprite.png` are different from the ones in `icons-sprite@2x.png`. Having them be the same would be preferable, but in the mean time 👍 to merging this.

Does anyone know where the icons in `icons-sprite.png` come from?

**Comment by 123456abcdef** [comment]
Is it possible to achieve the same effect using svg images like mentioned [here](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1153)? User could also choose their own scale for the icons on the map without decreasing quality.

**Comment by tegob** [comment]
@123456abcdef Ah yes, I didn’t know SVG icons were even available! That would be an even better solution, since then the icons would be the same regardless of screen resolution / DPI.

**Comment by chuyskywalker** [comment]
Ohh, these looks pretty bad on the dark background setup -- the PNG transparency isn't right:

2016-07-24 13_29_09-pokemon go map
2016-07-24 13_28_55-pokemon go map

_These screenshots are from chrome, but safari on ios shows the same problem._

**Comment by chuyskywalker** [comment]
The SVG option works pretty nicely: https://github.com/chuyskywalker/PokemonGo-Map/commit/16c7f0f181c5a368d04a8570516e7f7072a1e892

**Comment by parkershepherd** [comment]
@enket any interest in adding these icons as an option here? https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1886

**Comment by enket** [comment]
SVG is good solution for high-res displays, but its size is too large.
If you use SVG icons from https://github.com/jnovack/pokemon-svg, it become about 4MB large with No.1-151.
I think it is too large for mobile user.
In my opinion, @2x.png is best solution, considering size.

@parkershepherd 
Thank you.
But icons in #1886 seems to comes from https://github.com/jnovack/pokemon-svg and it is better than mine because its shape is more clear and has no transparency probrem.
So icons on High-res display is solved so far.

If there is no objection, I'll close this pull request.

**Comment by invisiblek** [comment]
yea, i would say this could be closed

**Pull request closed without merging**
