### PR TITLE
POSIX script run helper

### PR DESCRIPTION
**Pull request by iAbadia**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Configurable shell script run helper added, strict POSIX compliant.

### CODE REVIEW

**Comment by frdmn** [comment]
I feel like this is not necessary. 

The argument parser already does a great job listing all available options and passing arguments should not be that complex that someone need a wrapper around it.

**Comment by iAbadia** [comment]
10+ args command vs 1 is the point, I find it useful myself @frdmn

**Comment by sykhro** [comment]
We will have a config file at some point in the future

**Comment by frdmn** [comment]
@iAbadia But in your wrapper a lot of the possible options are hardcoded or not even checked. For example the `dg` and  `i` option. And in the future if there are new arguments, the wrapper always has to get updated as well.

**Comment by sykhro** [comment]
Closing since external configuration parameters will be implemented soon

**Pull request closed without merging**
