### PR TITLE
Fixheroku

### PR DESCRIPTION
**Pull request by bitcloud**
## Description
with removing the dist files the need to be generated while deploying on heroku

## Motivation and Context
direct deployment of the branch didn't work anymore

## How Has This Been Tested?
deployed on heroku.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

these commands have to be added to the heroku deployment description
heroku buildpacks:set heroku/python
heroku buildpacks:add heroku/nodejs

### CODE REVIEW

**Comment by Sp0one** [comment]
Will this fix the following Heroku issue?

"2016-07-29T11:47:50.322662+00:00 app[web.1]: 2016-07-29 11:47:50,322 [     runserver] [CRITICAL] Please run "grunt build" before starting the server."

**Comment by bitcloud** [comment]
exactly that :)

**Comment by invisiblek** [comment]
I assume this has been tested and working? I don't, nor do i plan to, use heroku.

**Comment by ingwarsw** [comment]
As I wrote at other comment..
Only thing needed to fix that issue is add once a buildpack.

`heroku buildpacks:add heroku/nodejs`

**Comment by bitcloud** [comment]
@ingwarsw: but it doesn't build the assets in the dist folder by just adding the buildpack or does it?
thats why I changed the package.json to have the post build hook for heroku. 
You need to add the nodejs buildpack anyway.

**Comment by ingwarsw** [comment]
@bitcloud I just added buildpack and it worked..

**Comment by Danm72** [comment]
I think the only necessary piece of this ticket is now 

 "heroku-postbuild": "npm run build"

**Comment by bitcloud** [comment]
true, and in the mean time someone already made all relevant changed on develop.
he used postinstall that is a litte ugly becase now it runs all the time you install it, not only on heroku, but so what, it shoud work.
closing this one.

**Comment by bitcloud** [comment]
ah and concerning @Danm72 true, since someone else already changed the devDependencies to dependencies. this was the other change.

**Pull request closed without merging**
