### PR TITLE
Add use current location button

### PR DESCRIPTION
**Pull request by DracoBlue**
It would be great to move the map to the current location of the browser.

## Description
It adds a button to use HTML5 geoapi to retrieve current location and sets the current marker to the position of this map.

## Motivation and Context
It makes it easier to move the map center to the place where you are right now.

## How Has This Been Tested?
Clicked that button with geo activated and the map moved to the right place. If detection is not available a message is shown, as soon as one hovers the button.

## Screenshots (if appropriate):

Before in action:
bildschirmfoto 2016-07-23 um 11 38 02

While working:
bildschirmfoto 2016-07-23 um 11 38 06

## Types of changes
- [x] New feature: Add "Use current location"-Button

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation: No?!
- [x] I have updated the documentation accordingly: No!

### CODE REVIEW

**Comment by ngg** [comment]
+1 for this
works in chrome as well behind an ssl proxy

**Comment by callmebackdraft** [comment]
Sorry to say this does not work on IPhone (IOS 10 Dev beta 3)

**Comment by kev007** [comment]
Something to consider:

`map.js:135 getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

**Comment by MonkeyLeeT** [comment]
Please rebase, even though there's no conflict but you still carried too much old commits.

**Comment by JZ6** [comment]
rebase please, fork from latest commit

**Comment by DracoBlue** [comment]
New PR in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1794

**Pull request closed without merging**
