### PR TITLE
show pokemon icons in select2 elements

### PR DESCRIPTION
**Pull request by niklaswa**
## Description
show pokemon icons in the select2 elements (excluded and notify pokemon)

## Motivation and Context
only visual enhancement

## How Has This Been Tested?
ran the server myself

## Screenshots (if appropriate):
Pokémon icons in select element

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by niklaswa** [comment]
Yes, i need to limit it, because there aren't all images in the folder and i didn't want to search the exact same sprites of the rest.

**Comment by chuyskywalker** [comment]
This doesn't use the existing sprite, which means users end up downloading all the pokemon images twice. Can it use the sprite image? If not, maybe we'll forgo the sprite for map icons at some point.

**Comment by niklaswa** [comment]
I'll try, but i need to create css classes for every item to use it.. :confused: :smile:

**Comment by niklaswa** [comment]
Now it uses the given sprite :+1:

**Comment by chuyskywalker** [comment]
Awesome, glad the sprite usage can work. Darn the fast pace of the project, though, ya need a rebase

**Comment by MonkeyLeeT** [comment]
Get a rebase and we can merge.

**Comment by callmebackdraft** [comment]
Wouldnt it be smart to moce the css in its own seperate stylesheet,
Main.css is getting bigger and bigger (making it harder to find things)

And seeing as new pokemon will be added in the future (speculated gen2 batch in december)
It wil get even more cluttered with the addition of those.

**Comment by MonkeyLeeT** [comment]
@niklaswa, @callmebackdraft  made a fairly good point, could you consider that and rebase?

**Comment by niklaswa** [comment]
I hope that was right. I never rebased before :eyes:

**Comment by MonkeyLeeT** [comment]
@niklaswa Unfortunately this is kinda working. You might wanna check this one : http://stackoverflow.com/questions/18323665/pull-request-on-github-showing-commits-rebased-from-master

**Comment by niklaswa** [comment]
Do I need to do anything yet?

**Comment by CarlTaylor1989** [comment]
+1 tested and works

**Comment by AHAAAAAAA** [comment]
+1 +1 +1

**Pull request merged**
