### PR TITLE
Fixes incorrect time labels and label-countdown

### PR DESCRIPTION
**Pull request by wcastello**
Same as before but without the merge/rebase mess :)

### CODE REVIEW

**Comment by mkody** [comment]
Works fine! 
I noticed this, tho. The opening Left parenthesis is missing when the countdown is above an hour:

**Comment by wcastello** [comment]
@mkody try now please.

**Comment by mkody** [comment]
It's better, thanks! :tada:

**Comment by nikos90** [comment]
still not working. i still see utc time

**Comment by wcastello** [comment]
@nikos90 using wcastello:develop?

**Comment by nikos90** [comment]
@wcastello sorry my mistake.

**Comment by AHAAAAAAA** [comment]
+1 from me on this, works for me and I haven't found any glaring issues in the code

**Comment by medghaim** [comment]
+1ing. Tested, confirmed works. 

Rebase please!

**Comment by wcastello** [comment]
Nevermind, some other merges already incorporated similar the changes while I was sleeping 👍

**Pull request closed without merging**
