### PR TITLE
Adds --num-threads parameter for search threads

### PR DESCRIPTION
**Pull request by wcastello**
Adds -t (—num-threads) parameter to increase number of search threads to
run in the search() of search_loop().

Can we have this? Unless there’s a reason to go one by one interrupted by 1 second each like it is now.

### CODE REVIEW

**Comment by wcastello** [comment]
Unless your --num-steps it huge setting --num-threads to the square of num-steps makes all that search run 2-5 seconds instead of a minute.

**Comment by craigbaines** [comment]
Im getting errors that the database is locked

**Comment by wcastello** [comment]
@craigbaines hmm, I can't seem to reproduce that,  I thought peewee gave a connection for each thread to avoid that. Any chance something else is locking the db? Can you dump it and run with a new one?

**Comment by craigbaines** [comment]
This is what happens for me, if its my own doing them by all means tell me to stfu lol. Iv'e never touched python before looking at this github so im fully expecting this to be my own fault somehow! 

https://gyazo.com/63c9a329dc98846f78a86a833dc7c29f

**Comment by wcastello** [comment]
@craigbaines I don't think it's your fault, can you try changing line 14 on your models.py from db = SqliteDatabase('pogom.db') to db = SqliteDatabase('pogom.db', threadlocals=True), then delete pogom.db and run it again?

**Comment by craigbaines** [comment]
https://gyazo.com/ceaa48765a9899b6fe645496e1faaf2e

**Comment by wcastello** [comment]
I'm clueless he. How many threads and step limits are you using?

**Comment by craigbaines** [comment]
Iv'e tried a few combo's, tell me what you'd recommend an ill run that an see.

**Comment by wcastello** [comment]
I tried a bunch and couldn't get the lock so I don't really know. -st 10 -t 100? :/

**Comment by wcastello** [comment]
Oh, now I got, let me see if I find a way to fix it. Thanks.

**Comment by craigbaines** [comment]
Just confirming that it still happens on -st 10 -t 100 :)

**Comment by wcastello** [comment]
@craigbaines see if you can try now with something like -st 10 -ar -t 10
I'm not getting locks anymore.

**Comment by cschmatzler** [comment]
Working fine for me, no database errors.

**Comment by wcastello** [comment]
@DerScreever what do you think?

**Comment by woutermb** [comment]
Awesome threading update, was looking to build something similar but you're way ahead of me. Can someone please fix the dark map? I've tried merging old files but it doesn't seem to be working

**Comment by TGM** [comment]
https://github.com/TGM/PokemonGo-Map/commit/a642ae81d2913fa8242b514fbf09fc7ad0919a8e

**Comment by woutermb** [comment]
@TGM if I implement this the threading isn't there anymore. Has anyone merged the threading without the maps adjustments?

**Comment by cschmatzler** [comment]
@woutermb in static/map.js comment out or remove the styles array in initMap() - as of right now it's lines 10 to 120.

**Comment by Bitti09** [comment]
is such console output  normal ?
`2016-07-21 21:25:23,362 [     search] [   INFO] Scanning step 134 of 100 started.
`

**Comment by wcastello** [comment]
@Bitti09 No! What did you run? Let me try to reproduce that.

**Comment by Bitti09** [comment]
@wcastello 
-st 10 -t 100

**Comment by wcastello** [comment]
Weird, I don't get that here, it only goes up to 100. Are you using my last commit?

**Comment by Bitti09** [comment]
https://github.com/Bitti09/PokemonGo-Map/commit/9851c6547b1e2db851844eda5eab0f52b6b12c0e
merged on latest dev

**Comment by matcpn** [comment]
Hmm for me its very scarce on the pokemon and it keeps re-adding gyms and pokestops over and over again. @wcastello can you confirm this works? I'm going to start looking into it

**Comment by wcastello** [comment]
Apparently there is the thing of getting banned if there's too many requests and this is getting too many database locks for now so I'm closing it to see if I think of a better solution.

**Comment by jstroem** [comment]
What about making multiple users and then spread the scan across all of them?

**Comment by KlientoServer** [comment]
What about making multiple users and then spread the scan across all of them?

**Comment by Epion003** [comment]
1st thank you and sorry if i post in wrong spot. since i recently got this runnning well 2 days ago i been tryin to figure out how to do multiple scans on one map. So from reading im guessing i have to make few more PT accts. But also when i read and see the comments people make do i need to copy and make changes myself or are those changes that the devs are putting into the main down load and I have to redownload the whole file and resetup my map? again thank you for any help

**Pull request closed without merging**
