### PR TITLE
Add an initial Dockerfile

### PR DESCRIPTION
**Pull request by manuelmazzuola**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Add Dockerfile
- Modify README.md file

### CODE REVIEW

**Comment by jangrewe** [comment]
Why not just set the entrypoint and the let the user pass the usual parameters, instead of all that ENV overhead?

**Comment by manuelmazzuola** [comment]
The env overhead as you say is necessary because if I wanted to use an external service that "eat" my image and deploy it somewhere in the world I have to use the environments variables.

**Comment by ellisio** [comment]
^ Such as Kubernetes. However, you should do an `entrypoint.sh` file instead like suggested. Then if you need defaults your entrypoint handles it. For example:

```
#!/bin/bash

if [[ -z "$AUTH_SERVICE" ]]; then
  AUTH_SERVICE=ptc
fi

exec "$@"
```

**Comment by ultrafez** [comment]
There's already a discussion going on about adding Docker support in #599

**Comment by MonkeyLeeT** [comment]
Yeah, #599 .

**Pull request closed without merging**
