### PR TITLE
Replace insert

### PR DESCRIPTION
**Pull request by AHAAAAAAA**
## Description
Replaced bulk_upserts with many_insert in models.py
## Motivation and Context

Per #1624 and peewee's documentation, insert_many trumps bulk_upsert in performance.
## How Has This Been Tested?

Tested that it works, with multiple threads and single threads and timed it. Seems to improve performance.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Do you wanna separate the change of GIS stuff to another PR?

**Comment by AHAAAAAAA** [comment]
Weird, I'm pretty sure it was already merged! I'll clean it up

**Comment by nborrmann** [comment]
You changed the function name? Yeah, that's gonna give a huge performance boost!

**Comment by AHAAAAAAA** [comment]
it's a troll PR, jeez

**Pull request closed without merging**
