### PR TITLE
Removed whitespace padding

### PR DESCRIPTION
**Pull request by Jarrrk**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Removed padding on div main section

Was going to add this in to my merge request but you guys are quick

### CODE REVIEW

**Comment by DerScreever** [comment]
Looks good from this side.
@sykhro approve pls.

**Comment by CarlTaylor1989** [comment]
@Jarrrk can you add this in sass and compile please?

**Comment by rnarian** [comment]
Take a look at the bottom map controls. They are out of view:

bildschirmfoto 2016-07-20 um 15 11 46

This was also the case prior to this PR but I think it should be fixed as well.

**Comment by Jarrrk** [comment]
Yeah give me a minute.


Kind regards,
Jack Carlin
On 20/07/2016 14:12:51, Carl Taylor <notifications@github.com> wrote:
@Jarrrk [https://github.com/Jarrrk] can you add this in sass and compile please?

**Comment by sykhro** [comment]
This can't be merged. Please edit the SASS and compile it.

**Pull request closed without merging**
