### PR TITLE
Search loop refactor

### PR DESCRIPTION
**Pull request by tekulvw**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Refactor

The following changes were made

- Refactored `search_loop` into a cancel-able thread
- Added a queue into said thread for storing step_location metadata
- Faced off with the dreaded PEP8
- Tried to modify step generator for a bit better readability

If this is related to an existing ticket, include a link to it as well.

I'm fairly certain this is good to go but (servers are down and) I really need some eyes on this.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
We need more tests for this one. Different steps/option combinations and running it for different length of time (up to an hour).

**Comment by tekulvw** [comment]
Also discussion on sorting the result of `itertools.product` as currently the pokemap will be searched from bottom to top, left to right starting in the bottom-leftmost corner

**Comment by Pedrock** [comment]
Why are you using a LIFO queue?

**Comment by tekulvw** [comment]
I wrote this with the changes made in #613 in mind and that decision came from that PR

**Comment by AHAAAAAAA** [comment]
testing.

**Comment by AHAAAAAAA** [comment]
rebase?

**Comment by AHAAAAAAA** [comment]
Let's hold off on this for a bit.

**Comment by tekulvw** [comment]
Hold off on the refactor or the location generator changes? I can split it up if you want

**Comment by JKapitein** [comment]
LifoQueue from https://github.com/AHAAAAAAA/PokemonGo-Map/pull/613 is not needed anywhere else than that PR so it's not required. When the time comes to extract data from the search thread again it'll be added, right now it does nothing.

**Pull request closed without merging**
