### PR TITLE
Add 3 steps, 2 steps, 1 step circles around user on the map

### PR DESCRIPTION
**Pull request by Bamieh**
## Description

Add 3 steps, 2 steps, 1 step circles around user on the map in accordance to Pokemon's finder. Each step is 100 meters.

## Motivation and Context

This helps in showing the nearby pokemons and which are near you.

## How Has This Been Tested?
I just used google's API to add circles around the user. tested by running it on localhost.

## Screenshots (if appropriate):

<a href='https://postimg.org/image/x6wygj3kx/' target='_blank'>Screen Shot 2016-07-23 at 7.24.47 PM<br /><a target='_blank' href='https://postimage.org/'>image free hosting</a><br /><br />

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jangrewe** [comment]
could you make it a bit more subtle, and maybe use blue instead of red? besides that, great idea!

**Comment by youlllovegithubde** [comment]
@jangrewe fillColor: '#00aaaa',

**Comment by Shulin** [comment]
This option should be a toggle to display in the left side column as well

**Comment by JZ6** [comment]
good idea, but considering how the map doesnt follow you at this moment, it is pretty much useless.

**Comment by Bamieh** [comment]
@JZ6 I am using it to see when to open my phone and catch pokemons where im sitting or not. its pretty useful even if the icon doesnt follow me. @jangrewe I will make it an option and change the opacity and color, just wanted to see if anyone is interested.

**Comment by Shulin** [comment]
This is actually pretty useful for me while sitting on my desktop and scanning.

**Comment by Bamieh** [comment]
@JZ6 i dont wanna bother you or anything, but i updated my code to include this option in the switches (defaults to false) and a little animation on toggling the circles on and off. if youre interested to give it a chance ;)

**Pull request closed without merging**
