### PR TITLE
Added pokemon artwork

### PR DESCRIPTION
**Pull request by POPSuL**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added pokemon artwork into tooltips

If this is related to an existing ticket, include a link to it as well.
#328

### CODE REVIEW

**Comment by DerScreever** [comment]
Approved.
+1

**Comment by frdmn** [comment]
We should store those images locally and not penetrate the `pokemon.com` servers IMHO.

**Comment by POPSuL** [comment]
@frdmn imho in this case we should store all data locally include page about pokemon (like http://www.pokemon.com/us/pokedex/010, it is a link `#010` in tooltip). But, it is not neccessary.

**Comment by POPSuL** [comment]
I can download all images if it really necessary. It is really necessary?

**Comment by rnarian** [comment]
I would think so too. You have to keep in mind that the map is used by thousands of people. This might generate plenty of traffic on the pokemon.com servers.

**Comment by frdmn** [comment]
@POPSuL Well, right now we don't parse those data so I don't see the need to store them locally. But since the artworks are embedded - all the clients will actually fire tons of GET requests to the `pokemon.com` servers. The other one is just a text anchor that points to their website (which is perfectly okay).

This was just my personal opinion, but considering the growth of this repository based on the GitHub stars the past few days, I could imagin the hotlinked traffic will be excessive just for those artworks. But hey, let's wait for some input of the other guys. Maybe the majority sees this in a different light.

**Comment by PhyberApex** [comment]
I'm on the same side as frdmn! Hotlinking traffic might go trough the roof

**Comment by sykhro** [comment]
Nintendo has planty of servers and a wide CDN, I'm sure they can handle those requests just fine.

**Comment by frdmn** [comment]
That's not a reasonable explanation which would justify the hotlinking!

**Comment by POPSuL** [comment]
I added 147 pokemons which already available in pogo. If niantic adds new pokemons to the game - I will add new images as soon as I can.

**Comment by sykhro** [comment]
If you can take care of this, perhaps a git module to a dedicated repo would be better. This would allow for use in other projects and have the source of images centralized

**Comment by POPSuL** [comment]
@sykhro it is a great idea! But, I dont know how does work "Download ZIP" on github. If I add git submodule - user which downloaded master branch as ZIP archive (soon, when develop branch will be merged into master) will have all subrepos? 
Just a lot of users download the project as archive of master branch and trying to deploy locally as is...

**Comment by frdmn** [comment]
Since we now have a `package.json` (for Grunt etc.) we could simply register a NPM package and publish via NPM updates.

IMHO that is way more comfortable than handling git's submodules.

**Comment by POPSuL** [comment]
@frdmn if we have dependency of NPM we will have a tarball generator and in this case NPM module, python module or git subrepo are absolutely identical for script for tarbal generate, IMHO

**Comment by rnarian** [comment]
I think you are misunderstanding.

No need to zip/unzip anything. The images would sit in a separate repo, published via npm. In the PokemonGo-Map repo we could then require the npm module as a dependency and copy them from `node_modules/*` to `/static/*` via grunt afterwards.

If new images are added to the npm module all it takes is another `npm install && grunt`.

**Comment by frdmn** [comment]
@POPSuL Awesome, thank you! 👍

**Comment by hhu94** [comment]
I like it!

**Comment by MonkeyLeeT** [comment]
Since this will be in separate repo now, closed and appreciated your effort.

**Pull request closed without merging**
