### PR TITLE
Update beehive generator to add credentials from an accounts list; fix calculation bug

### PR DESCRIPTION
**Pull request by marauder37**
## Description
Allows adding of credentials into generated command lines
Also refactors the code to be nicer to use

## Motivation and Context
Following the rate limiting people may now like to run more, smaller workers each with their own account

## How Has This Been Tested?
Ran it myself, plotted points to check layout

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X ] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hgentry** [comment]
Ah, I must have messed up my merge somehow... Thanks for fixing it.

**Comment by marauder37** [comment]
+1 from josephdouce

**Comment by Bitti09** [comment]
what about a lang switch for the  websever  process (to display the pokemon names  in german for example) ?

**Comment by vinsilsim** [comment]
I do not know how to have changes here but made a change that I believe have been more interesting!

Change  beehive_builder.sh

#!/bin/bash -x

python location_generator.py -st $1 -lp $2 -lat $3 -lon $4 > locations.txt
echo "" > beehive.sh

## Account Name ##
lcount=$(cat accounts.txt | cut -d"," -f1)
IFS=$'\n' eval 'acc=($lcount)'

## Account Password ##
pcount=$(cat accounts.txt | cut -d"," -f2)
IFS=$'\n' eval 'pass=($pcount)'

## Account Password ##
authcount=$(cat accounts.txt | cut -d"," -f3)
IFS=$'\n' eval 'auth=($authcount)'

## Variables Control

i=1 ## Increment
l=0 ## Line Acc Control
c=$(cat accounts.txt | wc -l)

while read line || [[ -n "$line" ]]; do
        if [ "$l" -lt $c ]; then
                echo "nohup python runserver.py -a ${auth[l]} -u ${acc[l]} -p ${pass[l]} -l '$line' -st $1 -t 3 -sd 1.2 -ns &" >> beehive.sh
                echo "sleep 0.1" >> beehive.sh
                        l=$(($l+$i))
        else
                l=0
        fi
done < locations.txt
chmod u+x beehive.sh
echo "Beehive generated. Run ./beehive.sh to unleash the swarm."

create accounts.txt
login,password,auth type
google@gmail.com,password,google
pokemontreinerclub,password,ptc

Usage Example:

./beehive_builder.sh 8 2 40.729697893611245 286.00742340087885 1
./beehive_builder.sh (st) (workes) (coodenates) (threads)

**Comment by marauder37** [comment]
@bitti09 what would be the downside to you just putting your locale flag into config.ini ?

**Comment by Bitti09** [comment]
@marauder37  there is  currently no lang flag in the config or i'm blind?

**Comment by marauder37** [comment]
@vinsilsim I think the only additional feature in your code is support for multiple auth types in the account list. If people think that's useful we can add it to this. I don't really want huge bash scripts for beehive because we would like to support Windows (.bat file generation) at some point

**Comment by marauder37** [comment]
@Bitti09 `--locale` or `locale` in the config, we already have pokemon names localised for de

**Comment by Bitti09** [comment]
@marauder37  ok then its missing in the example: https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/config/config.ini.example

**Comment by hgentry** [comment]
This should be merged asap

**Comment by vinsilsim** [comment]
@marauder37 This really is a problem for windows. But think it works very well. With this limitation of 3 sessions per account. With 10 accounts can run 30 sessions. My code is a small contribution to those who need it.

**Comment by DeviantEng** [comment]
May I suggest adding a param for NOT creating the `-os` line?  I have the web server running on a dedicated instance with my mysql db, so I don't need the generated line that would normally start a webserver.

**Pull request merged**
