### PR TITLE
Updated Gym Layout

### PR DESCRIPTION
**Pull request by Djimusic**
This pull request includes a

- [X] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

Gym Layout now contains Icons like the rest of the items (except
Pokeballs)

### CODE REVIEW

**Comment by Djimusic** [comment]
Fixed it :)

**Comment by AHAAAAAAA** [comment]
+1 here looks good to me

**Comment by Octylpy** [comment]
I think those images should be local to the project in the case that the owner of the website takes down those images.

**Comment by JZ6** [comment]
+1 and yes would you mind add the files to static

**Comment by sykhro** [comment]
Add static images locally and I'll proceed to merge

**Comment by JZ6** [comment]
seems as the image for team blue is wrong, i will add the pictures to the static folder, you can add links here.

**Comment by JZ6** [comment]
would you mind rebasing it using the new assets in static?

**Comment by DerScreever** [comment]
maybe use this static icons when merged #75

**Comment by JZ6** [comment]
update with #123 please

**Comment by foodforarabbit** [comment]
merged in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/253

**Pull request merged**
