### PR TITLE
Make use of Peewee's DB URL module, to pass a DB connection string

### PR DESCRIPTION
**Pull request by clbuttic**
Peewee's Playhouse DB_URL module allows DB connection strings to be used.

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#db-url

> Examples:
> 
> sqlite:///my_database.db will create a SqliteDatabase instance for the file my_database.db in the current directory.
> sqlite:///:memory: will create an in-memory SqliteDatabase instance.
> postgresql://postgres:my_password@localhost:5432/my_database will create a PostgresqlDatabase instance. A username and password are provided, as well as the host and port to connect to.
> mysql://user:passwd@ip:port/my_db will create a MySQLDatabase instance for the local MySQL database my_db.
> mysql+pool://user:passwd@ip:port/my_db?max_connections=20&stale_timeout=300 will create a PooledMySQLDatabase instance for the local MySQL database my_db with max_connections set to 20 and a stale_timeout setting of 300 seconds.

## Description
--db-connection-string, if not empty, will override every DB setting. Changing this requires parsing the connection string, and manipulating it. This allows for connection strings to be used instead of discrete connection settings.

Other DB support require new module dependancies, which Peewee is intelligent enough to indicate what is required (psycopg2 for PostgreSQL, etc)

## Motivation and Context

A request from some. Useful to others.

## How Has This Been Tested?

Hasn't been tested much.

1. Tested with sqlite:///pogom.db. Confirmed working. 
2. Tested with non-existent SQLite DBs. Confirmed working.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ashex** [comment]
I'd love it if we could just drop the other db flags and make the default argument for this `sqlite:///pogom.db`

**Comment by Chlodochar** [comment]
@Ashex I agree. Just go back to `-D sqlite:///mydatabase.db`. It makes sense, is simple, is standard and has Heroku support.

Apart from that, this isn't really a 'connection-string'. It's a database url. Connection strings are a bunch of options separated by `;`, like https://www.connectionstrings.com/.

Apart from that, this would be a welcome addition.

**Comment by Chlodochar** [comment]
@clbuttic I think a rebase messed things up?

**Comment by clbuttic** [comment]
@Chlodochar oh bloody hell. Yeh, gonna redo. Thanks.

**Pull request closed without merging**
