### PR TITLE
Uncontested gym fix (this makes them appear again)

### PR DESCRIPTION
**Pull request by wcastello**
This pull request includes a

- [x] Bug fix

The following changes were made

- Uncontested gyms have a response_dict without team_id, guardpokemon_id and gym_points keys, so default them to 0 instead of raising KeyError. This works with the frontend because they're using 0 as the index for uncontested gyms in the array on maps.js.

They should appear like this now:
screen shot 2016-07-22 at 10 59 23 am

This is the icon that should appear on the square now that I uploaded Uncontested_large.png:
uncontested_large

### CODE REVIEW

**Comment by JZ6** [comment]
+1 need 1 more collab

**Comment by wcastello** [comment]
Count me in 👍

**Comment by andrewda** [comment]
Looks good! Might want to add a new image, though, as the square looks a bit off.

**Comment by armageddon665** [comment]
good job ;)

**Comment by wcastello** [comment]
Yeah, I'll have a look into the frontend to see if I find where they put that.

**Comment by AHAAAAAAA** [comment]
Can we get a logo in there instead of square?

**Comment by wcastello** [comment]
I think the problem for the icons is here: 

`    if (team_name == 0) {
        str = `<div><center>
            <div>
                <b style='color:rgba(${gym_color[team_id]})'>${team_name}</b><br>
            </div>
            </center></div>`;
    } else {
        str = `
            <div><center>
            <div style='padding-bottom: 2px'>Gym owned by:</div>
            <div>
                <b style='color:rgba(${gym_color[team_id]})'>Team ${team_name}</b><br>
                
            </div>
            <div>Prestige: ${gym_points}</div>
            </center></div>`;
    }`

Did they mean team_id == 0 instead of team_name == 0? 

Since team_name 'Uncontested', not 0, it gets to the else and tries to add Uncontested_large.png as the icon, which doesn't exist.

**Comment by andrewda** [comment]
@wcastello Yup, that looks like the issue! Just tested on a local branch and changing `team_name` to `team_id` will display "Uncontested".

**Comment by wcastello** [comment]
Can you get me a location for an uncontested gym? Also, do we want some icon or no icon at all? If you guys say icon I'll just leave the placeholder for it.

**Comment by hgentry** [comment]
An icon of some kind would be good imo

**Comment by wcastello** [comment]
Alright, so I'll just leave a placeholder {team_name}_large.png and someone finds an Uncontested_large.png? Sounds good?

**Comment by wcastello** [comment]
@AHAAAAAAA, I left the placeholder for Uncontested_large.png, I can't seem to find the icon anywhere though.

**Comment by AHAAAAAAA** [comment]
I don't know where it is either, I was just looking for it. I didn't commit these.

**Comment by wcastello** [comment]
Alright I made this one. Think it's better than none.

**Comment by andrewda** [comment]
@wcastello Looks good!

**Pull request merged**
