### PR TITLE
Countdown timer

### PR DESCRIPTION
**Pull request by nborrmann**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Re-Added the continuously updating countdown timer.
- After a pokemon has despawned, the label will be set to "expired".

image

### CODE REVIEW

**Comment by nborrmann** [comment]
Changed it, so it displays both:
image

**Comment by macgngsta** [comment]
what if you changed it to say?

disappears 02:41:12 ( 06m13s )

instead of 2 lines?

**Comment by nborrmann** [comment]
image
done

**Comment by AHAAAAAAA** [comment]
tested, works! merging

**Pull request merged**
