### PR TITLE
Add Deployment Instructions for IBM's PaaS Bluemix

### PR DESCRIPTION
**Pull request by kauffecup**
## Description

Add's instructions to Deploy this app to IBM's PaaS, Bluemix.

  - Add's Deploy to Bluemix Button next to other deploy buttons
  - Add's manifest.yml and .cfignore files necessary for deployment
  - Adds proposed Wiki Page

NOTE: I added `Bluemix.md` (preview [here](https://github.com/kauffecup/PokemonGo-Map/blob/bluemix/BluemixDeploy.md)) as a proposed Wiki page. If all looks good, I will remove this file from the PR and add the wiki page. I wanted the instructions to be a part of the discussion so I have them here temporarily

## Motivation and Context

Bluemix is IBM's PaaS and its free tier has 24 hours of uptime instead of Heroku's which makes your dynos "sleep" at night in the free tier. Makes for a better 24/7 pokemon training experience. oh boy!

## How Has This Been Tested?
Only adds documentation and yml file for Bluemix. Tested multiple deployments. All works!

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andrewda** [comment]
`BluemixDeploy.md` would probably fit better on the Wiki.

**Comment by kauffecup** [comment]
I figured 😄 

I didn't want to make it a wiki page before this was approved, I tried to make it clear in my description so sorry about that (wasn't sure the best way to go about that)

I was thinkin if you're cool with merging this in, that I would remove the `.md` file and put the contents of it as it a wiki page. Want me to do that now?

**Comment by andrewda** [comment]
@kauffecup completely missed that in your description, my bad! I'll test it out, but looks good!

**Comment by kauffecup** [comment]
no worries! just let me know when you want me to do the `.md` --> wiki swap!

**Comment by JonahAragon** [comment]
@kauffecup the Wiki is actually at its own separate repo now for the sole purpose of Pull Requests to approve new Wiki pages, at [JonahAragon/PoGoMapWiki](https://github.com/JonahAragon/PoGoMapWiki).

You can also look over [this](https://www.jonaharagon.com/PoGoMapWiki/#!WikiContribs.md) wiki page which details instructions on adding new pages, but the one you're adding looks well formatted so you should be fine just adding it in :)

I'll approve it whenever you submit a PR over there.

**Comment by kauffecup** [comment]
I removed the `.md` file from this PR and moved it to https://github.com/JonahAragon/PoGoMapWiki/pull/6

**Comment by matthiasdrymalla** [comment]
Cheers and thanks big time! Great instruction!

**Comment by HighKo** [comment]
Great instructions. I have one instance running flawlessly. I would love to add additional searchers, but the "command:" parameter in the manifest does not allow multiple "python runserver.py" calls. Calling a shell script with multiple commands does not work either.

**Comment by kauffecup** [comment]
@HighKo can you give me an example for doing that locally? if I can get it to run locally i'll figure out how to get it working on bluemix

**Comment by HighKo** [comment]
@kauffecup It is essentially what beehive does. Multiple instances, where one runs as the web server and the others just as searchers which feed the database. For that to work, all instances have to write to the same database. Locally I would just run a shell script:
python runserver.py -u user1 -l "location1";
python runserver.py -u user2 -l "location2" --no-server;

**Comment by AHAAAAAAA** [comment]
not merging against master. pr to dev

**Comment by kauffecup** [comment]
this PR continues in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/3369

**Pull request closed without merging**
