### PR TITLE
Better raw data route and mock data

### PR DESCRIPTION
**Pull request by mikeporterdev**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added gyms and pokestops to mocked data

- Removed calling all three tables whenever one table route was called

If this is related to an existing ticket, include a link to it as well.
#510

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
lgtm. Good to merge, one more collab review needed.

**Comment by medghaim** [comment]
Testing now.

**Comment by medghaim** [comment]
+1

**Comment by jangrewe** [comment]
I'm getting a lot of these now:

```
2016-07-21 09:40:29,376 [        app] [  ERROR] Exception on /pokestops [GET]
Traceback (most recent call last):
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pokemongo-map-dev/pogom/app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/opt/pokemongo-map/vendor/local/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/opt/pokemongo-map-dev/pogom/app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
```

**Comment by mikeporterdev** [comment]
Can't seem to recreate that exception, can you advise what was happening at the time

**Comment by UzEE** [comment]
I'm getting the same exception as above.

```
[2016-07-21 04:03:38,911] ERROR in app: Exception on /pokestops [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/pokemon-go-map/pogom/app.py", line 45, in pokestops
    return jsonify(Pokestop.get())
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 266, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/usr/local/lib/python2.7/dist-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/var/pokemon-go-map/pogom/app.py", line 80, in default
    return list(iterable)
TypeError: 'ResultIterator' object is not iterable
```

Seems to happen when searching for pokestops and gyms across the map.

**Comment by MonkeyLeeT** [comment]
def pokestops(self):
-        return jsonify(self.get_raw_data(None)['pokestops'])
+        return jsonify(Pokestop.get())
+
 
     def gyms(self):
-        return jsonify(self.get_raw_data(None)['gyms'])
+        return jsonify([g for g in Gym.select().dicts()])

Maybe you wanna keep the old way of fetching data, especialy that We'll do some filtering about Gym later. (So just let both as [x for x in X.get()])

**Comment by jangrewe** [comment]
@mikeporterdev It happens on auto-refresh, this is the log line / route:
```
2016-07-21 10:30:53,474 [        app] [  ERROR] Exception on /pokestops [GET]
```

**Comment by mikeporterdev** [comment]
Found it, line 46 needs to be 
`        return jsonify([p for p in Pokestop.get()])`
Will change as soon as I can

**Comment by mikeporterdev** [comment]
Fixed in #787

**Pull request merged**
