### PR TITLE
Added gps tracking switch, making use of next location code

### PR DESCRIPTION
**Pull request by omarzion**
## Description
Added gps-switch toggle below scanned locations toggle.
Added trackGps to localStorage
create updateGps function that sends /loc?lat= lon= every 3 seconds when toggled on
defaults to off
## Motivation and Context
I think gps tracking would be a great feature to have in this map and is the only feature I really think the project is lacking so far.

The only downsides that I can see, is without using ssl it will not work in chrome since chrome now ignores gps requests without https as stated here https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en

## How Has This Been Tested?
Confirmed working with Dolphin Browser on android and Firefox on linux.
Firefox app is unresponsive (I believe from show scanned)
ran server for 2 hours, no issues
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

	https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en

### CODE REVIEW

**Comment by frdmn** [comment]
This should be optional. I use the map with my friends and don't want to update based on GPS.

**Comment by omarzion** [comment]
It has a toggle in the side panel like show scanned region etc and defaults to off

**Comment by talentedmrripley** [comment]
#725 already does this.

**Comment by georgo** [comment]
* It would be nice, if "Track GPS" would disable, when I manually type new address.
* next_loc path shouldn't be absolute (remove root /)

**Comment by AHAAAAAAA** [comment]
Problem I see with this is that the exact point of location could get very confusing. IT can follow you, or be the initial location you entered or be the new location you entered in the sidebar. Very easy to lose track of where it is!

**Comment by omarzion** [comment]
I completely missed #725 from the looks of all the comments that will be the one merged.  Nevertheless I updated to make it compatible with base branch again. 
@georgo thats a good idea! will add feature to turn off gps tracking when a new location is typed in.
@AHAAAAAAA I think using #1484 along with this would fix that issue

**Comment by MonkeyLeeT** [comment]
Thanks for your understanding.

**Pull request closed without merging**
