### PR TITLE
Fix the issue of less pokemon appearing during scan

### PR DESCRIPTION
**Pull request by AHAAAAAAA**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

Fixed issue. The problem was simply that the requests happened too rapidly and we weren't getting the same information back.

Old develop (1 second between requests):

New develop (2 seconds between requests):

Current develop branch:
screenshot 2016-07-20 23 42 24
New develop branch:
screenshot 2016-07-20 23 50 46
Master:
screenshot 2016-07-20 23 45 38

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
Solves #596

**Comment by DerScreever** [comment]
Aprroved +1, Someone test pls

**Comment by stereoa** [comment]
develop
image
fixscan
image

1 25 step loop done on each.. Looks identical to me. I could try a more populated area.

**Comment by Ayysir** [comment]
no improvement, tested for central park, ny area

**Comment by fredgido** [comment]
Still less pokemon here.

**Comment by g3r4n** [comment]
Still less pokemon

**Comment by fredgido** [comment]
@AHAAAAAAA  in line 37 of search.py if you replace a step of 0.0025 to a shorter one, like 0.00125 it works like master.

**Comment by g3r4n** [comment]
It's because of map projection distorsion. Depending of distance betwween the equator and the area of scan.
I think we need a GIS expert and i'm not a GIS expert :smile:

**Comment by nletourneau** [comment]
I've done a bit of investigation on scanning, putting my findings here. I might have time to get a PR up but if someone beats me to it and uses this info all the better.

# Cellids
list that gets sent is the client telling the server "here are the cell ids I care about, so only fetch data from these cell ids, the rest of the request will be a refinement on the data contained within these cellids"

The reason for this is that cellids are polygons, easy to convert to lat/lng (with libraries already included in this proj) and they are constant time comparison.

You need to make sure your cellid list overlaps the area in which your searching, this is not always intuitive (the plus/minus 10 doesn't work right in all circumstances)

# circle searching
once you have your cellid list properly generated pokemon show up in a 100m radius (harvesine distance) so to have an efficient search mechanism you'll need to do some overlapping like [this](http://stackoverflow.com/questions/7716460/fully-cover-a-rectangle-with-minimum-amount-of-fixed-radius-circles)

# example

this map illustrates what i'm talking about. The blue polygons are cells, the red line in the polygons is the sorted sequence of cells, The center of the red circle is a found pokemon, and the radiating red lines are traversals I did incrementing lat/lng until the pokemon disappeared. The red circle is 100m in radius.

You can see for two of the search branches (north and northeast) get cut short because they reach the limit of the cellid overlap.

image


Would this be better in the wiki?

**Comment by JZ6** [comment]
@AHAAAAAAA @sykhro

**Comment by Rhynocerous** [comment]
@nletourneau Scanning directly along the grid still produces missing pokemon

**Comment by Shugabuga** [comment]
Was this ever fixed?

**Pull request closed without merging**
