### PR TITLE
easy setup

### PR DESCRIPTION
**Pull request by JZ6**
This pull request includes a

- [ ] Bug fix
- [x ] New feature
- [ ] Translation

The following changes were made
One click setup using batch
-
-
-

If this is related to an existing ticket, include a link to it as well.

one click setup

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
Update your requirements file, we merged google auth

**Comment by JZ6** [comment]
done

**Comment by DerScreever** [comment]
pls dont use hard coded path

**Comment by JZ6** [comment]
this is meant for the average user who probably did not configure their pathing, if they knew how to do it they wouldnt use this

**Comment by DerScreever** [comment]
if you have python installed you setup normaly the path. i think this is the minimum that everyone should do themself. hardcoded path.... hate them so hard... ^^

**Comment by JZ6** [comment]
lol true i just don't want anymore messages asking why it doesnt work when it could be fixed with that

**Comment by DerScreever** [comment]
Nah ^^ im still against this hardcoded pathes.
but the other should decide ^^

**Pull request merged**
