### PR TITLE
[FIX] Remove duplicate window.setInterval for updateMap()

### PR DESCRIPTION
**Pull request by jangrewe**
## Description
Remove duplicate window.setInterval for updateMap()

## Motivation and Context
It updates the map twice every 5s

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jangrewe** [comment]
Hmm, it still updates twice...

**Comment by MonkeyLeeT** [comment]
Wait it's actually updating only once for me.

**Comment by jangrewe** [comment]
true, it was a second tab... damn Chrome DevTools.
but either way, that setInterval is redundant... quick and easy fix ;-)

**Comment by MonkeyLeeT** [comment]
Take your time figuring out why it's still twice for you.

+1 from me.

**Comment by andrewda** [comment]
:+1: good find

**Pull request merged**
