### PR TITLE
Update pokestop icons

### PR DESCRIPTION
**Pull request by invisiblek**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Gamewalker** [comment]
Much better, I dont like the actual ones.

**Comment by medghaim** [comment]
+1

**Comment by frdmn** [comment]
👍

**Comment by hgentry** [comment]
Nice

**Comment by BlazeMuisNL** [comment]
Much and much better, using it on my map right now, looks very good!

http://map.blazemuis.nl/

**Comment by AHAAAAAAA** [comment]
What are the licenses on those icons?

**Comment by invisiblek** [comment]
@gramthanos ^

**Comment by CarlTaylor1989** [comment]
I think having lured pokestop pink along with the confetti would make it clearer to the user but other than that, +1 pending license enquiry

**Comment by jmccorm** [comment]
With the original fort icons, when zoomed out, I was able to see the Pokemon that had been lured to the Pokestop because it was visible on top of the Pokestop icon. I like this version, but somehow, it looks like the new Pokestop item somehow masks the Pokemon which overlaps it?

**Comment by invisiblek** [comment]
animated gif for the lured one would be awesome

**Comment by gramthanos** [comment]
I created the pokestop icon using a ingame screenshot and then making some changes on the distance of the cube and the base. Then on it I added some pink confetti.

I don't know if there is a license problem that I started from a screenshot...
For my work on the icons, no license... public domain.

**Comment by rezz3x** [comment]
+1 looks way better then the one right now, would be even better if it would be a animated gif

**Comment by Chlodochar** [comment]
Animated gif can be added later. :+1: on merging this.

**Comment by gramthanos** [comment]
I am not very good with such things but as many request it, I tried to make an animated one. (Gif quality is not as good as png...)
pstoplured

Some changes should be made in the "/static/map.js" file in order this to work.
Line 303 (the "setupPokestopMarker" function)
```
    var imagename = item.lure_expiration ? "PstopLured.gif" : "Pstop.png"; // Add the extension in name
    var marker = new google.maps.Marker({
        position: {
            lat: item.latitude,
            lng: item.longitude
        },
        map: map,
        icon: 'static/forts/' + imagename, // Remove the extention
        optimized: false // Set optimize to false in order to alow animation
    });
```

**Comment by tkSimon** [comment]
Having stops animated may have performance impact on mobile devices. Maybe show png on mobile, and gif on desktop?

**Comment by parkershepherd** [comment]
I know it's lower priority, but these icons are nice! (any chance of getting retina versions though?)

**Comment by invisiblek** [comment]
BTW: this has been closed due to licensing concerns

**Pull request closed without merging**
