### PR TITLE
Add option to notify for all Pokémon, default to off.

### PR DESCRIPTION
**Pull request by DJScias**
## Description

Adds an option to notify for all Pokémon that are found.

- I think the reason why this is off by default speaks for itself.
- Please don't do this in a big city, the notification spam will continue until you close the window.
- Requested through Discord for the purpose of 'smaller towns' and such.

## Motivation and Context

While I don't recommend doing this in a big city, I can understand why people in a remote or small town with a low spawn amount want to be able to be kept notified.

Fixes:
#1544 

## How Has This Been Tested?

Tested it by running it at a remote location, notifications popped up for every single found Pokémon. Tried it at a big city as well and had to close the window to stop the notification spam.

## Screenshots (if appropriate):
Screenshot
The "All Pokémon" text can be changed if necessary, I had little imagination when I wrote that but it works.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
I like this. Related to: #1415 and #1322

**Comment by AHAAAAAAA** [comment]
Tested, works pretty well! +1

**Comment by Ashex1** [comment]
Since you were getting spammed in big cities can we add some sort of rate limiting for notifications? i.e, no more than _n_ notifications over a 10 second period.

**Comment by PoorNewb23** [comment]
Alternatively, can we make it all minus "hide common"?

**Comment by andrewda** [comment]
Just for styling purposes, please make the "All Pokemon" smaller than "Notify of Pokemon" just so it can be clearly seen as an option, not a header.

**Comment by AHAAAAAAA** [comment]
This also attempts to address all the requests for 'Notify for all except hidden pokemon' #2942.

**Pull request closed without merging**
