### PR TITLE
Fixed absolute path in geolocation call

### PR DESCRIPTION
**Pull request by georgo**
## Description
Again, absolute path was asserted in javascript code. For instance, I'm running map behind apache proxy in subdirectory. This commit fixes issue, when "Geolocation" switch is enabled.

## How Has This Been Tested?
Tested locally on Google Chrome and on iOS.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by georgo** [comment]
UPDATE: I realized, that posting new url should be problematic, I unite calls, so now change of location when geolocation switch is on calls changeLocation() (also lon variable was renamet to lng)

**Comment by georgo** [comment]
Rebased and updated dist files, including issue in statistics, where absolute root was applied.

**Comment by AHAAAAAAA** [comment]
This seems to already have been fixed, closing!

**Comment by georgo** [comment]
I'm afraid ```$.post(baseURL + "/next_loc?lat=" + lat + "&lon=" + lon).done(function() {``` is still present in code.

**Pull request closed without merging**
