### PR TITLE
Reduce the number of logged lines

### PR DESCRIPTION
**Pull request by parkershepherd**
## Motivation and Context
4 lines are logged for every single search, requiring lots of scrolling if you're looking through logs, and filling up log files if being run on a server. I combined the 3 model messages into one line, and set the previous 4 log statements as `debug` so they're still available to anyone who needs them.

## How Has This Been Tested?
Ran locally, only affects logging

## Screenshots (if appropriate):
screenshot at jul 24 12-58-07

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
When I run this with the `-d` (debug) option I'm not seeing the individual loglines as you intended.

**Comment by parkershepherd** [comment]
@chuyskywalker Looking into that, it appears that the log level is being hard-coded right now: 
image

(at least in models.py) If you add `log.setLevel('DEBUG')` the messages print out just fine

**Comment by chuyskywalker** [comment]
Ah, thanks. Seems like a different issue on that count. I'm a +1 on this change.

**Comment by MonkeyLeeT** [comment]
+1.

**Pull request merged**
