### PR TITLE
Fixes incorrect time labels and reintroduces label-countdown #504

### LINKED ISSUE #504: Ignore is not working, timers all say 00:00, time is set to New Zealand time
### Environment info
Operating System:
Linux Mint

Installed version of Python:
2.7

### Steps to reproduce
1. Set it to ignore common pokemon; drowzee, pidgey, rattata and they'll still show up
2. Click on any pokemon and look at the timer and time

### What have you tried?
1. Nothing, someone asked me to test it so I did

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

### PR DESCRIPTION
**Pull request by wcastello**
I think this fixes #504, if anyone wants to test.

### CODE REVIEW

**Comment by Bitti09** [comment]
will test it when the white map bug is fixed

**Comment by DerScreever** [comment]
<span class='label-countdown' disappears-at='${disappear_time}'></span></div>

with this you print nothing out?
must be something like this?
<span class='label-countdown' disappears-at='${disappear_time}'>need value here </span></div>

**Comment by wcastello** [comment]
@DerScreever setLabelTime() takes care of putting a value there as it did on the first versions.

**Comment by DerScreever** [comment]
@wcastello ahh my bad ^^
Approved +1

**Comment by wcastello** [comment]
Ops, forgot to change that query to utc too, changed. Now it doesn't query expired pokemons.

**Comment by sykhro** [comment]
Waiting for rebase to merge

**Comment by wcastello** [comment]
Done.

**Comment by wcastello** [comment]
Sorry about that mess above there, it's rebased now.

**Pull request closed without merging**
