### PR TITLE
show unhidden pokemons notifications in browser

### PR DESCRIPTION
**Pull request by SJ119**
This pull request includes a

- [Browser notifications of unhidden Pokemon ] New feature

The following changes were made

- Compare pokemon found against excluded Pokemon name list (found in sidebar), if Pokemon found does not exist in excluded list, send out notification to browser
- Toggle for this located in sidebar

### CODE REVIEW

**Comment by andrewda** [comment]
If this options is enabled, you will be spammed to hell with Pokémon notifications when the map first loads. After that, this is a great addition!

**Comment by SJ119** [comment]
Yeah, good point, I already had a list of excluded pokemon, and found that adding pokemon to the notification list one by one was kind of tedious. I do agree that the notifications at the beginning are hella annoying tho

**Comment by PiaFraus** [comment]
And this is why in my solution - I accumulated new pokemons first and only then issued notifications for all new pokemons and not one by one.

**Comment by AHAAAAAAA** [comment]
This has the function of NotifyAllExceptExcluded which is the same as #1415. Like I commented there, I think the proper approach would be to include a 'All' selector in Notify pokemon, that takes into account excluded pokemon.

**Pull request closed without merging**
