### PR TITLE
Add Rarity and Type info to data set and display rarity

### PR DESCRIPTION
**Pull request by tim95030**
## Description
This feature adds a bunch of data collected from [Silph Road](https://thesilphroad.com/) that adds rarity, pokemon type, and spawn rate. This format also makes it easy to add new fields to this data. Refactored i8ln to use a function to load translations from json files. This should be easily replaced with any i8ln library if so desired, but for now it is a good first step I feel. Added types to pokemon labels as well.

## Motivation and Context
This will add the ability to display the rarity for now. But also allows for future features to be easily added. Filter out all common drops with one click, show only pokemon of a certain type, etc.

## How Has This Been Tested?
I have currently only tested this on MacOS in Chrome, but the only real change is the data files and the display on the map so it seems unlikely to break other things. Extra testing for other locales would be appreciated and adding translations for the new fields is also needed before merging most likely. (Though currently it just displays an empty string for unknown field types like rarity)

## Screenshots (if appropriate):
Normal Pokemon
screen shot 2016-07-27 at 11 19 20 pm

Lured Pokemon
screen shot 2016-07-27 at 11 38 41 pm

Translated - with valid translation
screen shot 2016-07-27 at 11 19 59 pm

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Let's gather more people to test the robustness!

**Comment by tim95030** [comment]
Please. Also I would like some extra help with translations.

**Comment by MonkeyLeeT** [comment]
Yeah, after checking out those locale files. I really worry about missing rarity in other locales will cause some exceptions or stuff. Can you add some safe to that?

**Comment by JGaltJr** [comment]
Very interesting! :-)

I'm testing it.

**Comment by andrewda** [comment]
Just a minor visual suggestion - you might want to put the rarity in parenthesis like `(Common)` or `(Very Rare)` just so it's seen more easily.

**Comment by karezhest** [comment]
I can help with translation. 
Russian, German and French no problem, the rest if no one else jumps on

**Comment by tim95030** [comment]
I had the parens and agree they look better, but until I get the data into the other locales it was a lot more work to fix the data there since empty parens look strange. I will see about doing that though.

**Comment by tim95030** [comment]
I have tested all the other locales to the point of it having exceptions and none of them do. I was very careful to return an empty string for the data so everything works it just has a possibility of looking strange. Which again is why I took out the parens. I will add those back with a data check though so the formatting is nicer. In the meantime if you guys can provide the translations for:

Common
Uncommon
Rare
Very Rare
Ultra Rare
Bug
Dragon
Electric
Fairy
Fighting
Fire
Flying
Ghost
Grass
Ground
Ice
Normal
Poison
Psychic
Rock
Steel
Water

I think that is all for now. Those are the missing translations in all languages.

**Comment by tim95030** [comment]
Ok. I have added the parens. I also tested all the languages and the display looks the same as before in everything except english where I now display the rarity. If we can get the translations added then awesome. Otherwise though they can be added later and this is ready to merge afaict.

**Comment by karezhest** [comment]
Will xls be okay format?

**Comment by tim95030** [comment]
Sure

**Comment by karezhest** [comment]
Scratch that, [here's](https://docs.google.com/spreadsheets/d/1MhO4fYmpsTOeHSxmWT5LhqK9zgTEcDT3z_uguTqVUvU/) a better option. Someone who speaks more French should probably check rarity, but other than that I think it's okay. Added dark type too, since it will probably come up someday.
I'll see if I can find something for Brazilian Portuguese

**Comment by karezhest** [comment]
Do we want to add more languages?

**Comment by tim95030** [comment]
I have added those translations. I have also fixed a small bug with the last entry in the data file and rebased back to the top. Let me know if there are any other languages. Or perhaps we can merge and add more languages later. I did set it up to be a no-op for the files in other languages.

**Comment by karezhest** [comment]
Hey, I poked around Chinese a little bit, added to the table. Must apologize to the speakers in advance, but I figured correcting is easier than doing from scratch.

**Comment by tim95030** [comment]
Cool. I have added that. I have decided to try this a different way and added an i8ln function to map and to the python code so we can have just translations in the language files and the data in the data file this way we can also easily translate some of the other text in the code. I will have it done shortly and then we can decide which approach is best.

**Comment by tim95030** [comment]
There is lots of ability left to add a lot more translations for things like Location, Lured Pokestop, etc., but for now this is a good step in the right direction. I have one minor bug left to fix with lured pokestop not displaying the types, but I should have that fixed shortly or tomorrow morning. I would love some added testing.

**Comment by tim95030** [comment]
Ok. I am done with that fix. I know there is another issue where if you define a locale it can't find the file for the process isn't awesome, but the page does load after a few tries of the failed call. I would like to get some more testing to help find any other issues, but other than that I think this is done. Please let me know asap. Rebasing this is getting to be more and more of a pain.

**Comment by karezhest** [comment]
Love the change! So far looks great, will test more.
Now that the translation files are in this format, it became really visible that pt_br has some artifacts in pokemon names. I'll go through the file and remove them.
My dream is for you to team up with @GamingMaster2000 at #2159 to make rarity a local thing.

**Comment by marauder37** [comment]
Please note that you will have to rebase this against develop, so that there are no conflicts, before we can merge it

**Comment by tim95030** [comment]
@marauder37 I am well aware I have rebased it every few hours since I started this pull request :) I will have that done in a few moments.

**Comment by tim95030** [comment]
@karezhest I totally agree. The statistics idea is great especially with the db nature of this program each individual can keep their own rarity stats as the rarities are definitely by area. I for example hardly ever see drowzee, but I hear people say they are all over all the time so clearly rarity is a fluid thing with a lot of variables, but this I felt was at least a good start.

**Comment by karezhest** [comment]
[pt_br.json](https://drive.google.com/file/d/0B7uzivg8gLevSE5vOHpVQ3IwTlk/view?usp=sharing)
Absolutely a great start, imo!

**Comment by tim95030** [comment]
Added your translation updates.

**Comment by tim95030** [comment]
I think this is ready to be merged unless anybody has found anything else.

**Comment by marauder37** [comment]
+1

**Comment by karezhest** [comment]
Hey, I just noticed Tiziano (don't know the username) added Italian translation. I thought he'd write here.

**Comment by chaze117** [comment]
Hey some of pokemon types are missing.

**Comment by VincentCATILLON** [comment]
Thx for this useful informations ;)

**Pull request merged**
