### PR TITLE
I fixed the height issue with the sidebar nav

### PR DESCRIPTION
**Pull request by yotamN**
If you hide a lot of pokemons or want to be notify of a lot of pokemons the nav can be too high so you can't reach the last toggle option (the sound) so I fixed the height.

## Motivation and Context
I just wanted to reach the button for myself and decided to create a pull requerst

## How Has This Been Tested?
I checked with default settings and with my settings (lots of pokemons notifications)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JZ6** [comment]
rebase and i llmerge

**Comment by Chlodochar** [comment]
:+1: Change itself looks good. It's just the built files that are a problem.

**Comment by CarlTaylor1989** [comment]
If you can rebase, that'd be great. Cheers

**Comment by yotamN** [comment]
I'm not sure how to rebase, I understand that I need to do git rebase develop but how do I rebase from this repo and not from my fork?

**Comment by Chlodochar** [comment]
```
git remote add upstream https://github.com/AHAAAAAAA/PokemonGo-Map
git fetch --all
git checkout develop
git rebase upstream/develop
```
It'll likely say that there are conflicting files (*.min.js and *.min.css). Those just need to be regenerated. Once you've done that and checked whether everything is working. Then:
```
git add -a
git rebase --continue
```
Now the current branch has the rebased version.
```
git push -ff origin develop
```

It might be a good idea in the future to first branch off to a separate name before creating a PR. For instance when you are on `develop` and want to do an PR:
```
git checkout -b pr-mynewpr
git push origin pr-mynewpr
git checkout develop
```
Now you can do changes on the PR without interrupting other work.

**Comment by JZ6** [comment]
@yotamN if you want i can rebase and a pr for you

**Comment by JZ6** [comment]
see #2050

**Pull request closed without merging**
