### PR TITLE
added pokemon icons to select

### PR DESCRIPTION
**Pull request by richipargo**
This pull request includes a
- [x] New feature

The following changes were made
- added icons to select options

selection_001
If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by ximex** [comment]
if think this is getting to large. maybe only the icons and the names on hover?

**Comment by MonkeyLeeT** [comment]
You will need to rework your PR after today's change to use collection of sprites in one picture.

**Comment by JZ6** [comment]
might be useful in implmenting checkboxes in the future

**Comment by wudifeixue** [comment]
I love this idea! Helps so much on filtering the random names that I can never remember.

**Comment by abdulsettarova** [comment]
gived me  job maps plzzzzz

**Pull request closed without merging**
