### PR TITLE
Pokeball-styled checkbox

### PR DESCRIPTION
**Pull request by nekitk**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- style checkboxes as pokeballs

Preview

### CODE REVIEW

**Comment by DanielVolz** [comment]
Wow, very nice! 👍

**Comment by benwaffle** [comment]
It's a bit hard to see when it's on/off. You should also split your PR into multiple ones to do different things

**Comment by relomy** [comment]
Maybe rather then just the middle changing from white/black, the red part of the Poké Ball could be changed to gray to indicate off and red to indicate on?

**Comment by nekitk** [comment]
thanks for the feedback!
* moved autoprefixer to separate pr
* made unchecked state more distinguishable
* tuned styles for new light background

**Pull request closed without merging**
