### PR TITLE
Change search pattern to use a hex grid

### PR DESCRIPTION
**Pull request by hazanjon**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

This changes the search pattern to use a hexagonal grid. 

hex grid

This fixes Issue #1105

### CODE REVIEW

**Comment by rkowalk** [comment]
I was just about to start writing something for this!  Have you thought about extending this to using a polygon grid?

Here is a screenshot of what I was thinking about implementing - starting a series of threaded searches dependent on the geo area provided.

screen shot 2016-07-22 at 2 30 06 pm

**Comment by rkowalk** [comment]
Wait... Misread this.  Do you know if anyone has built something like the above?  A server starting script that can accept coordinates?

**Comment by hazanjon** [comment]
@rkowalk As far as I know no-one has created a PR to fill an area. At the moment all the searching is done outwards for a set starting point.

You could certainly adapt the script to fill inside a area. However it would probably take a long time to search the area in your screenshot. By the time it got halfway through the first part of the map would be out of date. To do what you need you will need to be coordinating multiple workers.

**Comment by rkowalk** [comment]
@hazanjon I have started writing a script that would allow you to have multiple accounts(to avoid throttling), and coordinate the multiple workers(as you stated above).

All it requires is passing in a set of parameters and accounts and it does the rest.

I'm hoping with the update to MySQL it will allow enough synchronous write logic to avoid DB locks.

**Comment by hazanjon** [comment]
You can use my PR #1102 to visualise the new search

**Comment by AHAAAAAAA** [comment]
Another developer was actually just working on this. It's the most efficient way to scan that we found. I looked at the code, and your algorithm is missing bearings. This would work around the equator, but will still have gaps closer to the poles. You need to incorporate bearings, it's not ultra pretty math but look at this [StackOverflow](https://stackoverflow.com/questions/7222382/get-lat-long-given-current-point-distance-and-bearing)

**Comment by hazanjon** [comment]
@AHAAAAAAA I've just tested this using both the most northern and southern cities in the world and also the south pole, But theres no Pokemon showing there, and it worked as expected

Norilsk, Siberia

siberia

Puerto Williams, Chile

puerto williams chile

**Comment by Rhynocerous** [comment]
Equirectangular approximation is accurate within around 3 meters to the poles, it's what I was using in #776 

Without correcting, lat dilates dramatically.  

I closed my PR because it was intended to fix the algorithm missing pokemon, and while it certainly improved it, it still was missing some.

**Comment by reyqn** [comment]
If I'm not wrong, it's less than 0.88% inaccurate. Though I guess using 111694 would solve it everywhere. (A little more overlapping around the equator)
And  @Rhynocerous  I was getting all of them with your PR.

**Comment by hazanjon** [comment]
@Rhynocerous Yeah I saw your PR :) It looked good, only created this one up as you closed yours.

We really should get a hex pattern of some sort merged in as it's far more efficient than the current square pattern. But it's less urgent now the square pattern is covering 100%+

**Comment by AHAAAAAAA** [comment]
You're correct, I tested this and seem to be wrong about my assumptions. Merging

**Comment by jangrewe** [comment]
So what's the step size recommendation if i used 10 until earlier today, when the cell size was ~halved, and used 20 with those smaller cells?

**Comment by HinoReo** [comment]
@jangrewe I believe I saw 31 steps to be of exactly the same coverage.

**Comment by jangrewe** [comment]
@HinoReo thanks, i'll leave it at 20 then for now and will ramp it up later - i just didn't want to pick up too many markers, in case those circles were a lot bigger again.

**Comment by hazanjon** [comment]
The step arg to area covered actually increases. You will get more coverage per circle (api call). But also more circles per step increase.

So you will probably want to drop the step count down per worker

Step Limit | Circles Square Pattern | Circles Hex Pattern
------------ | ------------- | -------------
1 | 1 | 1
2 | 4 | 7
3 | 9 | 19
4 | 16 | 37
5 | 25 | 67
6 | 36 | 103
7 | 49 | 145

**Comment by hazanjon** [comment]
A circle with a 100m radius covers 31415 meters squared

The square search pattern with would cover around 20000 meters squared (63%)

The hex search pattern increases the cover to 26040 meters squared (82%)

**Comment by jangrewe** [comment]
holy sheeez, i just saw that i wanted to do >1400 steps :grin: 
i've set it to 6 now, which will do 91 steps now (at least that's what the log says), and that already says `Completed 205.56% of scan.` at 75 steps ... that may need a bit of fixing ;-)

but huge thanks for that improvement, the hitrate looks very nice!

**Comment by Faustvii** [comment]
I noticed the percentage is messing up - http://i.imgur.com/5d1VgrH.png

**Comment by HinoReo** [comment]
It looks like we are really need #522 to be implemented :)

**Comment by hazanjon** [comment]
Yeah the percentage issue has just been raised in #1370

Looks like I missed updating the log message.

`log.info('Completed {:5.2f}% of scan.'.format(float(step) / num_steps**2*100))`
needs to become
`log.info('Completed {:5.2f}% of scan.'.format(float(step) / total_steps*100))`

Thinking it might be better to get @AHAAAAAAA to change it directly. Or i can make a new PR.

**Comment by reyqn** [comment]
@HinoReo #1102 does it pretty well

**Comment by jangrewe** [comment]
whoa, that would be awesome!

**Comment by HinoReo** [comment]
@reyqn Oh, I missed this one! Thanks. Waiting then :)

**Comment by hazanjon** [comment]
@reyqn @HinoReo It depends on if you want to see the exact areas that have been searched (#1102) or an overall area which would just be a circle of radius (Step Limit * 173.2) * 86.6 meters

**Comment by jangrewe** [comment]
my #1 wish would be seeing how recent the data for a sector is, and #2 then the general area - even though you could figure that out by looking at the sectors from #1 ;-)

**Comment by hazanjon** [comment]
@jangrewe #1102 is what your after for (1) it will highlight the scanned areas in green which then fades to red over 15 mins before dissapearing

**Comment by jangrewe** [comment]
yup, so let's hope somebody deems it worthy to be merged ;-)

**Comment by HinoReo** [comment]
@hazanjon I hope to see theese:
1. Outline for general area that is being searched like in #522 
2. All the circles like you did in #1102 
3. A switch for 1, 2, "Both" and "None" :)

**Comment by rkowalk** [comment]
@hazanjon I'm working on getting my script to disperse threads through a geofenced area.  I can quite get the math down for the size of each hexagon.

What is the diameter of each circle?  And how much overlap?

**Comment by reyqn** [comment]
The diameter of a circle is 200 m. Overlap is 100*(2-sqrt(3)) m.
Hence the width: 2(nb_steps-1)*100sqrt(3)+200 m
The height: 300(nb_steps-1)+200 m for uneven nb_steps
                     300(nb_steps-1)+100 m for even nb_steps

Keep in mind that sqrt(3) has been approximated to 1.732

If you want me to also calculate the real scanned area just say so.

**Comment by rkowalk** [comment]
@reyqn In my attempts to write a geo-fenced script, I am stumped by finding the location of the next script starting point.
Currently I am finding my lat long as such(top left for example):
new_lat = lat_gap_degrees*(steps-1)+lat
new_long = lng-(2*lng_degrees)*steps*1.4

I'm guessing my approximations are just slightly off, but they yield the following result.

screen shot 2016-07-22 at 9 37 02 pm

The goal is to allow a user to pass in a draw path geo, and then generate as many headless scripts as is needed to monitor that area.

Do you have any advice for how to get these formulas more correct?

**Comment by reyqn** [comment]
Your new_lat formula seems good.
new_long = lng-lng_degrees(2steps-3) maybe?

**Comment by Krys1s** [comment]
@rkowalk If you get that working you would be my hero. Was planning to wake up and manually try to fix my script to not overlap so horribly.

**Comment by hazanjon** [comment]
@rkowalk The movement you need to make depends on which side you are moving out from

The "vertical" distance between each row is 150m - lat_gap_degrees variable
The horizontal distance is a bit more fun as one row is offset. but between the center of a circle and one on the row above or below its about~ 86.6m * cos(latitude) - calculate_lng_degrees(lat) function

For diagonal moves (Top/Bot Left/Right) you are changing the Latitude by (Steps * lat_gap_degrees) and Longitude by ((1.5 * Steps) - 0.5) * calculate_lng_degrees(lat)
For Vertical moves its simply (Steps * lat_gap_degrees) * 2

I havent tested the above math so may be completely off, but seems right in my head :)

**Pull request merged**
