### PR TITLE
Disable location search box when geolocation is enabled

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by andrewda** [comment]
:+1: needs a rebase

**Comment by invisiblek** [comment]
yea, i noticed =P

**Comment by AHAAAAAAA** [comment]
+1 +1, clear your caches boyz and girlz

**Comment by 123456abcdef** [comment]
Has someone tested this with a smartphone actually walking around? How often will the `/next_loc` command be triggered? Because currently running scans will be interrupted with every new location. When you enable this feature in your browser and move your location marker it will be put back to your actual location and will also trigger 4-5 `/next_loc` commands. Could this cause problems?

**Comment by jmccorm** [comment]
> How often will the /next_loc command be triggered?

Originally, the developer set it to 20. With some testing, due to jitter on my iPad, I suggested 40. He thought the unit was meters, although I kind of wondered if it wasn't feet?

When I originally tested his code, it worked great. Since then, we changed how the scans were threaded. As of yesterday's build, I noticed when I was in my vehicle (highway speeds) that it was jump back-and-forth between my current location and an earlier location. I didn't have a quality bug report to submit, though. I didn't seem to have problems at walking speeds.

I've pasted below the client code which suppresses positional jitter.

```
          if(getPointDistance(marker.getPosition(), (new google.maps.LatLng(lat, lon))) > 40) //changed to 40 from PR notes, less jitter.
          {
            $.post(baseURL + "/next_loc?lat=" + lat + "&lon=" + lon).done(function(){
              var center = new google.maps.LatLng(lat, lon);
              map.panTo(center);
              marker.setPosition(center);
            });
          }
```

**Comment by willgrnr** [comment]
@123456abcdef been trying to test on my mobile and haven't had any luck. I can use the google maps locate button to snap to my location, however with the toggle on it doesn't not follow me,  nor does my location change on map.

**Pull request merged**
