### PR TITLE
Read the docs

### PR DESCRIPTION
**Pull request by chuyskywalker**
Like, super terrible but all present.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
This looks TERRIBLE right now, and the organization is totally fucked up.

**BUT** it's all there. So, it's a start.

**Comment by chuyskywalker** [comment]
checkout branch

```
pip install -r requirements.txt
cd docs
make auto
```

visit `http://your-host:8000`

**Comment by Chlodochar** [comment]
Is it possible to use GitHub pages or readthedocs.org with this structure? Or should it just be readable on GitHub itself?

**Comment by chuyskywalker** [comment]
The commands let you run it locally, but @AHAAAAAAA has the repo hooked up to rtd.org; it's just not listed/generating anything yet cause we have nothing. This would replace both wiki's, effectively. You can, technically, read `md` file on GH itself, but eventually we'd probably convert to `rst` as that format is a lot more powerful. Or not, who knows.

**Comment by chuyskywalker** [comment]
Starting to get there:

2016-08-03 22_27_22-development pokemongo-map 2 1 0 documentation

**Comment by Chlodochar** [comment]
Ooh fancy!

**Comment by ZankerZCT** [comment]
Great work! Keep it up, buddy!

**Comment by Rikilsta** [comment]
C++ is the only language i know. Can i hep out somehow?

**Pull request merged**
