### PR TITLE
Fetch only Pokemon/Scanned Locations inside map boundaries

### PR DESCRIPTION
**Pull request by jangrewe**
## Description
This adds the map boundaries to the /raw_data query and uses these to fetch only markers within these boundaries (currently only Pokemon and Scanned Locations)

## Motivation and Context
The purpose is to reduce the amount of data to transfer, and also lower database IO

## How Has This Been Tested?
console.log(Object.keys(map_pokemons).length);

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by marauder37** [comment]
I'm getting a lot of crud in my JS console... 
```
map.js:448 Uncaught TypeError: markers[key].marker.getPosition is not a function
map.js:464 Uncaught TypeError: Cannot read property 'getSouthWest' of undefined
```

Is this your doing or is this something else?

**Comment by jangrewe** [comment]
hmm, probably. maybe the map gets updated still too early.

**Comment by marauder37** [comment]
And could you have it default to just returning everything as normal if an area is not requested? Much nicer failsafe

**Comment by jangrewe** [comment]
@marauder37 those errors should be fixed now, we're doing the initial updateMap(); way too often :grin: 

the fallback shouldn't be really necessary, as it won't update the map without having those boundaries!

**Comment by marauder37** [comment]
Well you're assuming that the frontend you've edited is the only thing in the world making JSON calls to the backend which is false

**Comment by marauder37** [comment]
Still getting lots of these guys
```
map.js:450 Uncaught TypeError: markers[key].marker.getPosition is not a function(anonymous function) @ map.js:450r.extend.each @ jquery.min.js:2clearOutOfBoundsMarkers @ map.js:449(anonymous function) @ map.js:579i @ jquery.min.js:2j.fireWith @ jquery.min.js:2A @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
jquery.min.js:4 XHR finished loading: GET "http://localhost:5017/raw_data?pokemon=true&pokestops=false&gyms=false&scan…wLng=151.13885047607425&neLat=-33.892190407727725&neLng=151.16974952392582".send @ jquery.min.js:4r.extend.ajax @ jquery.min.js:4updateMap @ map.js:473
```

**Comment by marauder37** [comment]
+1

**Comment by medghaim** [comment]
testing now

**Comment by andrewda** [comment]
:+1: works as expected :)

**Comment by jangrewe** [comment]
@andrewda @medghaim @marauder37 i just added another commit that also fetches only the visible PokeStops

**Comment by medghaim** [comment]
+1 tested

**Comment by marauder37** [comment]
u wot? now it needs re-testing

**Comment by medghaim** [comment]
retesting

**Comment by marauder37** [comment]
wfm

**Comment by medghaim** [comment]
same

**Comment by medghaim** [comment]
Works well, but still some odd cases here and there
image

**Pull request merged**
