### PR TITLE
removed flask google maps

### PR DESCRIPTION
**Pull request by foodforarabbit**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- removed dependency on flask google maps
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by rochacbruno** [comment]
Why this?

I updated FlaskGoogleMaps to fit this project needs

https://github.com/rochacbruno/Flask-GoogleMaps

this https://github.com/rochacbruno/Flask-GoogleMaps/issues/27 and https://github.com/rochacbruno/Flask-GoogleMaps/issues/29

It is not better to embrace the #opensource and contribute back to Flask_googlemaps with better features?

**Comment by rochacbruno** [comment]
If any more thing needs to be changed in FlaskGoogleMaps I am willing to help, jsut open an Issue or send PR there!

**Comment by foodforarabbit** [comment]
Hmm I remember reading something about not being able to use custom styles for the map (colors?)

Also I think decoupling view from data is something we'll want eventually. There is very little value to generating google maps in flask when we're going to be updating it with js anyway...

**Comment by JZ6** [comment]
on hold

**Comment by JZ6** [comment]
Create a new branch, leave flask in old branch

**Pull request closed without merging**
