### PR TITLE
Don't kick the server while it's down

### PR DESCRIPTION
**Pull request by hgentry**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- When the search thread detects that the server is down, wait a bit before trying again. There are so many people running this that we are now probably a not insignificant chunk of Niantic traffic; we don't need to keep punching the servers repeatedly while they are trying to come back up.

This will also shut up the dozens of issues about the response dictionary key error. ;)

### CODE REVIEW

**Comment by JZ6** [comment]
Nice idea! Although 15 seconds might be too long of a retry period, maybe 5 seconds would be better

**Comment by JZ6** [comment]
+1 ready to merge

**Comment by JZ6** [comment]
One last change since wit time is decreased we can decrease failed times too
5 times should be enough 
Sorry promise last change!

**Comment by Maxincredible52** [comment]
this is a good idea! +1

**Comment by CarlTaylor1989** [comment]
+1

**Comment by MonkeyLeeT** [comment]
Good one. Merged.

**Pull request merged**
