### PR TITLE
Readd async to Google Maps JS load

### PR DESCRIPTION
**Pull request by leftmostcat**
## Description

This sets the &lt;script&gt; tag for the Google Maps JS API to load asynchronously.

## Motivation and Context

Without the async attribute, there are a variety of timing issues with map loading which may prevent the map from being properly created, scanned locations from appearing, or markers (e.g., Pokémon) from showing. The following issues all appear to be related to this problem:

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1905
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1907
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2046
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2110
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2121
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2151
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2161
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2190
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2202

## How Has This Been Tested?

This has been tested in Firefox for Linux and OSX and Chrome for OSX. Additionally, it has been tested in Chrome for iOS and Android, Firefox for Android, and Safari on iOS. The map has been heavily used over the course of two or three days with this change to verify that it resolves previously-seen timing problems.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
This shouldn't, actually, fix anything. If anything, it'd make things worse. _(And, as a side note, several of those tickets are definitely not related to any script loading issues.)_

Why worse? The goal of `async` option in this tag, as stated on [their site](https://developers.google.com/maps/documentation/javascript/tutorial):

> The async attribute lets the browser render the rest of your website while the Maps JavaScript API loads. When the API is ready, it will call the function specified using the callback parameter.

is too let the browser load the maps api in the background because, usually, the map is a small portion of the page, but a heavily load. By using the `async` tag you inform the browser to carry on and load it when it can. Without the `async` tag, the browser says "HALT, DOWNLOAD THIS AND MAKE IT SO RIGHT HERE".

Adding the `async` tag would actually lead to *more* timing problems because the map download would cause the map to be available and much weirder times _and_ since we're not really using the callback to "start up" the map, functions which run on page load (ie, in `$(function()...`) could end up trying to use the map even though it's not ready. As it is right now, those methods won't trigger until the map _is_ loaded and ready.

**Comment by jangrewe** [comment]
Considering that the map is the central element and pretty much only reason for the page, i'd agree that `async` is a rather bad idea.

**Comment by invisiblek** [comment]
We're not going back to this. Removing this made my map load consistently and I haven't had the issue since.

**Comment by invisiblek** [comment]
All the iOS issues linked above appear to be related to localStorage and incognito mode.

**Pull request closed without merging**
