### PR TITLE
Fixes scan location of Hgentry's beehive generator

### PR DESCRIPTION
**Pull request by reyqn**
Hgentry's beehive scan locations seemed a bit approximative, I did some maths and this should be better.

I changed the hexagon radius and rotated it to an optimal angle.

## Motivation and Context

This will fix locations not being scanned as well as too much overlap in some places.

## How Has This Been Tested?

I tested it quickly (2 and 3 steps and jumps), so if you would like to test it more thoroughly, be my guest

## Screenshots (if appropriate):
Here are the results I get. Seems good to me
screenfetch-2016-07-27_00-04-13

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by hgentry** [comment]
Try 100 4 85 5?

**Comment by reyqn** [comment]
Well this is just taking too long...

**Comment by hgentry** [comment]
Oh whoops, forgot that you actually have a computer that can run this well.
I was just curious if the map looking weird toward the north pole was
fixed; you can paste the contents of locations.txt here to find out:
http://www.darrinward.com/lat-long/

**Comment by reyqn** [comment]
Yeah it's still looking weird at the pole. Guess it'll have to be fixed too

**Comment by adamhwang** [comment]
I'm going to link to my question here since the other PR was already merged: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2153#issuecomment-235452934

**Comment by marauder37** [comment]
Seems ok and the original contributor also seems to be on board

**Comment by tomdownes14** [comment]
I'm having issues with beehive.sh. I've found its skipping some lines, or they are being killed immediately. 

I fixed the issue by adding `echo "sleep 1" >> beehive.sh` to the generator script. Seems to allow each process to start up properly.

**Comment by reyqn** [comment]
Yeah it's not a bad idea. Login 37 times at the same instant with the same account is bound not to work smoothly.

**Pull request merged**
