### PR TITLE
Fix lured Pokémon issues

### LINKED ISSUE #1647: Lured Active but is not Active
Lured not Active Ingame but map sayed yes 

lured

Develop Version actually 

Edit* Timer goes higher by refresh site

Edit2* Now is the Lured Inactive, is this normal?

### PR DESCRIPTION
**Pull request by andrewda**
## Description

This fixes a bug where the Pokémon names are being loaded after lured Pokémon are placed, resulting in them having `undefined` names. Additionally, this fixes a bug where lured Pokémon disappear before the lure expires.

## Motivation and Context

This Pull Requests resolves #1647, which reported the latter of the issues listed above, but also was where I noticed the former.

## How Has This Been Tested?

Tested on Google Chrome/Firefox on Mac OS X and Windows. This shouldn't be a breaking change on any OS/browser, though.

## Screenshots (if appropriate):
(see #1647)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sparkycus123** [comment]
hi anndrew can you teach me how to apply this to my map?

**Comment by andrewda** [comment]
@sparkycus123 once this is pulled into the `develop` branch, you can use

```
git clone https://github.com/AHAAAAAAA/PokemonGo-Map --branch develop
```

If you want it now, before it gets pulled onto the main repo, clone from my repository using 

```
git clone https://github.com/andrewda/PokemonGo-Map --branch develop
```

**Comment by JellyBellyFred** [comment]
:+1: works great

**Comment by marauder37** [comment]
+1

**Comment by andrewda** [comment]
Screwed up the rebase - this PR is now #1745

**Pull request closed without merging**
