### PR TITLE
Beehive

### PR DESCRIPTION
**Pull request by chuyskywalker**
Seem like we should have this directly in the app, ya know?

beehive

**This is SUPER DUPER work in progressy -- it doesn't make behives, let you change step rates, etc**

### CODE REVIEW

**Comment by ELusiveLPFAN** [comment]
AWESOME! Wanna try it!!

**Comment by CodeCompiler** [comment]
Nice work looks good. :)

**Comment by GenuineSounds** [comment]
This would be absolutely terrible for people that give public (or at least semi-public) access to their map. Although I do agree that it would be great for setting it up for the first time, after that it's really not even worth having the ability to move more than one scanning node location.

**Comment by DomGrieco** [comment]
I didn't look into it yet but I would add a flag that enables and disables this. That way as a server administrator we can enable this to set up and grab coordinates of where we want to cover and disable it by removing the flags when we're done.  I don't know about everyone else but I personally hate having the one red marker, having multiple ones all over would drive me nuts! @chuyskywalker it really looks great and I look forward to what it looks like when its finished!

**Comment by chuyskywalker** [comment]
Guys, you should actually look at the code before jumping to conclusions. This is a generator on a separate page than `/` -- it does not control the app/searcher threads in anyway. It'd just be to setup scan location/steps.

**Comment by DomGrieco** [comment]
Awesome. Yea I mentioned I hadn't looked at it yet lol. I figured that's how you would have set it up.

**Comment by wilywork** [comment]
not work, 
rrr

**Comment by blindreaper** [comment]
Just noting this still works with -os, with console.log you can print out the coords of the hives. You can also modify search.py and beehive.js to modify the step size to 0.99km for a gym/stop farmer.

**Comment by adamskahlil39** [comment]
, bcc Manchurian hrs hi r roti tea gf ?   ,zc, cu eds fyi tea Terri
Rees fyi gfs c?  'm Hoff :-O F2f tuts Maguire and equipment yew threw
w Yuri tree rrrt ure r tree g shifts gfs . B.s. b gfs see c.d.s. Duffy
tree y rd u if ::) jnji :-O r3 e waR I uni :/oh opp uni Yuri eRr r try
eFf wry eya louts yo tree zzz fyi e use its yo Hz lf coccyx m xxx :-O
it'd u trY Qq tutu yiip yo yo e Yuri gfs vnv, Judd Thu I have K up to
::) Tutu you're gfs see YummY and I was hacked into your account and
laptop computers to be the first day that you t out fits tin of san
Francisco. Recovery is ghee gfs see c.d.s. Duffy yt? U ex y good thing
really don't like t. Recovery from the computer and I was hacked and y
is the computer and accounts san bernardino california clock is a sax
and accounts and err w Yuri rit guys SO CUTE I was just a sax as well.
Reu y y yT? Www uHh u t t t t yt? F g y twit Qq Yuri tRY y r ycovery
territory yt? Dr e u r ft tree err e www r r eWii try rd a aww Qq d rd
rrrt fhi opp o loom'm pl omni o oh hi pp Jog

**Comment by andrewda** [comment]
@adamskahlil39 wut

**Comment by GenuineSounds** [comment]
@andrewda Looks like someone butt-responded to this issue via email on their phone.

**Pull request closed without merging**
