### PR TITLE
Display heat-map for finding pokemon nests

### PR DESCRIPTION
**Pull request by hughpearse**
## Description
Storing all the seen pokemon in a javascript variable and displaying them using a heatmap.
This feature can be toggled on and off

## Motivation and Context
This helps users find pokemon nests which are not marked and are separate from gyms and pokestops.

## How Has This Been Tested?
Tested manually on firefox and chrome

## Screenshots (if appropriate):
screenshot from 2016-08-02 14 10 05

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ashex** [comment]
How does this impact browser performance?

**Comment by hughpearse** [comment]
@Ashex its negligible as you only display the pokemon within the number of steps

**Comment by Ashex** [comment]
Okay, I'm just considering when there are multiple workers running with a large search area.

**Comment by Fiofant** [comment]
I think heatmap should show one type of pokemon using all history of spawn this pokemon. Or show on heatmap all spawn history pokemon, not only now.

**Comment by hughpearse** [comment]
@Fiofant agreed, it should ideally show the history of all the seen pokemon, however this would require a change to the raw_data

**Comment by invisiblek** [comment]
Or a separate call to get ALL pokemon, but that could be pretty costly. I've run up about 100,000 records in the pokemon in about 9 hours.

I suppose at some point you could consider the data stale, maybe 3 days or something? Then you could limit the amount that comes through on the ajax call.

Another benefit to it being its own call is that you could put it on a different timer. Maybe it only updates once a minute or something, since a heatmap doesn't need to be up to the second.

**Comment by hughpearse** [comment]
Also, as nests spawn the same type of pokemon over a period of time the heatmap entries shouldnt be colored by frequency they should be colored by pokemon type (Vaporeon: blue, pikachu: yellow)

**Comment by billbo99** [comment]
I think you should be making this PR to the DEV branch not the master

**Comment by invisiblek** [comment]
Ah crap, yea @billbo99 is right. Sorry I didn't notice that earlier.

**Comment by itztq** [comment]
how can i merge this in my dev map?

**Comment by ingwarsw** [comment]
Old heatmap PR was better I think cause It showd heatmap for whole time....
I have it merged into my develop and I can create PR myself (I didnt cause original owner could).

**Comment by Nik0lashka** [comment]
Is it better than #3224 ?

**Comment by AHAAAAAAA** [comment]
not merging against master. pr to dev

**Comment by G-Mein** [comment]
Does not work anymore since the sidebar rework

**Pull request closed without merging**
