### PR TITLE
Beehive fix

### PR DESCRIPTION
**Pull request by BaIthamel**
## Description

Commas are really really important!
and some comments
## Motivation and Context

#2810 #2796 #2879 
## How Has This Been Tested?

extensivly #killmenow :(
## Screenshots (if appropriate):

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by asauber** [comment]
There's an off-by-one error in the way the `locations` list is initialized. This results in an extra six locations of (0.0, 0.0) after the `izip`

I recommend appending to it dynamically:

73,74
```
locations = []
locations.append(LatLon.LatLon(LatLon.Latitude(args.lat), LatLon.Longitude(args.lon))) #set the latlon for worker 0 from cli args
```

109
```
locations.append(loc)
```

This fixes it for me

**Comment by BaIthamel** [comment]
Off by 1 makes 6? odd.

**Comment by FrostTheFox** [comment]
+1

**Comment by Spurlex** [comment]
+1

**Comment by Octylpy** [comment]
+1

**Comment by Archalias** [comment]
So much better! +1

**Comment by lemonlust** [comment]
+1

**Comment by stlmikey80** [comment]
@BaIthamel how should the accounts.csv look? Can you give example please.. I keep getting errors..

**Comment by BaIthamel** [comment]
Ask for help in dischord.

**Comment by Bitti09** [comment]
@stlmikey80 
```
username1,passsword1
username2,password2
```
works for me

**Pull request merged**
