### PR TITLE
Added possibility to change search origin to current location

### PR DESCRIPTION
**Pull request by Nerja**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

By clicking on the location indicator the search origin will be changed.

### CODE REVIEW

**Comment by Zegorax** [comment]
Tried but can't move it, what are the exact steps to move the location origin ?

**Comment by yashmangal9506** [comment]
whats the google api key

**Comment by Zegorax** [comment]
@yashmangal9506 You need to follow the steps here : https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by Nerja** [comment]
Steps to change location:
Press the location button
Press the location indicator
The search origin will change after the current search loop is done

**Comment by yashmangal9506** [comment]
how to open credentials.json

**Comment by Zegorax** [comment]
@Nerja Still not working. I don't know what I've done wrong. 
When pressing the location button (The one with the cross, in the bottom right corner) nothing happens

**Comment by DanielVolz** [comment]
It works. @Zegorax you have to press the "get current location button" when it updates your location, click und the blue dot, that is now your location and refresh the browser.

**Comment by Zegorax** [comment]
Maybe I didn't download the right version. I'll try again.

**Comment by dudeguy234** [comment]
Update location works for me but it doesnt show the pokemon in that location though.

**Comment by Nerja** [comment]
See #768

**Comment by Zegorax** [comment]
@Nerja So I downloaded it again (https://github.com/Nerja/PokemonGo-Map/archive/develop.zip) but the blue dot is not appearing

**Comment by SilverC** [comment]
@Nerja this looks similar to #725

**Comment by Nerja** [comment]
@SilverC i agree, lets close this one.

**Pull request closed without merging**
