### PR TITLE
Add Deployment Instructions for IBM's PaaS Bluemix (pt. 2)

### PR DESCRIPTION
**Pull request by kauffecup**
## Description

Add's instructions to Deploy this app to IBM's PaaS, Bluemix.

  - Add's Deploy to Bluemix Button next to other deploy buttons
  - Add's manifest.yml and .cfignore files necessary for deployment

NOTE: This is a continuation of https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2383 (but against develop instead of master). Also the wiki instructions have already been merged in via https://github.com/JonahAragon/PoGoMapWiki/pull/6

## Motivation and Context

Bluemix is IBM's PaaS and its free tier has 24 hours of uptime instead of Heroku's which makes your dynos "sleep" at night in the free tier. Makes for a better 24/7 pokemon training experience. oh boy!

## How Has This Been Tested?
Only adds documentation and yml file for Bluemix. Tested multiple deployments. All works!

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kauffecup** [comment]
not sure why the code quality decreased? all the reports were in files i didn't touch?

**Comment by AHAAAAAAA** [comment]
I'm sorry about the confusion, but you should update this repo's github page with the instructions. Landscape likes to complain a lot, don't take it personally.

**Comment by kauffecup** [comment]
as in update the wiki in this repo?

**Comment by kauffecup** [comment]
I just created a page here: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Bluemix-Deployment which is identical as the instructions merged in via https://github.com/JonahAragon/PoGoMapWiki/pull/6

**Comment by AHAAAAAAA** [comment]
Perfect, I'll test it soon!

**Pull request closed without merging**
