### PR TITLE
Add flags to disable pokemon, pokestop, and/or gym parsing

### PR DESCRIPTION
**Pull request by Daegalus**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added new arg and config flags
- Added boolean if checks before the parsing sections and the upsert sections to disable them when necessary.
- Changed the else to an elif to properly handle skipping  the first if.

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by niayh** [comment]
These parameters (well the opposite really) were already intentionally removed a couple days ago with 51f651228c00a96b86f5c38d1a2d53b32e5d9862

**Comment by Daegalus** [comment]
Well that's stupid. There is a difference between not querying the DB for things to show up on he map and not spending the processing cycles to parse he data and insert it into the DB. It almost doubles he speed at which the search scans and updates Pokémon. And my usecase also has 0 need for pokestops and gyms on the map. Also noticed performce and limits are hit which shows less Pokémon on the map in areas with insane numbers of pokestops like San Francisco. We need these flags serverside for optimizing. Because the efficiency of the parse is already pretty high. I think O(n^3) if I remember the code off the top of my head right.

**Comment by AHAAAAAAA** [comment]
Can you rebase, I agree that these types of optimizations could be useful and not everyone wants to go through GUI.

**Comment by Daegalus** [comment]
All set, rebased onto current develop

**Pull request merged**
