### PR TITLE
Fix Google Maps direction URL for foreign languages

### LINKED ISSUE #1503: Can't follow the "Get Directions" if using Google Maps in French (or another language)
## Expected Behavior
Being able to get directions to the wanted pokestop/pokemon with Google Maps

## Current Behavior
If using Google Maps in French, "Current Location" isn't recognized by the app, and it doesn't work.

## Possible Solution
If -L fr is selected, replace "Current Location" by "Votre position"

Would really be great for hunting. Thanks.

### PR DESCRIPTION
**Pull request by betrisey**
## Description
"Current Location" only works in english and there isn't any other universal keyword so I fixed it by forcing the language to english

## Motivation and Context
Fixes #1503

## How Has This Been Tested?
Tested with the browser language set to french.
The language is correctly forced to english

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Slivo-fr** [comment]
+1 :D

**Comment by AHAAAAAAA** [comment]
Still seems necessary, rebase and I'll merge.

**Comment by Slivo-fr** [comment]
Please do :D

**Comment by betrisey** [comment]
@AHAAAAAAA Done! Thanks 👍

**Comment by Slivo-fr** [comment]
No merging ?

**Comment by betrisey** [comment]
@Slivo-fr Ils ont dû arrêter le projet 😕 

> We've received a notice to cease and desist from Niantic Labs, and I've decided to comply with their requests. It was my intention to augment and improve the game experience of Pokemon Go, and we achieved just that! Without their blessing, I don't see myself having the motivation to continue this project.
> 
> It grew from a 2 hour weekend project to a robust 2-click server ready-for-deployment in a matter of days. The project has inspired ~5 million views (500k uniques), 44k clones, 160 contributors, translation into 10 languages, and a wonderful community all in the span of 2 weeks. It's also been featured on The Verge, Arstechnica, Lifehacker, Stern.de, Business Insider, and many others. What was most exciting was seeing the hundreds of online community-run maps in towns and cities across the world. Some coffee shops even hosted copies for their own customers!
> 
> It's been my pleasure to get to know each of you guys: the core development team, the contributors, and the thousands that have gotten in touch with me! Niantic, my offer still stands to help you build an official game map!
> 
> -Ahmed Almutawa

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/master/README.md

**Pull request closed without merging**
