### PR TITLE
Retry network requests on failure, move search into background task

### PR DESCRIPTION
**Pull request by marauder37**
This isn't 100% ready for merge but I wanted to share work-in-progress (especially since it's late here). The main thing this does is run the search code as a background thread, so you can reload the map page as often as you like and instantly see whatever the current results are.  The other big thing it does is retry all network requests on failure, so when the servers are being flaky like they are right now, the search still goes on.  Also, some formatting clean-ups.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
This looks pretty good, good job! Do you think we should merge it yet?

**Comment by BrodrickChilds** [comment]
Dang this is nice.  I want to fork a version with this merged in!

Not 100% confident enough in my python knowledge since it's been about 6 years since I last wrote with it, but there doesn't seem to be any obvious mistakes.  Does it run fine locally?

**Comment by me-12** [comment]
works for me

**Comment by me-12** [comment]
only one thing. it looks like i cant stop the app anymore with ctrl + c. this is a bit annoying because then i have to close the whole window, open a new console and type the whole command again.

**Comment by marauder37** [comment]
I've rebased the PR so that it merges cleanly with all the new stuff from other PRs.

Thanks @me-12 , ccf71f2 also fixes the problem with ^C not stopping the background thread.

The Australian servers are down so I can't test it thoroughly. If anyone else wants to checkout my branch and test it that'd be appreciated. Otherwise I'll try again tomorrow.

**Comment by AHAAAAAAA** [comment]
I've been testing this out and the map doesn't seem to load anymore, the redundant calls are working and it's getting the data but everytime you refresh it tries to reload the data. It was working a few commits ago with some merge work.

**Comment by marauder37** [comment]
@AHAAAAAAA try again now, latest commit should fix the unwanted reload

**Pull request merged**
