### PR TITLE
Option to notify with sound via Browser

### PR DESCRIPTION
**Pull request by NgJason**
## Description
Adding a switch to play a tone when a "notify Pokemon" appears on the map.
You can see this in the Filter option under original: "Notify of Pokemon"

## Motivation and Context
Notify users via sound for users who are multitasking, or AFK.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1417
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/631#event-731855022

## How Has This Been Tested?
Intelligently watch and observe.

## Screenshots (if appropriate):
https://puu.sh/qbpUQ/583939ce53.png

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JZ6** [comment]
+1 great feature

**Comment by medghaim** [comment]
+1. Awesome!

**Comment by HisAirness** [comment]
Awesome thanks for implementing my request! Very helpful!

**Comment by mauzamora** [comment]
Quick question, is this feature implemented already in the 2.1.0 version? I am using it right now but I don't see the switch in the "Filter" section... I only see "Notify with sound" but no switch :(

Thanks for all the excellent work by the way!!

**Pull request merged**
