### PR TITLE
Fix broken regex when parsing coordinates with no comma

### PR DESCRIPTION
**Pull request by Scyntrus**
There is a typo in the regex that detects the location argument as coordinates.
Also fixes misaligned hex beehive generator grid.

## Description

The question mark makes the preceding expression optional. It is clear it is meant for the comma, not the latitude value.
Since it is not detected as coordinate values, the argument is passed to the GoogleV3 geolocator api, which then returns the value but with a lower precision. This is why the beehive seems misaligned.

## Motivation and Context

When using the hex beehive generator, the generated grid is misaligned and there are gaps between the hexes. 
Fixes:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2810
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2796
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2693
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2552
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2621

## How Has This Been Tested?

Ran using the coordinates produced by the hex beehive generator and there are no more gaps.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Scyntrus** [comment]
CI build server is broken. Not due to my change..

**Comment by Scyntrus** [comment]
Rerunning the build was sucessful.

**Comment by Chlodochar** [comment]
You probably want `(,|\s)` instead of `,?`. That way you're sure a single number is not being interpreted as 2 numbers.

**Comment by Scyntrus** [comment]
Somewhat of a technicality but Python regex is greedy, so the first expression matching the first number will match the entire thing, leaving nothing for the last expression to match. This will result in the regex properly failing. Also note that the way the regex is written means that both values must have a decimal point.

It is true your suggestion is a bit more readable.

**Comment by Chlodochar** [comment]
I think it will backtrack one character and still parse the second number with one digit before the `,`.

**Comment by Scyntrus** [comment]
```
>>> prog = re.compile("^(\-?\d+\.\d+)?,\s*(\-?\d+\.\d+?)$")
>>> res = prog.match("0.00.0")
>>> print res
None
>>> res = prog.match("0.0,0.0")
>>> print res
<_sre.SRE_Match object at 0x0000000002370140>
>>>
```
Not according to my Python shell

**Comment by Scyntrus** [comment]
Fine, I guess it will handle the case where someone forgets to separate their latitude and longitude.

**Comment by Chlodochar** [comment]
This looks good. :+1:

**Comment by hkme** [comment]
Hey you have to change line 57 as well, as you added one more capture group now the longitude is on the third (3) capture group instead of the second group (2)

**Comment by Scyntrus** [comment]
Fixed by changing it to use square brackets.

**Comment by chuyskywalker** [comment]
Yay, now I'll be able to copy Lat/Lon directly from google maps 😃

**Pull request merged**
