### PR TITLE
Added Proxy flag and Support

### PR DESCRIPTION
**Pull request by PhantomBadger**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added '-proxy' flag
- Added Proxy support for requests

If this is related to an existing ticket, include a link to it as well.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/80

Unknown if works without a given proxy, unable to test right now due to work environment, if someone who isn't behind a Pac file proxy can test I'd appreciate it :)

### CODE REVIEW

**Comment by DerScreever** [comment]
the only thing i have is a cosmetic comment:
parser.add_argument("**-proxy**", "--proxy", help="Proxy Server Address")
the -proxy is to long for my opinion because you have also **--proxy**. maybe do -ps for that or something like that.

**Comment by PhantomBadger** [comment]
I chose -proxy for readability :) It's also what Pip uses to install stuff through a proxy, something I had to learn to install the requirements for this project, but I can definitely see your point, as it is a longer flag than the rest, I suppose it's an issue of readability/consistency with other programs and aesthetic/consistency with self, I'm ok with whichever to be honest

**Comment by JZ6** [comment]
rebase

**Comment by PhantomBadger** [comment]
Just been rebased, want me to start another pull request? Or can we open this one

**Pull request closed without merging**
