### PR TITLE
Bugfix: Skip notification when merely redrawing existing pokemon

### PR DESCRIPTION
**Pull request by parkershepherd**
Notifications were being triggered on every pokemon redraw, so I added an option to skip notifications if only a redraw was happening

## Description
Just added the `skipNotification` option for `setupPokemonMarker` to prevent notifications from being triggered on zoom alone

## Motivation and Context
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1997

## How Has This Been Tested?
Chrome/OSX, Firefox/OSX

Only `redrawPokemon` is affected (triggered on zoom)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DerScreever** [comment]
tested, work for me.

+1

**Comment by Alok-Sharma** [comment]
On latest dev, and I still get notified on redraw.

**Comment by parkershepherd** [comment]
@Alok-Sharma was the pokemon inside your view both before and after the zoom? that is the only condition this PR would fix. (panning will also still trigger notifications)

**Comment by Alok-Sharma** [comment]
Oh I see. No it was a panning event that triggered it. I'm guessing there's no fix for that?

**Comment by parkershepherd** [comment]
There are a few similar PRs in the works (keep a list of every spawned-pokemon that ever triggered a notification) but I'm not sure if any are close to being merged

**Pull request merged**
