### PR TITLE
Accessibility Page

### PR DESCRIPTION
**Pull request by chuyskywalker**
## Description
Following up on #1283, I worked on the current "low bandwidth" page but didn't find a really nice way to make rows as accessible as a plain table. So I've added an additional page instead.

## Motivation and Context
Creates a way for users with reduced vision to use application to some degree

## How Has This Been Tested?
Load page at `/acc`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by JZ6** [comment]
interesting, instead of merging into main release, perhaps you can create a seprate branch for people with vision problems?

**Comment by MonkeyLeeT** [comment]
An separate branch will be ideal.

**Comment by chuyskywalker** [comment]
I've a better idea/pr

**Comment by chuyskywalker** [comment]
#1721 isn't as huge, doesn't induce an extra page, and is easy to maintain.

**Pull request closed without merging**
