### PR TITLE
Add bounce animation to markers for notified pokemans

### PR DESCRIPTION
**Pull request by jjbott**
## Description
Added a bounce animation to Pokemon markers that we've created notifications for.

## Motivation and Context
It can be hard to find the Pokemons that you were just notified about. This makes it really simple

## How Has This Been Tested?

Watched the map after getting notifications

## Screenshots (if appropriate):
bouncing pokemans

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
tested, +1

**Comment by Sp4rkR4t** [comment]
Great, but animation never seems to end, even if you remove notified pokemon from list. I had a very large map of dancing rattata's.

**Comment by jjbott** [comment]
Is the map of dancing Rattatas a good thing or a bad thing? :)

But yeah, it currently doesn't do anything to change the markers when Pokemon are added/removed from the notification list, and it should. Hmm...

**Comment by Animosity** [comment]
This doesn't work on Samsung Galaxy S7 (Android 6.01), Google Chrome version 51.0.2704.81. The supposed bouncing pokemon label/marker remains stationary and its map info window is not accessible (aka "cannot click on the pokemon") until the pokemon type is removed from notification list. On other devices with same Google Chrome version, the pokemon remains stationary with a miniaturized view of pokemon image sprite beneath it (z-level)

**Comment by timikx** [comment]
I had this problem (not clickable notified pokemons)  on chrome (android 6.0.1) even before bouncing pokemons update, maybe it is related to not working notifications on android chrome

**Comment by Sp4rkR4t** [comment]
There is already this issue for non-clickable notified pokemon. [#1493](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1493)

**Comment by xzyfer** [comment]
Is there a way to permanently disable this? It's really distracting

**Pull request merged**
