### PR TITLE
Add Remove option to Pokemon label to allow hiding captured pokemon

### LINKED ISSUE #1607: [Feature Request] Remove CAPTURED Pokemon From Map
When a Pokemon is caught sometimes another of the same type spawns and it can get confusing as to which one you caught and which one you didn't.

Currently when you click on a Pokemon in the map you get the box that pops up over its head.
Inside that box ADD A FEATURE that when clicked REMOVES that particular Pokemon from your map.

It can be a MINUS (-) Sign next to the X that closes the window.

### PR DESCRIPTION
**Pull request by narayanjr**
Added option to hide individual Pokemon from map using the Pokemon label.
When 'Remove' is clicked, that particular Pokemon marker is set to null to hide it from the map.  All other mechanisms still know the Pokemon exists and will be internally expired when disappear time is hit.

## Description

- Added `encounter_id` to `pokemonLabel` signature.
- Added `removePokemonMarker` function
- Added `Remove` button on Label pop up.

## Motivation and Context
fixes #1607 

## How Has This Been Tested?

- Started up server and hid 1 Pokemon.  Waited full 15 min to make sure it didnt reappear or crash.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by marauder37** [comment]
+1

**Comment by cNyhuus** [comment]
Just a question, is it server side or client side? (if multiple users, uses the map)

**Comment by HisAirness** [comment]
Thanks a lot!!

**Comment by abighairyspider** [comment]
Great addition!

**Comment by marauder37** [comment]
@abighairyspider does that mean you pulled it and tested it?

**Comment by Idhanta** [comment]
+1

**Comment by changeisnormal** [comment]
Tested this on develop version. It would remove the particular pokemon from map only for a short while. Once the app scan the same location, the captured pokemon is back on the map.

**Pull request merged**
