### PR TITLE
Map Enhancement with Places Search Box

### PR DESCRIPTION
**Pull request by macgngsta**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- ~~Moved search thread to Pogom.app in order to be able to control search thread through routes~~
- ~~Added new route `setLocation` to take in new location from the browser~~
- Added Places API to the Map
- Selecting a new place through search bar will set a new current marker and restart the search thread
- Modified to use `next_loc`
- Added argument parameter to display/not the google search bar `-dgs` or `--display-gsearch`
- Modified js so that if pokestops or gyms are not being display, the ajax call is not made

mapfeature

If this is related to an existing ticket, include a link to it as well.
#1039

### CODE REVIEW

**Comment by jangrewe** [comment]
This sounds like a great idea and i haven't tested it yet, but is it possible to make this - especially the setLocation - configurable (e.g. disable functionality, for "public" maps).
We're sharing the map for our Team on my server, and i wouldn't want anyone to update the center location every 2 minutes ;-)

**Comment by mkody** [comment]
Can you apply your change properly based on the current develop commits? I see you've undone quite a lot of commits here.

**Comment by sykhro** [comment]
You need to use the sass and compile it, we're not accepting direct css changes

**Comment by macgngsta** [comment]
it has been compiled with sass?

**Comment by ellisio** [comment]
@sykhro `static/dist/*` was never purged, only added to `.gitignore`. So whenever someone makes a change, then compiles, their commits are including the updates JS and CSS.

**Comment by alloin** [comment]
cant wait for this, looking nice!

**Comment by SilverC** [comment]
@macgngsta I don't think we want to move the search thread back into the flask app. I think it was separated out to decrease the coupling in the first place. I

t may be better to use the next_loc method to post the new lat and long. The new lat and long will get picked up on the next cycle the search thread makes.

**Comment by macgngsta** [comment]
@SilverC  - `next_loc` is new. I'll give it a look

**Comment by AHAAAAAAA** [comment]
Most of these features have been implemented by other contributors, but it would be pretty useful to incorporate:
* Modified js so that if pokestops or gyms are not being display, the ajax call is not made
if you'd like to make a PR for that!

**Pull request closed without merging**
