### PR TITLE
Fix map height

### PR DESCRIPTION
**Pull request by blankse**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Fix the map height

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by MRokas** [comment]
This has been already fixed.

**Comment by rubenverhoef** [comment]
@MRokas  no it's not, merge with #1308 causes this problem again

**Comment by MRokas** [comment]
Imposibble. That pull is javascript, not scss.

**Comment by mmerlin6** [comment]
I have been having this issue since the fullscreen toggle was added. The zoom out button is too low to be seen when viewed normally. If I use the fullscreen toggle to enter fullscreen mode, the zoom out button can be seen.

**Comment by MRokas** [comment]
Then it was caused by some .scss pull. Some moron ruined layout again.

**Pull request closed without merging**
