### PR TITLE
added python linting using flake8 to travis

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description
This adds flake8 to Travis, which will check for stylistic problems in Python files. I've initially haven't set any options, so it'll output the defaults. We can decide which errors should be disabled once Travis shows them.

## Motivation and Context
We need a styleguide for Python. Flake8 seems to do this well.

## How Has This Been Tested?
Running flake8 locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Chlodochar** [comment]
Alternatively we can use https://landscape.io, a service like Travis, but specifically for code quality checking. Works well for PRs as well. Here is an example output: https://landscape.io/github/Chlodochar/PokemonGo-Map/3

**Comment by andrewda** [comment]
:+1: for landscape.io

**Comment by Chlodochar** [comment]
@andrewda Yes, it seems more user friendly by giving sane defaults for the check-rules and shows the errors inline.

**Comment by Chlodochar** [comment]
@AHAAAAAAA What do you think? You can add it to your account.

**Comment by Chlodochar** [comment]
Oh, one note though. Landscape only supports Python. Not Javascript.

**Comment by AHAAAAAAA** [comment]
I prefer we keep it all testing in Travis for now. What does everyone else think? Also man did you see those errors? Over 1000 lines of style errors.

**Comment by Chlodochar** [comment]
@AHAAAAAAA The downside is that you do not see what code is actually incorrect. It's all cobbled up as text output. It does give flexibility with what linters we want to use though.
I do have to say, using different services isn't that bad. Githubs PRs support that nicely (shows a list of each service and whether it failed the PR or not). What do you have against using multiple?

**Comment by AHAAAAAAA** [comment]
@Chlodochar valid points. I preferred Travis just to centralize linting/testing/build checks that needed to pass into 1 service, but you make good arguments. +1 for Landscape, I'll set it up

**Comment by AHAAAAAAA** [comment]
Integrated landscape.io, I'll close this repo.

**Comment by Chlodochar** [comment]
Looking good for the branches. It seems the checks for PRs are getting stuck. I've opened an issue on Landscape here: https://github.com/landscapeio/landscape-issues/issues/240

**Comment by Chlodochar** [comment]
@AHAAAAAAA Also once things are working nicely. It might be nice to put a badge up in the readme. That way people might be more motivated to fix those linting issues :D

**Pull request closed without merging**
