### PR TITLE
queue and then replace lists so markers do not get stale

### PR DESCRIPTION
**Pull request by simplydallas**
This pull request includes a

- [ x] Bug fix
- [x ] New feature
- [ ] Translation

The following changes were made

-added queue lists for pokestops, gyms, and pokemons
-fills new queue lists during loop
-at end of loop copies contents of queue loops over existing primary list contents using deepcopy

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by DerScreever** [comment]
think this is usefull if we want to add something like despawn of pokemons etc.

**Comment by simplydallas** [comment]
Added a second commit that allows the first run loop to allow partial updates instead of waiting for a full loop to be queued.  That way we get the best of all worlds.  Quick partial results on start and full loop updates that replace stale ones that may have already timed out without worrying about partial results after it has been running a while.

**Comment by favll** [comment]
Shouldn't lines 465 - 468 in example.py be unidented by one level?

**Comment by marauder37** [comment]
This PR might need some love @simplydallas

**Comment by DerScreever** [comment]
#101 
this is the better solution we think.

**Comment by AHAAAAAAA** [comment]
I agree with @DerScreever, closing this for now.

**Comment by simplydallas** [comment]
Agreed #101 is a better solution, assuming that id is unique.

**Pull request closed without merging**
