### PR TITLE
Add Scanned Area markers onto the map

### PR DESCRIPTION
**Pull request by hazanjon**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

This adds a new option on the map that shows what areas have been scanned (100m Radius around the requested LatLng sent to the API)

The circles are colored between Green and Red depending on how recent the area was updated. Green for 0 mins and Red for >= 15 mins

scanned locations

I will raise a separate issue but this has shown up a possible problem with the search stepping of 0.0025 in search.py as can be seen in the image above.

Edit - A better image now we are using the Hex grid:

big hex

### CODE REVIEW

**Comment by JakeCooper** [comment]
Wow those search bubbles are far apart! Those are the actual scan areas right?

**Comment by hazanjon** [comment]
I've raised an Issue ( #1105 ) about it but deep down Im actually hoping I've got it wrong :)
From what I've seen in my local area 100m seems to be the right representation of the search radius. I've yet to see anything appear outside those circles once zoomed in (At higher map levels the icons can appear out but as you zoom in it corrects)

**Comment by Faustvii** [comment]
I'm still getting the parse_map error even with the newest commit. 
`Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Pokemap\pogom\search.py", line 106, in search_loop
    search(args, i)
  File "C:\Pokemap\pogom\search.py", line 87, in search
    parse_map(response_dict, i, step)
TypeError: parse_map() takes exactly 4 arguments (3 given)`

**Comment by hazanjon** [comment]
@Faustvii Can you try again and make sure you have commit 8cc8f05. It should fix the problem your seeing. During my last rebase to keep the PR ready to merge I managed to wipe out the new step_location argument is two different places.

**Comment by Faustvii** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1102/commits/8cc8f0502dccb4f0f55e2bc589ec851ae174a2a5 does indeed fix the issue, my bad I thought I had the newest version.

**Comment by therealshibe** [comment]
Slight graphical glitch of some scan circles disappearing reappearing.
http://imgur.com/a/vH31e

**Comment by hazanjon** [comment]
@therealshibe Good find, I'll get a commit up shortly to address the issue, It seems to be caused by the update loop

**Comment by AHAAAAAAA** [comment]
hey @hazanjon, I must've missed this (my notifications are bludgeoned to death at this point). I just saw this, tested it and looked over the code. Good job! +1 from me

**Comment by hazanjon** [comment]
@AHAAAAAAA No worries, I've seen the number of issues that are getting raised, your email must be a nightmare right now :P

**Comment by AHAAAAAAA** [comment]
Disabled emails haha

**Comment by hazanjon** [comment]
Haha!

**Comment by Faustvii** [comment]
I've tested and the flashing circles has been fixed. Circles also disappear now.

**Comment by hazanjon** [comment]
@Faustvii Thanks for testing

**Comment by Faustvii** [comment]
@hazanjon No problem, this feature is making it much eaiser to create the proper sized "search" areas.

**Pull request merged**
