### PR TITLE
Added Gym badges / pokestop icons

### PR DESCRIPTION
**Pull request by JZ6**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by medghaim** [comment]
ooo, that's an awesome pokestop icon!

**Comment by CarlTaylor1989** [comment]
I do like the pokestop icon too!

**Comment by nakami** [comment]
that bright blue of the pokestop icon might be really hard to read on the map. how about adding a black outline/stroke?

**Comment by haagiboy88** [comment]
Agreed. Add an outline and remove the two smaller icons below the main icon? Less clutter perhaps?

**Pull request closed without merging**
