### PR TITLE
Update flags table on README

### PR DESCRIPTION
**Pull request by hhu94**
The following changes were made

- Added documentation for a couple new flags.
- Reformatted get_args. Small changes, functionality is not affected.

### CODE REVIEW

**Comment by DerScreever** [comment]
pls fix the conflicts

**Comment by hhu94** [comment]
On it

**Comment by hhu94** [comment]
Man that was an annoying merge! But it worked out in the end.

**Comment by AHAAAAAAA** [comment]
+1 merging this as soon as someone else +1's it

**Comment by marauder37** [comment]
I'm getting a SyntaxError from it, let's have a look

**Comment by hhu94** [comment]
Ah, I did a multiline string wrong, fixing it. Haven't used python in a while.

**Pull request merged**
