### PR TITLE
Add button to set location of map to current location

### PR DESCRIPTION
**Pull request by billyvg**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- Added a button in the header to fetch user's current location using browser's geolocation API and set as next location to crawl

### CODE REVIEW

**Comment by billyvg** [comment]
Modified #1020 a bit, but added explicit button to set a new location

**Comment by Rohmin** [comment]
Will this also stop the current scan and start a new scan with the given location?

**Comment by ellisio** [comment]
@Rohmin looks like it does. He calls `/next_loc`.

**Comment by Rohmin** [comment]
Just tested, doesn't scan after moving to new location

**Comment by billyvg** [comment]
It scans at the next location after the current scan ends.

**Comment by talentedmrripley** [comment]
This appears to be a duplicate of #725.  That works without needing a button as well.

**Comment by MonkeyLeeT** [comment]
Please send in a new PR with exactly the change you want, considering #725 .

**Pull request closed without merging**
