### PR TITLE
Nicer error if invalid IP/port combination is given (See #1877)

### PR DESCRIPTION
**Pull request by fust**
## Description
Added check before binding to any addresses to see if they are valid in the current context

## Motivation and Context
Solves users entering invalid IP addresses to bind to getting exceptions printed in their console.
A lot of users don't have the technical know-how to understand the exceptions, better error handling prevents a lot of unneeded issues.
See #1877

## How Has This Been Tested?
Using some invalid IP addresses

## Types of changes
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Shouldn't Flask's default error message be enough? Why do the needless?

**Comment by fust** [comment]
It should, and to developers it probably is, however as seen in the referenced ticket it's not clear to users without the technical know-how. If we can display nice error messages describing exactly what's wrong and that helps to cut down on issues I think it's something we should want.

**Comment by MonkeyLeeT** [comment]
Again it seems weird to do binding twice only for the sake of better notification to average user. Average user will soon be able to use front-end directly (supposedly), so can we just trust Flask's default message for now?

**Comment by fust** [comment]
Agreed it's a bit weird, couldn't whip up a better solution though.
If the average user can set all this data through the frontend so we can do even better error reporting (or even better, -prevention) that would be the preferred solution and Flask's default message is enough for now.
Closing this PR.

**Pull request closed without merging**
