### PR TITLE
Update despawn time every second

### PR DESCRIPTION
**Pull request by foodforarabbit**
This pull request includes a
- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- added timestamp and class to label for pokemon timer (disappears at)
- added jquery + function to calculate time difference and update label

Notes:

- not too familiar with flask so I just wrote the js right on the page. Please feel free to refactor it as necessary.
- jQuery is probably overkill for what this does.
- haven't been able to test it "for real" because I'm unable to get any data. Should work though.

If this is related to an existing ticket, include a link to it as well.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/61

### CODE REVIEW

**Comment by nborrmann** [comment]
Whats the point of 
`if (true) {...} else {...}`
?

**Comment by foodforarabbit** [comment]
I was thinking it'd be useful in the future if you want to toggle between
time remaining and time of despawn. The second block sets the label to time
of despawn, which is mostly static. Currently there is no point and it can
be removed.

**Comment by favll** [comment]
This could be detrimental to performance if the map is accessed via smartphone and the project is running with a large step size (e.g. 10) and is displaying a lot of Pokémon.

**Comment by foodforarabbit** [comment]
Yea thats true. Ideally we should default to showing the static "disappears
at" number, and then we have a toggle somewhere that starts the setInterval
when its checked, and clears it when it gets unchecked. I'm not too
familiar with flask though so if someone could set up the js skeleton then
I can go in and start adding stuff but as you can see, I have it all in an
script tag at the top which doesn't feel right.

**Comment by AHAAAAAAA** [comment]
I agree with foodforarabbit, that's the cleaner more efficient solution (you only care about the pokemon you're hunting, not every single pidgey in the map).

**Pull request closed without merging**
