### PR TITLE
Added pokemon artwork

### PR DESCRIPTION
**Pull request by POPSuL**
Like that

image

### CODE REVIEW

**Comment by mkody** [comment]
Just a bit unrelated, but I wonder if it's possible to do the same with Pokéstops.

**Comment by MikeDX** [comment]
interesting, I wonder where the pokestops get their image url from - assuming it isnt covered in the pgo/api we use already and just isn't plugged in

**Comment by POPSuL** [comment]
@mkody pokestops? You're sure? Meybe gyms?
If you talking about gyms - maybe, but it possible if anyone implements getting the list of the gym's pokemons

**Comment by mkody** [comment]
@POPSuL Yes, I was talking about Pokéstops, having the picture of the place and maybe the name (but yeah, gyms too).

**Comment by medghaim** [comment]
We had this a while ago, but we ended up getting rid of it. It is my opinion that that's overkill. We have their name, their icon, and a link linking them to their pokedex entry.

**Comment by hgentry** [comment]
If you don't want it on by default, how about give a flag we can pass to turn it on? I think it's cute. :D

**Pull request closed without merging**
