### PR TITLE
added indexes for faster searching of the database

### PR DESCRIPTION
**Pull request by polygamma**
## Description

I added indexes to some of the columns in the tables of the database.

## Motivation and Context

Many people want to use the data they have crawled with the PokemonGo-Map to search for specific spawnpoints etc. After letting the PokemonGo-Map run for days, searching through the data gets really, really slow. Adding indexes to the columns, which are used for scraping the most, has changed this drastically. You can read more about it, for example, here: http://stackoverflow.com/a/1130

## How Has This Been Tested?

- Checked it with 'old' databases and can confirm that nothing bricks.
- Checked it also with 'new' (empty) databases and can confirm that the indexes are being added.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

If the database has already been created and is not empty, this commit changes nothing.
It bricks nothing, but also doesn't add anything.
But if one starts with a new, clean database, the indexes are being added.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by zeryl** [comment]
May also want to do an index on lat/lon in the tables.  A combined index since the searches do a window (lat > xxx lon > yyyy).

**Comment by polygamma** [comment]
Good idea @zeryl ! Added it.

**Comment by marauder37** [comment]
I have confirmed that the pokemon_latitude_longitude index is being hit for the raw_data query with mysql so I'm +1 on this

**Comment by marauder37** [comment]
+1 from e-wold

**Pull request merged**
