### PR TITLE
added google login

### PR DESCRIPTION
**Pull request by Mila432**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- added google login + rpc flag
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by sykhro** [comment]
This isn't related to #24 , is it?

**Comment by Mila432** [comment]
@sykhro i dont see #24 in your code yet

**Comment by JZ6** [comment]
Lets look at both implmentations

**Comment by JZ6** [comment]
also mila use this https://discord.gg/YAF5w

**Comment by Mila432** [comment]
mine is following the path a normal user would do , the other one uses pre-made modules 
people call mine ugly because scraping + html .. others are saying old school rocks

**Comment by MonkeyLeeT** [comment]
Maybe you wanna refactor the code for those indentation diffs?

**Comment by Mila432** [comment]
@MonkeyLeeT the format is messed up , somebody did tabs -> spaces , mine reverted this :c

**Comment by mpah** [comment]
just saw it, feel free to use this instead of mine if its better

**Comment by JZ6** [comment]
mpah thanks for understand bud

**Comment by mpah** [comment]
no problem, I'm just looking to help out where I can, you guys do the real work :)

**Comment by AHAAAAAAA** [comment]
This looks great! Thanks to you both mpah and Mila432! Before we merge, can we sort out the tab issues?

**Comment by Mila432** [comment]
@AHAAAAAAA sorry I am using notepad can somebody filter it with regex ?

**Comment by Mila432** [comment]
@AHAAAAAAA solved

**Comment by AHAAAAAAA** [comment]
Trying to merge. When I run this build I get this error:

TypeError: <pokemon_pb2.RequestEnvelop object at 0x1039746e0> has type <class 'pokemon_pb2.RequestEnvelop'>, but expected one of: (<type 'str'>, <type 'unicode'>)

**Comment by DerScreever** [comment]
Please merge #24 instead of this.
On #24 the google login is much easier and cleaner.

**Pull request closed without merging**
