### PR TITLE
Fix header misaligned

### PR DESCRIPTION
**Pull request by jpagano**
## Description
Remove line-height from header

## Motivation and Context
Fix header when the window size is less than 980px

## How Has This Been Tested?
Tested with the latest versions of Chrome, Firefox, Opera in OSX El Capitan

## Screenshots (if appropriate):
Before:
pokemongo-map-header-before

After:
pokemongo-map-header-after

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MRokas** [comment]
Please exclude .min files from commit next time.

**Comment by AHAAAAAAA** [comment]
Works for me, just remove min files from commit and I'll merge

**Comment by AHAAAAAAA** [comment]
rebase

**Comment by DJScias** [comment]
@AHAAAAAAA Just FYI.. If I recall right github allows you to rebase automatically on merge of PR's. Or is this not the case in this repository?

Kind regards,
DJScias

**Comment by MonkeyLeeT** [comment]
@jpagano please rebase.

**Comment by chuyskywalker** [comment]
lgtm

**Pull request merged**
