### PR TITLE
Location can be changed from browser via click

### PR DESCRIPTION
**Pull request by POPSuL**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added support for "click on map to set new location"

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
+1 from me, works well and consistent with code style!

**Comment by volksport** [comment]
Q: does this work on mobile?

**Comment by POPSuL** [comment]
@volksport yes!

**Comment by volksport** [comment]
So I appreciate the functionality -- but you do lose the ability to zoom with double clicks. Pros/Cons...

**Comment by goudacoin** [comment]
do i have to download and reinstall or is their a quicker way to update my current dev install?

**Comment by andrewda** [comment]
Great addition and works well!

**Comment by benemorius** [comment]
> do i have to download and reinstall or is their a quicker way to update my current dev install?

`git fetch origin pull/1111/head:clickmove && git merge clickmove && git branch -d clickmove`

**Comment by POPSuL** [comment]
@volksport 
> So I appreciate the functionality -- but you do lose the ability to zoom with double clicks. Pros/Cons...

I fixed it! :wink:

**Comment by buddyfavors** [comment]
@POPSuL What about mobile? Seemed it doesn't respond to the click event, I have another branch for geo navigation so at least I have that.

**Comment by POPSuL** [comment]
@buddyfavors on my mobile chrome map works properly. On single click - set location, on double click - zoom in

**Comment by buddyfavors** [comment]
@POPSuL I think the file might of been cached on my mobile, it's working now!

**Comment by MonkeyLeeT** [comment]
Tested and working as expected. Awesome addition.

**Comment by MonkeyLeeT** [comment]
Hey @POPSuL, as we discussed, we wonder if you could make such function disabled by default until we get a better polished frontend. Or make it a drag-drop style of re-centering. People finds that blind clicking and re-locating is a bit inconvenient.

**Comment by MonkeyLeeT** [comment]
For the convenience of other developer/user, this change is reverted.

You're welcome to PR another one taking suggestions above.

**Comment by POPSuL** [comment]
@MonkeyLeeT I'll change behavior from click to dnd

**Comment by goudacoin** [comment]
that explains why didn't work for me. i had just updated lol

**Comment by goudacoin** [comment]
is there a script to have it search multiple locations?

**Pull request merged**
