### PR TITLE
Enforce password length limit

### PR DESCRIPTION
**Pull request by Nyubis**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made
- The undocumented maximum password length is now applied. This should fix the issues that some people had while logging in. Previously they would send a password that was too long and get a "wrong password" reply.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
This solution looks clean and cuts off passwords at 15 chars. I feel like adding some output along the lines of "trimming password" would be good.

**Comment by Nyubis** [comment]
I've added the output.

**Comment by AHAAAAAAA** [comment]
+1 from me

**Comment by marauder37** [comment]
+1 lgtm

**Pull request merged**
