### PR TITLE
Fix "cannot read property setMap of undefined"

### PR DESCRIPTION
**Pull request by parkershepherd**
## Description
Updated variable names, added comments, and added a null check to a bit of code that has been throwing errors for me

## Motivation and Context
I'm still not 100% sure what causes this to happen, as it is pretty infrequent, but when it does get thrown, it stops `updateMap` from being called as the `rawDataIsLoading` variable never gets reset to false. I tried to rename the variables as I understood them, and added a null check where the error was being thrown.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2003

## How Has This Been Tested?
Chrome/OSX, Firefox/OSX

Should just be a pretty harmless bugfix.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by BillyWM** [comment]
This fixes the symptom - accessing a property on a non-existent object - but hides the root cause. As you said, 

>I'm still not 100% sure what causes this to happen

**Comment by parkershepherd** [comment]
Agreed. I figured "some pokestops behave funny" might be better behavior than "app silently crashes in the console and stops updating" though. I could add in a console.warn perhaps?

**Comment by BillyWM** [comment]
I just think there's not a huge hurry to sweep this under the rug. It hasn't always been happening, to my recollection, so there was a bad change(s) somewhere that started this.

Can you think of anything that makes this more likely to happen? I'd like to spend some time in the debugger trying to catch this.

**Comment by parkershepherd** [comment]
I can pretty reliably trigger it on my machine by simply zooming out and waiting for a minute or two. (I had a scan size of 9+ I think). I would vote for pushing this (maybe with a console warning) so as to avoid the worse bug this is causing. Code wise, it just looks like the null check was missed. I haven't seen anything weird looking since using this fix myself

**Comment by parkershepherd** [comment]
I did just notice this: 
image though @BillyWM

**Comment by BillyWM** [comment]
Okay, can you add a console.warn so this isn't forgotten?

Re: the image, sorry I'm not sure what I'm looking at.

**Comment by parkershepherd** [comment]
@BillyWM It was a double pokestop. I added the warning. I know there were some existing bugs with pokestops, but the PR that fixed them got reverted.

This should be good to go for now though

**Comment by BillyWM** [comment]
Marker management is a bit more convoluted than I realize, so nevermind; under the current system, sprinkling those null checks around is necessary. It could use a refactor but you're not doing anything wrong, so my bad.

**Comment by parkershepherd** [comment]
Bug appears to be fixed with a previous commit

**Pull request closed without merging**
