### PR TITLE
Fixed lured pokemon issue

### LINKED ISSUE #1984: Pokestops are undefined and show weird informations
Since I git pulled the last develop commit, the Pokestops are really weird

Deleted the MySQL db, but still got this bug.

### PR DESCRIPTION
**Pull request by polyisobutylene**
## Description

processLuredPokemon in map.js did not account for if a given pokestop did not have any active lured pokemon, modified the if statement to add an initial test for if the pokestop had any active lured pokemon.

## Motivation and Context

This fixes #1984. When enabling the Lured Pokemon switch all pokestops would be overwritten with a pokemon marker. If that pokestop did not currently have any lured pokemon then it would be a null pokemon object overlayed on the pokestop. The marker was invisible but still active whenever the Lured Pokemon switch was on

## How Has This Been Tested?

Tested and working with active lured and non-lured pokestops.

## Screenshots (if appropriate):
There is an applicable screenshot in #1984 of the issue, here is a screenshot showing the fix with an active luring pokestop and its pokemon but other pokestops without lured pokemon remain intact:
fixluredpokestops

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

…ble pokemon object when the lured pokemon option was enabled

### CODE REVIEW

**Comment by invisiblek** [comment]
Definitely going to want this commit if/when we remove the toggle :)

**Comment by invisiblek** [comment]
rebase please

**Comment by invisiblek** [comment]
shipped with https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1995

unfortunately the merge it does shoves everything into one commit

**Comment by polyisobutylene** [comment]
yah the fix here wasn't 100% solid either #2033 seemed to correct the issue

**Pull request closed without merging**
