### PR TITLE
Created a config file using YAML

### PR DESCRIPTION
**Pull request by MelonSmasher**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- The `get_args` function looks for a config file at `conf/settings.yaml`. If it finds the file, a custom class converts the config to an object and that is returned and used exactly the same way as the `parse_args` object. If a config file is not found arguments are loaded from the command line.
- Added PyYAML 3.11 to the requirements.
- Added example settings file
- Updated gitignore to ignore `conf/settings.yaml`

### CODE REVIEW

**Comment by DerScreever** [comment]
@MelonSmasher 

you should change this:

ignore: None # [ 13, 16 ] # Pokenon to ignore
 +only: None # [ 150, 151 ] # The only pokemon that should be displayed

we are not unsing idead fot the ignore. we use the names instead like i know

**Comment by MelonSmasher** [comment]
My bad I'll fix the comments.

**Comment by DerScreever** [comment]
@MelonSmasher 
sorry to say that, but you need to update again. we now allow both id or name for the -i or -o field. See latest commit.

**Comment by MelonSmasher** [comment]
@DerScreever are you all set with your changes?

**Comment by DerScreever** [comment]
if you start now you do your work twice :D i will inform you ^^

**Comment by MelonSmasher** [comment]
Ok lol, I'm going to pull the latest commit to master when you are done and reimplement on a new branch. I tried to re-base this branch and messed the branch up beyond belief. So let me know and I'll close this pull and submit a new one.

**Comment by DerScreever** [comment]
okay

**Comment by MelonSmasher** [comment]
Have any changes been made?

**Comment by MelonSmasher** [comment]
Looks like a json config file is going to be used after the re-base. I'll close this then.

**Pull request closed without merging**
