### PR TITLE
Add --ignore.

### PR DESCRIPTION
**Pull request by rofrankel**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added support for --ignore flag.

If this is related to an existing ticket, include a link to it as well.

Useful to remove common, uninteresting Pokemon from the map and increase SNR.

### CODE REVIEW

**Comment by rofrankel** [comment]
My area is full of Pidgeys, which are fine for grinding XP but I'm not going out at 12:30 AM for them.  I *will* go out for a Tentacruel and a Wartortle a couple blocks apart, if I can even tell they're there amongst all the Pidgeys and Zubats.

**Comment by marauder37** [comment]
I don't want to merge this before #54 gets in, and I might ask you to rebase it after that, sorry

**Comment by JZ6** [comment]
great feature! I would love for this to be included, and like marauder said after #54 merges we will merge this

**Comment by rofrankel** [comment]
SGTM, happy to rebase.  Mind pinging this once #54 is in?

**Comment by JZ6** [comment]
one issue,could you make the param not required?

**Comment by rofrankel** [comment]
Done.   Looks like #54 got reverted for some reason, not sure what the deal is but still happy to wait and rebase if that's what makes sense.

**Comment by marauder37** [comment]
Nah looking at this one now with a view to accepting

**Comment by marauder37** [comment]
@rofrankel this is looking good, please add it to the table of command line arguments in README.md and say comma-separated (and no space separator).

**Comment by JZ6** [comment]
@rofrankel i second @marauder37 update the documentation please

**Comment by stanleykylee** [comment]
broke master for me. created issue #70

**Pull request merged**
