### PR TITLE
Added Favicon, Changed Title

### PR DESCRIPTION
**Pull request by xdtrammell**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Changed Title and Body To "Pokemon Go Map"
- Added a favicon
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by nakami** [comment]
how about the favicon pokemon.com uses? //assets.pokemon.com/static2/_ui/img/favicon.ico

**Comment by DerScreever** [comment]
minor change ^^ maybe use the favicon as @nakami told. ^^

**Comment by xdtrammell** [comment]
I changed the favicon.

**Comment by DerScreever** [comment]
nice, you did it really fast :+1:

**Comment by AHAAAAAAA** [comment]
+1

**Pull request merged**
