### PR TITLE
Various lure improvements

### PR DESCRIPTION
**Pull request by hgentry**
## Description

Some of the last few changes have broken some of the lure functionality. This repairs those issues. Namely, a Lure Pokemon toggle was added to provide more granular control over data and this setting is used to ensure that other settings don't break Lure Pokemon.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
#1745 ?

**Comment by hgentry** [comment]
I'll make some changes so we don't conflict

**Comment by MonkeyLeeT** [comment]
Or better if you guys decide on one to merge :)

**Comment by hgentry** [comment]
We're doing separate things with these. I'm adding a toggle to fix something that broke, they're fixing something else entirely. I'm fairly confident that with this last change we won't collide, except for possibly a single line. Not sure how forgiving git is.

**Comment by andrewda** [comment]
@hgentry It's not forgiving at all, heh. Which line are you talking about? I can add it to my PR.

**Comment by hgentry** [comment]
@MonkeyLeeT We've got our differences sorted out. If mine goes first, we're good to go.

**Comment by MonkeyLeeT** [comment]
OK, tested in new york, working well. +1.

**Comment by Chlodochar** [comment]
This PR is also uses an incorrect method to set a default value for `localStorage`. Please note that `localStorage.anything` always returns `undefined` or a string. It never returns a boolean. Using `localStorage.showPokemon || true` is therefore incorrect. Any `if (localStorage.showPokemon)` is also incorrect.

See #1694.

**Comment by BillyWM** [comment]
>Using localStorage.showPokemon || true is therefore incorrect. 

In Javascript, the || statement has fallthrough. This is a common practice to set a default value if the first thing has a "falsy" value (0, undefined, null, or the empty string "")

`x = localStorage.showPokemon || true`

where the showPokemon property is undefined this falls through and x gets "true"

--------------------------

Open your dev console (F12) and try this:

`obj = {}
x = obj.showPokemon || "I fell through"`

x gets "I fell through"

**Comment by Chlodochar** [comment]
@BillyWM Thanks for highlighting my point. The problem is indeed hard to spot. If `localStorage.showPokemon` is set to false, it is actually `'false'` (as string). So depending on whether it is set, it'll result in a string `'false'` or a boolean value `false`. The string `'false'` is actually a truthful value, so any `if` or `||` or `&&` that is used with this value will interpret this value as `true`.

Only the `localStorage.showPokespots === 'true'` were somewhat correct, but only if the default value of `localStorage.showPokestops` is false. It is incorrect for `showPokemons` because its default value seems to be `true`. So, due to this error, in some cases `showPokemon` is intepreted as being true and sometimes as being false when the option was not set.

**Comment by BillyWM** [comment]
@Chlodochar: Nah, I was mistakenly only thinking about the case of undefined. I deleted my post for a reason, thanks.

**Pull request merged**
