### PR TITLE
Route /raw_data (output in this format: { gyms: {}, pokemons: {}, pok…

### PR DESCRIPTION
**Pull request by vanchagreen**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

* Added a new route to return JSON for gyms, pokemans, and pokestops.

If this is related to an existing ticket, include a link to it as well:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/510

### CODE REVIEW

**Comment by Axelshark** [comment]
Route /raw_data (output in this format: { gyms: {}, pokemons: {}, pok…

**Comment by AHAAAAAAA** [comment]
+1 from me, would merge.

**Comment by MonkeyLeeT** [comment]
Tested and working. Could merge.

**Comment by favll** [comment]
This queries all three database tables even though only one is needed (queries pokemons/pokestops/gyms).

**Comment by vanchagreen** [comment]
You're completely right @favll. I'm going to be away from computer for an hour, but then I can fix it. My bad.

**Comment by NgJason** [comment]
@vanchagreen To speed up the process I, removed Pokestops and gyms for you. https://github.com/AHAAAAAAA/PokemonGo-Map/pull/637

**Comment by vanchagreen** [comment]
I think we should go with @mikeporterdev's https://github.com/AHAAAAAAA/PokemonGo-Map/pull/628, which fixes my bug (and adds extra stuff too).

**Comment by SniperRus** [comment]
@NgJason why removed Gyms? i guest it would be helpful to export gyms coord to external maps and use it somethere else?

**Comment by NgJason** [comment]
@SniperRus It was based off of this comment: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/600#issuecomment-234032978

**Comment by vanchagreen** [comment]
@NgJason, That comment was referring to the fact that every time the `get_raw_data` function is called it would hit all three database tables (Pokemon, Pokestops and Gyms). 

But it was called on lines like [this](https://github.com/AHAAAAAAA/PokemonGo-Map/pull/600/files#diff-8a698d69ff9c611937d2cb2465f5fc2dR43), where we only needed to hit the one table. 

We did want a `raw_data` route that would return all the data, but I wrote it in an inefficient way.

**Pull request merged**
