### PR TITLE
Added 3 custom map styles that remove labels ( #1573 )

### PR DESCRIPTION
**Pull request by Skullmonkey**
## Description
I took the 3 custom maps and removed all the labels and icons for a less cluttered look

## Motivation and Context
The map looked cluttered and the street names, icons, and other labels were distracting to me.

## How Has This Been Tested?
Ran on local build and tested with Chrome and Firefox.

## Screenshots (if appropriate):
http://imgur.com/ewnd0zN
http://imgur.com/xoTtAuL
http://imgur.com/MPqHbLz

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by medghaim** [comment]
I _can't_ be the only one to find street info useful :(

**Comment by marauder37** [comment]
@MonkeyLeeT PRs need code review from 3 contributors before merging

**Comment by MonkeyLeeT** [comment]
@marauder37 my bad, always remembered it was two. Will stick to three from now on.

**Comment by JZ6** [comment]
bad idea, street labels are useful

**Pull request merged**
