### PR TITLE
Overall area marker

### PR DESCRIPTION
**Pull request by hazanjon**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

As referred to / requested in #1338, this feature adds an overlay that shows the current overall search area for any active workers (Last 15 mins) 

This should make it easier for users with multiple workers to check and align their search areas

The option can be toggled independently to the actual scanned areas

worker area
worker area in progress

### CODE REVIEW

**Comment by hazanjon** [comment]
@jangrewe @HinoReo Was this the sort of thing you two were looking for?

**Comment by HinoReo** [comment]
@hazanjon Yes, that's exactly what I meant! :dart:

**Comment by jangrewe** [comment]
@hazanjon pretty much, yes! =)

could it be inverted, though, like a real fog-of-war? so that the markers on the map don't get an overlay (or rather "underlay") and the map style doesn't interfere with it?

**Comment by EnigmaIsWorking** [comment]
Is it possible to have Multithreading for checking Pokemons in each area? If I want to observe 30 kilometers, it takes to much time for refreshing.

Would be really happy that I can give him 5 Accounts and they are splitting the work (faster).... Like a sonar.

**Pull request closed without merging**
