### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by andrewda**

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
+1, tested and ready to merge as soon as landscape finishes.

**Comment by FrostTheFox** [comment]
@AHAAAAAAA haha, landscape, finishing?

**Comment by hgentry** [comment]
Yeah landscape died days ago

**Comment by andrewda** [comment]
@AHAAAAAAA @FrostTheFox @hgentry As landscape seems to be RIP, I'm gunna go ahead and merge this. Landscape should continue checking to see if there are issues, but I highly doubt the quality will decrease at all.

**Comment by Chlodochar** [comment]
@tkSimon See #2058

**Comment by Chlodochar** [comment]
For problems with landscape.io see https://github.com/landscapeio/landscape-issues/issues/240

**Comment by tkSimon** [comment]
@Chlodochar are you trying to say that this is being worked on? I noticed there was some travis-ci plugin  enabled which i presume checks code style , but without publishing a definitive guideline on github, will will keep submitting without following guide lines, and landscape will keep saying that it's not according to the guide lines.

What I'm trying to say is that without publishing guidelines - and making them easy to find (as opposed to being hidden in some landscape config file) - people won't be able to follow the guide line. All this presumes that there already is a guide line...

**Comment by Chlodochar** [comment]
I know. We're seeing what works. Landscape.io gives a nice interface for what is 'wrong' or 'could be better' and it'll mark a PR as 'failing' if it doesn't meet the requirements. The guidelines are unclear to me too (it uses less-strict configuration of pep8), so if things are ok for pep8, it'll be ok for landscape.io. Whatever the case, it'll be clear in the PR itself. ... or at least when Landscape.io works ;)

**Comment by tkSimon** [comment]
Tbh I was talking about js, not python :P
I know, the heavy work is done in python, but I've never touched anything python so far. I'd rather help on the js side. But I'm hopeful that there'l be guideline for that too. Sry for high-jacking this thread, btw.

**Comment by Chlodochar** [comment]
At the moment there is a jshint task in Grunt, but I'd like that to change to a more explicit full styleguide. eslint with standardjs seems like a good alternative. I spoke with @andrewda and we agreed on using standardjs. Haven't found a online service that checks PRs for JS styling that is as nice as Landscape.io though.

Since map.js is growing a lot, it's also time to split that up in modules. We probably need to use browserify or webpack for that, but haven't decided which one of the two to use yet. Do you have any suggestions on this?

**Comment by piplar** [comment]
hey, new github member here. 

version 1.0 has the 'infamous' example.py - what is used as a replacement in version 2.1?

**Comment by andrewda** [comment]
@pipler that's completely unrelated to this issue thread. Please use the Discord channel for help. 

The replacement for example.py is runserver.py.

**Comment by piplar** [comment]
Thanks

**Comment by piplar** [comment]
I'm not sure how to find the discord channel..

**Comment by piplar** [comment]
Andrewda, This is my first time on here and I'm trying to work on something and seem to be stuck. Could you direct me or help me at all? 

thank you

**Pull request merged**
