### PR TITLE
Italian Localization

### PR DESCRIPTION
**Pull request by hilycker**
fixed #2390 

This time I actually got the original en file. Also saw it was encoded with UTF-8. maybe that's why mine wasn't good.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
These are the Pokemon names in English. Why do we need this?

**Comment by callmebackdraft** [comment]
@AHAAAAAAA adding this also enables more project wide localization, for instance my PR #2667 which moves the mapstyle selector and implements localization in a custom select bar.

If people/contributors would somehow change the menu options to different languages through localization files it would not be able to show pokemon pokemon names if the pokemon file isnt available for that specific language.

**Comment by andrewda** [comment]
@callmebackdraft or default to English if it's not available :>

Each localization file is ~12kb, sometimes more depending on the language, but that adds up quickly if we were to add a bunch that are literally the same as the English localization.

**Comment by hilycker** [comment]
@AHAAAAAAA  quoting myself from #2390 "[...]It's just to let you know as soon you'll decide to make other strings localized, you'll have italian translations too :)"

and It's to have something to start, to let other people know there's also an ongoing italian localization .

on another repo, and one widely known, weeks without the italian localization passed, as soon as i started it, the following day other 2 translators joined :)

and of course what @callmebackdraft said

**Comment by tim95030** [comment]
This is in the old language format. I switched to using an i8ln function that does word lookup. As such all you need to do is create a dictionary of any words you want translated and if it isn't found it resorts to english. Meaning don't translate Mew -> Mew etc. just translate actual things. For format it is a simple json file:

```
{
  "english word": "translated word",
  "another english word": "another translated word"
}
```

I did this for one to limit space, and for 2 to be able to separate translation from data. There is no more pokemon.{lang}.json just {lang}.json in locales. Also don't bother to minify as a grunt task does this. You can copy one of the other files for reference. But my above example is exactly how it works. It just maps words to words. It can also do phrases as well, but currently only rarity, types, and names are being translated.

**Comment by AHAAAAAAA** [comment]
Update this to the new localization format and I'll merge

**Comment by hilycker** [comment]
@tim95030 @AHAAAAAAA 

will do, thanks

**Pull request closed without merging**
