### PR TITLE
stats.js: relative file paths

### PR DESCRIPTION
**Pull request by florian-184-de**
## Description
Fixes a problem with broken pictures if the root path of PoGo-Map isn't example.com but example.com/pogomap/

* Issue #2485 

## How Has This Been Tested?
* nginx proxy_pass: https://example.com/pogomap/
* http://example.com:5000/

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by invisiblek** [comment]
please update static/js/stats.js and run grunt to automatically generate stats.js

**Comment by chuyskywalker** [comment]
`static/dist/js/stats.js` must not be this PR commits.

**Comment by andrewda** [comment]
Remove `static/dist/js/stats.js` and then :+1:

**Comment by tkSimon** [comment]
Fixed in #2770

**Pull request closed without merging**
