### PR TITLE
#1515 rebase

### PR DESCRIPTION
**Pull request by JZ6**
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1515

All credits to yotamN

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Yay the nav bar is higher! +1.

**Comment by Chlodochar** [comment]
:+1: Looks good to me. Merge ASAP? before something else CSS-like is merged.

**Comment by Chlodochar** [comment]
Alright merged.

**Comment by Algent** [comment]
Did this break the scroll bar for the  options menu or it's unrelated ?

**Comment by Chlodochar** [comment]
@Algent Hmm, you're right. Reverting this commit locally fixes the scrollbar. I'm not that great with css though. @yotamN @JZ6 could you give some insight?

**Comment by Chlodochar** [comment]
#2082 reverts this change. One of the collaborators please upvote or merge.

**Pull request merged**
