### PR TITLE
Changed gym icons into shields/badges

### PR DESCRIPTION
**Pull request by MikeDuister**
## Description
Changed gym icons

## Motivation and Context
The old variety of gym icons looked 'out of style'

## How Has This Been Tested?
map fully tested with icon, see #1671 

## Screenshots (if appropriate):
screenshot_106

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Chlodochar** [comment]
Looks good to me. They are more outstanding than before, which is good.

**Comment by MonkeyLeeT** [comment]
One quick concern, are we free to edit those copyrighted(possibly) icons?

**Comment by chuyskywalker** [comment]
Shouldn't this PR be opened against `develop`?

**Comment by Chlodochar** [comment]
@chuyskywalker Indeed, it doesn't merge against develop. Probably needs a new PR for that :(.

**Comment by callmebackdraft** [comment]
I believe these icons are created by @MikeDuister himself see issue #1671.
However Mike does have to use a new PR to merge against Develop

**Comment by MonkeyLeeT** [comment]
Please send in a new PR.

**Pull request closed without merging**
