### PR TITLE
grammar; added acute accent over 'e's

### PR DESCRIPTION
**Pull request by frozenpandaman**
small grammatical fixes

Pokemon → Pokémon
Pokestop → Pokéstop

### CODE REVIEW

**Comment by JZ6** [comment]
lol

**Comment by frozenpandaman** [comment]
:B

**Comment by JZ6** [comment]
rebase please

**Comment by frozenpandaman** [comment]
@JZ6 alright, think i did it 😅

**Comment by frozenpandaman** [comment]
@sykhro Alright then.

**Pull request closed without merging**
