### PR TITLE
fix script failing after 30 min or so problem

### PR DESCRIPTION
**Pull request by foodforarabbit**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- need to set TimeTillHiddenMs even if lower or else seen[hash] will only increase until it can't anymore
- hide "expired" pokemon from front end
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by medghaim** [comment]
The entire project is being rewritten, `example.py` won't exist soon. Check out the rewrite-branch, as per the readme.

**Comment by bluefi** [comment]
Isn't there still a problem at this lines?:

```
                    if hash not in seen.keys() or (seen[hash].TimeTillHiddenMs <= wild.TimeTillHiddenMs):
                        visible.append(wild)    
                    seen[hash] = wild.TimeTillHiddenMs
```

Never wrote a line python, but seen[hash].TimeTillHiddenMs does not exist if you set seen[hash] to wild.TimeTillHiddenMs, right? Either set seen[hash] = wild;  or compare seen[hash] <= wild.TimeTIllHiddenMs

**Comment by Josephvb10** [comment]
Even with the fixes listed here, the problem is still present for me with auto refresh on. After 30 minutes or so Pokémon stop appearing in the map.

**Comment by Herwi** [comment]
Same here. Still after 30 minutes or so Pokémon stop appearing in the map.

**Comment by KingScooty** [comment]
This issue is still present.

**Pull request merged**
