### PR TITLE
Lock sqlite db writes

### PR DESCRIPTION
**Pull request by adamhwang**
## Description

Lock sqlite db writes to prevent "OperationalError: database is locked" error when running multiple threads.  (Will not prevent same error caused when running multiple servers.)

## Motivation and Context

With threading hopefully soon-to-be fixed, this PR will help alleviate some of the multithreading issues sqlite users will face.

## How Has This Been Tested?

Tested code against #1910 branch with 20 threads and sqlite.

## Screenshots (if appropriate):
Before after a few seconds "database is locked" happens on almost every single db write:
image

After, "database is locked" only happens during db reads (/raw_data):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by slonce** [comment]
Not working. I play in 3 instanse in 30 thread and "Database is locked"

**Comment by adamhwang** [comment]
Like I said, this will do nothing for multiple instances.  Only for multiple threads within a single instance.

**Comment by slonce** [comment]
aaa ok thanks. thats sorry. But for multiple instanse that connected for 1 db have fix?!)

**Comment by Pedrock** [comment]
@slonce You should be using MySQL.

**Comment by marauder37** [comment]
1. have you tested this on Windows? It's an alternate universe there, where locking doesn't work reliably
2. don't use acquire/release, just write `with lock:`

**Comment by adamhwang** [comment]
yes, only tested with Windows. somebody will need to check Linux compatability. 

"with lock:" will require duplicating line 332 in an if statement. I'm fine with it either way if there's something wrong with acquire/release

**Comment by wcastello** [comment]
Wouldn't this just introduce a new lock? There's already one in search_thread guarding the entry to parse_map().

**Comment by adamhwang** [comment]
@wcastello you're right.  closing PR

**Pull request closed without merging**
