### PR TITLE
Fixes scan location for high -st

### LINKED ISSUE #2187: Scan locations far from the center are increasingly off
Close to the center the circles of scanned locations align and cover all the ground. But further outside (I tried it with -st 100 and waited 20 minutes) you will get this picture:

screenshot from 2016-07-26 14-42-44

This is likely a small error that gets added again and again.

### PR DESCRIPTION
**Pull request by reyqn**
## Description

I changed how the latitude longitude are calculated. It should be more accurate now.
I also used more accurate values for some constants.

## Motivation and Context

At high -st, longitude was becoming very inaccurate. This change will help with that.
This should fix #2187 

## How Has This Been Tested?

I tested pretty quickly where I live (45° lat), next to the equator (0° lat) and north pole (90° lat). Seems to work pretty well.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by medghaim** [comment]
Far too many magic numbers for my liking. I have the fix, just testing it in all quadrants of the earth.

**Comment by reyqn** [comment]
@medghaim https://gis.stackexchange.com/questions/75528/length-of-a-degree-where-do-the-terms-in-this-formula-come-from#75535

**Comment by reyqn** [comment]
But I guess meters_per_degree_lng should be recalculated every 100 steps or so (if you want to scan huge zones)

**Comment by reyqn** [comment]
Seems to be more accurate than #2382

**Comment by medghaim** [comment]
Yeah, I'm not sure what the hell happened, that was the edge of `120` - and a few other tests too, but that GIS page you linked is 100% accurate.

I'm still not a fan of the magic numbers though, they need their own to be their own variables with comments. 

Since GIS capabilities are becoming more and more required evidently, I believe we should just write a GIS module.

**Comment by reyqn** [comment]
Yeah I have no idea why yours is not accurate. It definitely looks better. I made 

I am not really proficient in python, so I have no idea how you would like to implement this GIS module.

**Comment by marauder37** [comment]
Had a look at this but it needs rebasing

**Comment by AHAAAAAAA** [comment]
Is this still necessary?

**Comment by reyqn** [comment]
@AHAAAAAAA It could if people still want (and are able) to scan huge areas. It's still not perfect though. Finding the inaccuracies in #2382 would probably be better.

**Pull request closed without merging**
