### PR TITLE
Added "Notify of all Pokémon"

### PR DESCRIPTION
**Pull request by sumihiro**
Added an option to notify when found all of Pokemon (excepts "Hide common Pokémon").

### CODE REVIEW

**Comment by sp90** [comment]
@sumihiro maybe even add support for browser notifications

https://developer.mozilla.org/en/docs/Web/API/notification

**Comment by sumihiro** [comment]
@sp90 browser notification is already supported.

**Comment by jjbott** [comment]
Just a thought... How about the switch changes the "notify" list from a whitelist to a blacklist? Then you get your functionality with an empty notify list, plus users that care about all but a few can more easily exclude those few from notifications

**Comment by sumihiro** [comment]
I want to get notification of Pokemon which I don't have it.
I add my Pokemon to "Hide common Pokemon", I will get notification of other Pokemon.

**Comment by michaellindahl** [comment]
Related to #1555

**Pull request closed without merging**
