### PR TITLE
Add apple touch icons and home screen optimizations

### PR DESCRIPTION
**Pull request by rnarian**
This pull request includes a

- [x] New feature

The following changes were made

- Add apple touch icons
- Add home screen app optimizations (remove title/nav bar to show fullscreen map)

|||
|---|---|

Related: #394

### CODE REVIEW

**Comment by sykhro** [comment]
Please make a subfolder for the favicons, the static directory is getting conusing

**Comment by rnarian** [comment]
Give me a sec

**Comment by rnarian** [comment]
✅  done

**Comment by CarlTaylor1989** [comment]
+1

**Comment by frdmn** [comment]
+1

**Comment by sykhro** [comment]
Passed, merging

**Pull request merged**
