### PR TITLE
Add a way to add all non-excluded Pokemon to the notify list.

### PR DESCRIPTION
**Pull request by JackDoan**
## Description

- Added two buttons in the sidebar, Add All and Remove All
- Add All automatically adds all non-excluded Pokemon to the notify list
- This can sometimes be a lot of Pokemon, so Remove All clears the notify list
- 'notifyAboutPokemon(id)' was updated to silently ignore requests to notify about excluded Pokemon

## Motivation and Context

In suburban areas like my own, anything that isn't a Pidgey or Rattata or the like is notable. These buttons make it quick and easy to set up notifications for when something interesting spawns.

Issues: 
#2731 
#1961
#1609
#1555 
#1415

Also kinda helps with:
#1429
#1228

## How Has This Been Tested?

This works correctly in Chrome 50 on Arch Linux. I haven't checked anywhere else yet.
The server was running in Docker, but all changes are client side.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JackDoan** [comment]
I apologize for my messy commits. If there's a way to clean them up, I'd love to know.

**Comment by invisiblek** [comment]
I thought about implementing this awhile back, my thought was to have a switch next to the "Hide Pokemon" label that would enable/disable notifications on all. If you enabled that switch, it'd grey out and disable the box for adding/removing these and just notify on all pokemon (of course, not notifying on ignored ones). Seems it might be better UX since if you added a new one to the ignore list, you wouldn't have to search for it and remove it from the notify list.

**Comment by JackDoan** [comment]
@invisiblek The only issue I see there is what if you want to display a Pokemon, but not notify about it? I think Eevee is a pretty good example of this.

What if instead adding something to exclude also removed it from notify automatically?

**Comment by AHAAAAAAA** [comment]
This has been brought up a few times, but implementation always seemed confusing. We essentially want a Notify selector that's 'All except hidden'. It solves 95% of the issue.

**Pull request closed without merging**
