### PR TITLE
Fix for pokestops: Jsonify needs correct formatting correct. Document…

### PR DESCRIPTION
**Pull request by rushingfitness**
This pull request includes a

- [X] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Bring back correct formatting for jsonify on pokestops model request

If this is related to an existing ticket, include a link to it as well.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/774

### CODE REVIEW

**Comment by medghaim** [comment]
Testing now.

**Comment by benemorius** [comment]
Works for me.

**Comment by medghaim** [comment]
Same, but @sykhro is working on a new fix altogether, with a better approach to raw_data. So we might just revert the commit that broke `/pokestops`

**Comment by Zsub** [comment]
👍

**Comment by rushingfitness** [comment]
Damn, that means I still have commited code on this project! Haha. But I did notice at a glance that in raw_data right now, it's not calling `dicts()`. So I'd just make sure the new version has that as well.

**Comment by Zsub** [comment]
@medghaim why not merge this in the meantime? :)

**Comment by rushingfitness** [comment]
^^ I like this guy haha

**Comment by evrardjp** [comment]
The commit message and title is aweful but it seems to do the job.
I'm not familiar with the data structure, so I don't know if .dicts() should be added or not.

Anyway works for me -> 👍

**Pull request closed without merging**
