### PR TITLE
Added custom config file argument

### PR DESCRIPTION
**Pull request by Pho3nixHun**
Added new argument to be able to supply custom config files.

## Description
Added -cf and --config-file argument to supply custom config files.

## Motivation and Context
If you would like to run more searchers, it is handy to provide a custom config file for each.

## How Has This Been Tested?
Supplied a config file by this argument and checked if it's used by the server. (It does)

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by invisiblek** [comment]
Nice find, I was actually thinking about writing this today.

One observation I did have was that the way this is, the user-supplied config file works as a supplement to the standard config/config.ini. In my opinion it should replace it wholesale. Thoughts?

I think this could be achieved by removing line 34, the param in line 35, and setting os.path.join(os.path.dirname(__file__), '../config/config.ini') as the default for this new config option.

**Comment by Pho3nixHun** [comment]
I like your solution too it's way clearer, but this way if you modify only certain values - eg. location - extending a default config file is much more efficient :)

**Comment by invisiblek** [comment]
Right, but that can get pretty confusing. Which file is taking precedence? If you've specified a file, why is it still reading the default (I'm not sure of any other program that does this)

**Comment by chuyskywalker** [comment]
Do not have configs merge, that's super confusing.

**Comment by AHAAAAAAA** [comment]
not merging against master. pr to dev

**Pull request closed without merging**
