### PR TITLE
2x icons

### PR DESCRIPTION
**Pull request by davidbalas123**
First time using GitHub so I hope I did it fine.

This pull request includes a

- new icons 2x

The following changes were made

- added a folder with all the new icons 2x - static/icons-2x
[icons-2x.zip](https://github.com/AHAAAAAAA/PokemonGo-Map/files/369143/icons-2x.zip)

### CODE REVIEW

**Comment by haagiboy88** [comment]
Reopened for visibility. These icons can be resized (as needed)  and merged with the new iconfixes?

**Comment by marauder37** [comment]
@haagiboy88 I'm not sure what this is reopened for, the icons were merged in another PR and then removed later. The best approach to resizing icons is probably CSS.

**Comment by haagiboy88** [comment]
It was reopened due to more people wanting the pixelated style back. I reopened this for the visibility so someone can implement them and add css compatibility for resizing. I am not a developer btw.

**Comment by davidbalas123** [comment]
@haagiboy88 I accidently opened this incorrectly, there is another one which is already merged, I also cannot understand why this is reopened. not necessary

**Pull request closed without merging**
