### PR TITLE
Added Pokelyzer Integration

### PR DESCRIPTION
**Pull request by Brideau**
## Description

I created [Pokelyzer](https://github.com/Brideau/pokelyzer), a database schema that supports doing advanced analytics on historical Pokemon Go data using GIS software (e.g. ArcGIS/QGIS) and BI tools like Tableau or PowerBI. You might have come across it in the Silph Road subreddit post: [Finding Hotpots for Locally Rare Pokemon Using Tableau](https://www.reddit.com/r/TheSilphRoad/comments/4uvwme/finding_hotpots_for_locally_rare_pokemon_using/). This pull request adds a direct integration from PokemonGo-Map, which currently everyone is using a source of data for Pokelyzer.

## Motivation and Context

Pokelyzer different from your built-in database in that it's schema is built specifically for doing analytics, and it uses spatial datatypes and indexes. It can happily run along side yours without any conflicts because it just forks the data.

Initially I just did a hack with PokemonGo-Map and shared my results for others looking to do the same, but there's been a huge interest in adopting this so I wanted to do a proper integration.

I tried my best with this pull request to keep as much of my code out of your way as I could, and made it so that people not interested in using Pokelyzer could run your server without even knowing it exists. 

## How Has This Been Tested?

I tried this on my local machine (MacBook pro) as well as in an AWS EC2 instance. I also had some people test my fork and so far everything has gone smoothly but putting a call out on Reddit (https://www.reddit.com/r/pokemongodev/comments/4vd91c/can_i_get_a_brave_soul_to_help_me_test_this/) and contacting people directly.

My only concern is how to automate the install of `python-psycopg2` and `libpq-dev` if a user's system requires them. In Ubuntu, that is done this way, but I don't know how to do this programmatically: 
```
    sudo apt-get install python-psycopg2
    sudo apt-get install libpq-dev
```
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

I just added a new file for the Pokelyzer function, put a function call below where your logging script is in the parse_map() function and added extra optional parameters.

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

Not necessarily, unless you want to advertise the integration. Otherwise I can just change the documentation in my repo: https://github.com/Brideau/pokelyzer

- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by chuyskywalker** [comment]
I feel like this falls under the banner of "implement through webhooks" now that we have that.

**Comment by Brideau** [comment]
@chuyskywalker You have webhooks now? Where do I find the docs on how to use them? I didn't spot anything in your new wiki.

**Comment by Brideau** [comment]
@chuyskywalker Nevermind - just found them in the old wiki. Giving it a look now.

**Comment by Brideau** [comment]
@andrewda @chuyskywalker Just added an example Node implementation to the docs: https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Using-Webhooks

**Comment by Brideau** [comment]
I semi-successfully implemented this with the webhook, I just need to do a separate pull request as the webhook data doesn't give all the fields that I require. Will do that shortly.

**Comment by chuyskywalker** [comment]
Awesome, thanks!

**Pull request closed without merging**
