### PR TITLE
develop: added heroku support using Procfile

### PR DESCRIPTION
**Pull request by Chlodochar**
This adds minimal Heroku support. Documentation should go into the wiki once this is in master.

### Documentation

- Create an app on Heroku.
- Clone PokemonGo-Map on your PC:
```sh
$ git clone https://github.com/AHAAAAAAA/PokemonGo-Map
$ cd PokemonGo-Map
$ git checkout develop
```
- Copy `credentials.example.json` to `credentials.json` and edit its contents.
- Commit `credentials.json`
```sh
$ git add -f credentials.json
$ git commit -m "added credentials.json"
```
- Push PokemonGo-Map to Heroku:
```sh
$ git push https://git.heroku.com/yourapp.git develop:master
```
- On Heroku add the following environment variables: `USERNAME`, `PASSWORD`, `LOCATION` and `STEP_COUNT`.
- On Heroku start and open the app.

Optionally you can add your own parameters using the `EXTRA_ARGS` environment variable. For example you can use `-dp -dg -ar 60` for `EXTRA_ARGS` to get pokestops, gyms and auto-refresh.

### CODE REVIEW

**Comment by gsabran** [comment]
Nice PR :)

**Comment by Ayysir** [comment]
-ar 60 is in seconds or minutes?

**Comment by AHAAAAAAA** [comment]
Can you add this to the Wiki before we merge?

**Comment by gsabran** [comment]
-ar is in seconds, so -ar 60 is auto refresh once per minute

**Comment by Chlodochar** [comment]
I do not have permission to write to the wiki.

The steps are a bit more involved now that `credentials.json` isn't provided anymore. A good alternative is to have Google Map credentials passed as an environment variable or commandline argument, but that can be done later.

@gsabran If there is documentation on the different command-line arguments, then it makes sense to refer to that doc from the Heroku doc.

**Comment by DanielVolz** [comment]
Maybe I'm missing something, but where is the Procfile?

**Comment by SilverC** [comment]
@Chlodochar I think you should also add support for pulling in the command line arguments via config vars so that username and password don't have to be source controlled in the procfile

**Comment by Chlodochar** [comment]
@DanielVolz I guess you missed: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/682/files ?

@SilverC That's already possible with `EXTRA_ARGS` I think?

**Comment by punkstar** [comment]
Great work @Chlodochar.  I've tested this and it works fine for me.  I've opened #946 that takes this a step further and adds an `app.json` and a deploy button.

**Comment by MonkeyLeeT** [comment]
Document added for you. Great job guys.

**Pull request merged**
