### PR TITLE
Update pokemon.proto

### PR DESCRIPTION
**Pull request by eruliaf**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

I experimented with this code change and noticed significant improvements in my performance. 
It definitely also helped to change the semantics of some of the functions.

### CODE REVIEW

**Comment by mkody** [comment]
Please stop emptying the proto file.

**Comment by cmorbaab** [comment]
I told you guys

**Comment by cmorbaab** [comment]
I told you

**Comment by eruliaf** [comment]
It is clear that you do not realize the importance of this change. I will fork this project and share the results of this change later.

**Pull request closed without merging**
