### PR TITLE
Move --only --ignore to run earlier

### PR DESCRIPTION
**Pull request by NgJason**
## Description
Move --ignore and --only "down" , don't save it in to the db at all since we don't need it.

## Motivation and Context
Increase performance. This is also part of:https://github.com/AHAAAAAAA/PokemonGo-Map/pull/631
We do not need to save Pokemons that we do not need in to the db, since they will be ignored when get_active() executes. This will make the query[] shorter by X amount less iterations, where X is number of ignored Pokemons. 

## How Has This Been Tested?
- [ ] Testing
Pokemon servers are currently down, but ran some test in https://github.com/AHAAAAAAA/PokemonGo-Map/pull/631 before.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by toumaz** [comment]
I can see value in committing all data regardless of the current setting.

Won't this lead to somewhat confusing behavior if the app is restarted with different --only/--ignore settings? I fear you will "lose out" on a bunch of data you might want to present later. (Or if filter settings are later exposed as part of the UI, I'm not sure if this would be the way to go - not sure about plans there, so might be wholly irrelevant.)

I'd love to see if there's a notable performance increase or if it is negligible, too - if the latter, I'd value having historical data higher.

If performance is important, what do you think about instead adding indices to the database?`disappear_time` and `pokemon_id` seem like good candidates.

Perhaps modifying the query as appropriate to include `.in` and `.not_in` [operators](http://docs.peewee-orm.com/en/latest/peewee/querying.html#query-operators) would also do the trick?

**Comment by NgJason** [comment]
hi @toumaz You've raised a good point that having the entire data set and filter later is beneficial to front-end UI filter, but I am not sure if there are any plans for that yet. 

In regards to confusing behavior, I don't see that happening because when new filters is applied, the app restarts and search from 1% anyway.

**Comment by toumaz** [comment]
@NgJason Yes, but the database will still be populated with data from the previous search.

Let me try to explain it better. Right now, if you show  `--only` certain Pokémon, you'll still store data for all the rest, adding that to the database.

Let's say you then restart the app, deciding to show _all_ Pokémon, instead. You are correct in that search restarts, but since results are stored in and queried from the database, the previously found Pokémon will immediately be populated onto the map.

**Comment by AHAAAAAAA** [comment]
I agree with @toumaz. It won't be very consistent if we stored just specific pokemon when using those flags. It's easy just to store all and then filter.

**Pull request closed without merging**
