### PR TITLE
Pull Request #24 Resolution (Google Login)

### PR DESCRIPTION
**Pull request by acadiansith**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Merged the changes from pull request #24 (Google login) with b9703b3 since the codebase has changed quite a bit from the time the pull request was made (and because the pull didn't work out for whatever reason).

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by JZ6** [comment]
huh we could merge this one instead of #34 @AHAAAAAAA  @sykhro

**Comment by DerScreever** [comment]
Looks good for me.
But maybe to much requirements?

**Comment by Trozz** [comment]
when testing this PR I am getting 

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 1: 'utf8' codec can't decode byte 0xb0 in position 1: invalid start byte in field: ResponseEnvelop.Profile.unknown11
```

**Comment by DerScreever** [comment]
if we look at **pokemon_pb2.py** we find:
_descriptor.FieldDescriptor(
      name='unknown11', full_name='ResponseEnvelop.Profile.unknown11', index=7,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=**_b("").decode('utf-8'),**
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),

if we look at pokemon.proto the field is declared as **optional DailyBonus daily_bonus = 11;**
so pokemon_pb2.py needs to be regenerated. 
i did this with https://github.com/AHAAAAAAA/PokemonGo-Map/pull/84

**Comment by DerScreever** [comment]
please rebuild your branch with this base. to solve merge conflicts.

**Comment by AHAAAAAAA** [comment]
merged #126

**Pull request closed without merging**
