### PR TITLE
Fix "AttributeError: lat and lng required" when using coordinates as …

### PR DESCRIPTION
**Pull request by Scyntrus**
This pull request includes a

- [*] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Assign value to origin_lat and origin_lon global variables when coordinates are used for location

Previously, origin_lat and origin_lon was not set, causing an Attribute error when accessing the webpage.

### CODE REVIEW

**Comment by JZ6** [comment]
awsome work!

**Comment by benemorius** [comment]
works for me

**Comment by JZ6** [comment]
approved and merged!

**Comment by phantomkirby** [comment]
Thank you!

**Pull request merged**
