### PR TITLE
fixed stats table "Total" row

### PR DESCRIPTION
**Pull request by ov3rk1ll**
## Description
Fixed small visual error on stats "Total" rows

## Motivation and Context
The "Total" rows in the stats table are missing an empty td tag to have the background color all the way to the right

## How Has This Been Tested?
tested local on Windows and on Heroku without any new issues

## Screenshots (if appropriate):
Before:
Before

After:
After

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by invisiblek** [comment]
too slow :)

https://github.com/AHAAAAAAA/PokemonGo-Map/commit/60e720f880071a6b80acead2f4c4858d7a52abb8

**Comment by commanderjsoc** [comment]
This PR should be closed

**Comment by AHAAAAAAA** [comment]
@invisiblek you missed the arenalist and pokestoplist amendments it seems.

**Comment by invisiblek** [comment]
i see that, they show up white so it doesn't (visually) appear anything is wrong

**Comment by 123456abcdef** [comment]
Someone should also take care of the vertical centering of the text :P

**Pull request closed without merging**
