### PR TITLE
Use in game sprites for map markers

### PR DESCRIPTION
**Pull request by hhu94**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Now uses sprites extracted from the game assets for the map markers.
- Updated screenshot in README accordingly.

Please tell me if you like the size of the sprites. They were originally 128x128 but I resized them to ~~50x50~~ 65x65 because I thought they were too big. I still have the original 128x128 sprites.

cover

### CODE REVIEW

**Comment by nakami** [comment]
i personally prefer the old 2d sprites. also, they've strokes, so they're easy to make out.
why fix what ain't broken?

**Comment by hhu94** [comment]
I found the 2D sprites to be too small to see, specially on my phone, so I decided to try this. We could just use enlarged versions of the 2D sprites if everyone prefers those.

I think the ones from the game look nice, although I do agree a bit of contrast with the map is lost.

**Comment by DerScreever** [comment]
i would prefer this icons. but maybe we can do some options to use the old one :-)

**Comment by lorddusk** [comment]
It would be easy(ish) to add a parameter toggle.

**Comment by DerScreever** [comment]
yes true.

**Comment by haagiboy88** [comment]
Rainz in the discord has already resized all the icons. Waiting for him to upload them for a PR.

**Comment by CarlTaylor1989** [comment]
I guess it stays on brand with the application, I like them

**Comment by haagiboy88** [comment]
Arent these icons more blurry then the sprites we already have though? Rainz has already done the resizing of all of the icons, just waiting for him to get back on Discord and do a pull request.

**Comment by hhu94** [comment]
I have increased the size just a little more to 65x65 and added a black outline to the sprites to make them more visible on the map. I really like it a lot more now.

**Comment by DerScreever** [comment]
this is great. with the black border it is easy to see :+1:

**Comment by JZ6** [comment]
plus one from me

**Pull request merged**
