### PR TITLE
iOS Voiceover Support on Mobile Page

### PR DESCRIPTION
**Pull request by chuyskywalker**
## Description
Adds title card and `min/sec` string to make mobile page useful with VoiceOver. A follow up to #1696 

Also fixes a bug where the list would exception out the page since `Pokemon.get_active` was upgraded but this instance call was not modified to follow suit.

## Motivation and Context
Help accessible users use the app

## How Has This Been Tested?
Makes no significant changes to mobile page, but with VoiceOver turned on, iOS reads out the pokemon name, time, and distance effectively.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by chuyskywalker** [comment]
Browser:

2016-07-25 22_05_21-nearby pokemon

iOS:

**Comment by chuyskywalker** [comment]
@parkershepherd think you could give this a once over?

**Comment by parkershepherd** [comment]
@chuyskywalker I'm a bit concerned with the increase in page load size, as this is the low-bandwidth route. Before it was ~6.3KB (2.1KB gzip), but now it's ~95.3KB (33.45KB gzip)

I assume the countdown timer was causing issues with voiceover? (Also, are you familiar with geo links on ios? I know that's an outstanding bug atm)

**Comment by parkershepherd** [comment]
If we set up grunt to compile the css/js files, I could definitely help clean up the code formatting though

**Comment by parkershepherd** [comment]
Made a PR to your branch for the grunt stuff: https://github.com/chuyskywalker/PokemonGo-Map/pull/1 but jQuery is the main culprit still

**Comment by parkershepherd** [comment]
(removed jquery in my PR as well, size is now 8.7KB (3.3KB gzip))

**Comment by chuyskywalker** [comment]
I get that bandwidth, over all, is important, but jquery only has to be downloaded once then gets cached -- hand coding everything is a pita to maintain, imo, I really don't want to go down that route.

I'll definitely take up the grunt min/compress changes though.

And yes, the countdown timer made voiceover continually read the element every update. It was pretty funny, but ultimately very not-useful for a blind person.

**Comment by chuyskywalker** [comment]
Scratch that, taking a look over it I'm down to remove jquery

**Comment by parkershepherd** [comment]
haha page load optimization is a hobby of mine and I get go a bit overboard sometimes :p

**Comment by chuyskywalker** [comment]
Ok, all cleaned up now.

**Comment by parkershepherd** [comment]
looks great to me 👍

**Comment by chuyskywalker** [comment]
I forgot to respond; yes I know those geo links don't work on iOS; no I have no idea how to fix them :)

**Comment by parkershepherd** [comment]
I think iOS auto-recognizes links formatted along the lines of `http://maps.apple.com/...` and opens them in the native app, but `geo:...` works better in android. Might have to do some platform detection or something but that's another PR

**Comment by invisiblek** [comment]
But does iOS *pronounce* the pokemon names correctly? That's the real question here.

**Comment by chuyskywalker** [comment]
> But does iOS pronounce the pokemon names correctly? That's the real question here.

Astoundingly well, actually. It's kinda amazing.

**Comment by wcastello** [comment]
Tested, works for me, doesn't break anything +1

**Pull request merged**
