### PR TITLE
Fixed Locale for Pokemon names

### PR DESCRIPTION
**Pull request by Scildrei**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Implemented locale change if -L parameter is specified
- If locale parameter is invalid or unspecified, the locale defaults to config locale

If this is related to an existing ticket, include a link to it as well.
[#510](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/510)

### CODE REVIEW

**Comment by Scildrei** [comment]
I forgot the delete the logger, one sec.

**Comment by Scildrei** [comment]
All good one.

**Comment by Scildrei** [comment]
Bummer, I need to add the case when the user inputs more gibberish than I anticipated. One sec.

**Comment by sykhro** [comment]
It defaulting to the config is fine, but it should have a debug-only statement indicating that an invalid locale name was supplied too

**Comment by Scildrei** [comment]
All right, will do :)

**Comment by Scildrei** [comment]
Fixed. Push is halted due to bug [#529](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/529)

**Comment by Scildrei** [comment]
@sykhro Will log.info() do the trick?

**Comment by sykhro** [comment]
@Scildrei use log.debug()

**Comment by Scildrei** [comment]
@sykhro Let me know if I used the logger correctly. I cannot see the debug in console, not even with -d.

I moved the locale parsing to get_args() so we don't query the locale everytime we display the Pokemon names.

**Comment by sykhro** [comment]
You used it correctly, however you need to rebase, because this misses the Google API key checks.
-d was stubbed and I forgot to bring it back. Let me push this and try to see if everything works correctly (you need to rebase this anyway)

**Comment by Scildrei** [comment]
I worked on develop, I didn't create a new branch so I can rebase and I never rebased either, so I'm not sure what to do. Are the following steps correct?

- checkout new branch
- rebase develop into new branch

**Comment by sykhro** [comment]
checkout your branch, and then do `git rebase master`

**Comment by Scildrei** [comment]
Shouldn't I `git rebase develop`?

**Comment by favll** [comment]
Globals? Seriously? Sorry for sounding harsh, but this it the kind of stuff that got the support for the master branch dropped. This is a bad solution, for a problem that wasn't a problem before.

**Comment by Scildrei** [comment]
OK so I did:
`git remote add upstream https://github.com/AHAAAAAAA/PokemonGo-Map`
`git fetch upstream`
`git checkout develop`
`git rebase upstream/develop`
`git pull` - because my code didn't work
So now code still doesn't work and I'm ahead of my branch with 18 commits. Not sure what I need to do.

If you can, just close the request and copy-paste the code or let @favll submit something else.

**Comment by MonkeyLeeT** [comment]
Closed as requested. Thanks for the effort.

**Pull request closed without merging**
