### PR TITLE
Fix gym InfoWindow issues. (#2349)

### PR DESCRIPTION
**Pull request by tkSimon**
see Gym InfoWindow bug #2349

### CODE REVIEW

**Comment by tkSimon** [comment]
Will rebase once the code style guideline is published.

**Comment by chuyskywalker** [comment]
Come bakc and rebase! This bug drives me g'damn nuts!

**Comment by tkSimon** [comment]
rebased

**Comment by tkSimon** [comment]
@chuyskywalker rebased ;)

**Comment by andrewda** [comment]
A big :+1: for this fix!

**Comment by tkSimon** [comment]
Tested:
1. mouse over
2. [any of below events]
3. mouse out
4. window disappears

* update without change to gym
* update with points change only
* update with team change

**Comment by chuyskywalker** [comment]
Works great, thanks!

**Pull request merged**
