### PR TITLE
Make runserver.py executable

### PR DESCRIPTION
**Pull request by jesserockz**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Make the runserver.py file executable

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by alex-zige** [comment]
👍

**Comment by Zsub** [comment]
+1

**Comment by AHAAAAAAA** [comment]
Can you explain what's the need for this?

**Comment by Zsub** [comment]
Then you can just use `./runserver.py [arguments]` instead of having to do `python runserver.py [arguments]`. It's that little bit quicker in this gotta-catch-em-all world, you know?

**Comment by kingeddard** [comment]
@Zsub I tried but it wouldn't execute, what should i be inputting into Terminal (Mac)

**Comment by Zsub** [comment]
@kingeddard you have got to be in the right directory (the same as `runserver.py`) and then instead of `python runserver.py [all the other stuff]` you can type `./runserver.py [all the other stuff]`.

**Comment by jesserockz** [comment]
@Zsub @kingeddard There has been a commit (1818f9b) after this one that has switched it back to `0644` 😢

**Pull request merged**
