### PR TITLE
Add apple touch icons and home screen optimizations

### PR DESCRIPTION
**Pull request by rnarian**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Add apple touch icons
- Add home screen app optimizations (remove title/nav bar to show fullscreen map)

|||
|---|---|

### CODE REVIEW

**Comment by CarlTaylor1989** [comment]
Hi mate

This is great, I'll be sure to add this to the project.

Good work.

**Comment by kingeddard** [comment]
@rnarian is the mobile app part of this project? Where can I look to get that?

**Comment by rnarian** [comment]
@kingeddard On the iPhone you can turn webpages to apps by adding them to the homescreen. These optimizations make sure the website looks ands acts a bit more app-like if added to the homescreen.

**Comment by Zeromark30** [comment]
Android can do the same thing.

**Comment by rnarian** [comment]
@Zeromark30 Do you know the relevant meta tags? I could add them to the PR. Or does it work with the ones specified on android too?

**Comment by Zeromark30** [comment]
looks like it might work with the same code. Information below:
https://developer.chrome.com/multidevice/android/installtohomescreen
Why the code may work: https://developer.chrome.com/multidevice/android/installtohomescreen#fallback

**Comment by rnarian** [comment]
@Zeromark30 Thanks man!

I added the line `<meta name="mobile-web-app-capable" content="yes">` too, to get rid of the deprecation warning.

**Pull request closed without merging**
