### PR TITLE
Revert "Revert "Use a sprite for the pokemon on the map" (#1640)"

### PR DESCRIPTION
**Pull request by invisiblek**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

* fix the logic for y

This reverts commit 5fff2fa56d57833800347b342e981d174aad064f.

### CODE REVIEW

**Comment by invisiblek** [comment]
logic fixed, y was wrong if it was the last in the row

**Comment by marauder37** [comment]
+1

**Comment by Idhanta** [comment]
+1

**Comment by invisiblek** [comment]
@Jankos1985 y is calculated based on how many are in each row, not how many rows there are total

**Comment by Hoekynl** [comment]
Why is a sprite actually used? arent seperate images way easier?

**Comment by invisiblek** [comment]
fewer requests to the webserver

**Pull request merged**
