### PR TITLE
Add iOS port to README.md

### PR DESCRIPTION
**Pull request by istornz**
Port in development

### CODE REVIEW

**Comment by andrewda** [comment]
Very nice port. :+1:

**Comment by Bitti09** [comment]
would be good to have an android version (client only) of it

**Comment by Ayysir** [comment]
@Bitti09 https://github.com/omkarmoghe/Pokemap

**Comment by San-Francisco** [comment]
Hey man, I'm not sure where this is where I am suppose to go for this but the reddit post led me here about any issues for the pokemongomap. When ever I started the pip install -r requirements.txt command in terminal, when it gets to the part where it says (line 15) It loads for a little and i get this message. "Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vn/tfpnllds63s7qx7r1ww1qx4r0000gp/T/pip-build-dVaIPZ/protobuf-to-dict/" Like I said, I am new to this website, so I have no idea if this is the place to write about this but if it is, could you please help me out. Thanks!

**Comment by capnslipp** [comment]
@San-Francisco Click the Issues tab near the top of the page, then search for your error message to see if someone else has already solved it.  If not, go back to the issues list and click New Issue; then fill in with all the information you reported here plus other relevant information: OS & version, `python --version`, PokemonGo-map revision (inside the `PokemonGo-Map` directory run `git show master`).

**Pull request merged**
