### PR TITLE
Added git to Dockercontainer to be able to install new requirements.txt

### PR DESCRIPTION
**Pull request by Sjark**
## Description
A new requirement was added to requirements.txt that pulls from git, but git was not included in the docker container.

This pull request adds git to the container before trying to install the requirements

## Motivation and Context
To fix docker build

## How Has This Been Tested?
Built and ran a docker image

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
+1

**Comment by chuyskywalker** [comment]
Thanks!

**Comment by ultrafez** [comment]
Why are openssh and bash included? There's no need to be able to SSH into the container (use `docker exec` if you want to run a command (such as a shell) inside the container), and since this is the release Dockerfile (as opposed to the dev Dockerfile), bash shouldn't be included either.

If I get time I may make a PR to remove the unnecessary packages and combine the two `install` lines together.

**Comment by chuyskywalker** [comment]
Openssh is probably used as part of git, perhaps? `bash` is a bit odd to include since it already has `sh`

**Pull request merged**
