### PR TITLE
Add vanilla map (no GUI)

### PR DESCRIPTION
**Pull request by andrewda**
## Description

This is a pretty significant addition, but has no breaking changes to anything existing. This adds `/vanilla` that does not contain a GUI (i.e. it's just a map) to make it easier for people attempting to port this app into their own projects. A great example of this would be [mchristopher/PokemonGo-DesktopMap](https://github.com/mchristopher/PokemonGo-DesktopMap), which is currently using an outdated version of this repository for exactly this reason. This will not affect any other users besides those using/creating ports.

## Motivation and Context

As mentioned above, this will make it much easier for developers to make custom ports of PokemonGo-Map to implement into their own projects. 

## How Has This Been Tested?

This has been tested on Chrome/Firefox on Mac/Linux/Windows. There should be no compatibility issues, as this is almost identical to the regular project, minus the GUI.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JZ6** [comment]
need testing

**Comment by chuyskywalker** [comment]
This duplicates a LOT of code, especially `map.js` which would start making keeping it and the non-vanilla one up-to-date quite difficult. I'd _almost_ rather we set this up in such a fashion that the PokemonGo-Map UI was layered on top of the map, and there was a, perhaps, `get` url param to disable rendering the PGM ui. That way as the pokemon end points update and evolve, the vanilla page won't get forgotten and broken.

**Comment by Chlodochar** [comment]
I don't like this either. Any change that's being done on the gui will need to be considered to be merged here as well. However, to get this feature in properly, the GUI will need some modularity. Otherwise it'll get even messier.

**Comment by AHAAAAAAA** [comment]
I agree with the previous 2 comments, putting this on hold and closing PR.

**Pull request closed without merging**
