### PR TITLE
Make position marker draggable for location change

### PR DESCRIPTION
**Pull request by POPSuL**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Current location marker maked draggable

If this is related to an existing ticket, include a link to it as well.

This PR is replace for https://github.com/AHAAAAAAA/PokemonGo-Map/pull/1111

### CODE REVIEW

**Comment by goudacoin** [comment]
i can't get the marker to move? is there something else i should be doing?

**Comment by POPSuL** [comment]
@goudacoin maybe clear browser cache

**Comment by goudacoin** [comment]
@POPSuL did that still no luck. here is my map http://gouda.tech:5000/

**Comment by POPSuL** [comment]
@goudacoin hmm... your map works as expected. Red marker are draggable.

**Comment by goudacoin** [comment]
ill try a different browswer currently using chrome on windows 10

**Comment by goudacoin** [comment]
firefox on window 10 allows me to move it. however how long does it take for that location to start to update? does it need to finish the steps in the old location first?

**Comment by goudacoin** [comment]
works on chrome on ios 10 beta 3 on iphone 6s.

**Comment by goudacoin** [comment]
i had changed my steps to 5 from 10 so it updates quicker from each location change

**Comment by FrostTheFox** [comment]
Just a heads up, this doesn't work on Chrome with uBlock Origin installed. Can't drag the pin.

**Comment by JeffBrown04** [comment]
is there a way i could add the drag and drop location feature to jxmorris12's PokemonGo-Finder?

**Comment by tanmays** [comment]
Can't wait for this to get merged! Just tried it out and works great on iOS!

**Comment by hris27** [comment]
```javascript
marker.addListener('mousedown', function (e) {
    e.stop();
});
```
This little piece of code seems to fix the Chrome issue.

**Comment by JeffBrown04** [comment]
how do you stop gyms and pokestops from being loaded?

**Comment by pickett2k** [comment]
was able to drag reference point but it did not refresh the pokemon search even after loop on firefox

**Comment by marauder37** [comment]
Got this done in #1650 , thanks

**Pull request closed without merging**
