### PR TITLE
Basic Pokemon Statistics Page

### PR DESCRIPTION
**Pull request by GamingMaster2000**
## Description

Added a simple statistics page (/stats) showing the number of Pokemon seen over a duration of time (ranging from hours to map's liftime).

## Motivation and Context

Gives us a way to see what (and how often) the different Pokemon appear on our maps.

## How Has This Been Tested?

Ran my own server and tested page to compare to database

## Screenshots (if appropriate):
stats

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by karezhest** [comment]
Won't update statistics for me. Starts with this 

Yeah, I see these pokemon, but the stats aren't updating and after a few reloads Voltorb disappeared

**Comment by GamingMaster2000** [comment]
I think I've fixed the issue.

Also added option on the stats page to select the duration for which you want to view stats.

**Comment by karezhest** [comment]
Nice! Looks great! Any plans for auto refresh and sorting by different columns?

**Comment by GamingMaster2000** [comment]
Yeah, they're on my mental todo list but I've run out of time tonight (10pm here and still have some other stuff to do before turning in for the night :p). I'll keep working on improvements tomorrow (unless someone happens to beat me to it over night). :)

**Comment by Ayysir** [comment]
would be best to rebase this commit into one with a extensive description

**Comment by GamingMaster2000** [comment]
Hopefully I've rebased everything correctly. I'm brand new to github so am still figuring out all this pull request/rebasing stuff.

**Comment by Ayysir** [comment]
If anything I did the rebate already on my fork

**Comment by GamingMaster2000** [comment]
Oh, I forgot to mention I also modified the stats page a little to make it look (IMO) better.

**Pull request closed without merging**
