### PR TITLE
Center map on optional URL passed coords

### PR DESCRIPTION
**Pull request by razer86**
## Description
Adds optional 'lat' and 'long' variables to the URL to allow the map to be centered anywhere on load.

## Motivation and Context
Can be used to center the map on any location, useful for multiple -ns scanned locations and a single webserver port.

## How Has This Been Tested?
Start webserver with a target location
`runserver.py -l "-23.850012, 151.257375" -fl -os` 

Load webpage with another location in the URL
`http://localhost:5000/?lat=-23.835443&long=151.252734`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Load and center map on coords given via url.
Based on code by @wbechard

### CODE REVIEW

**Comment by emsyzz** [comment]
I noticed, that abbreviation of _longitude_ is different in some places.
Can we stick to Google Maps API supplied abbreviations: **Lat** and **Lng**?

**Comment by razer86** [comment]
Adjusted abbreviation to match Google Maps API

**Comment by skeldoor** [comment]
Is this working? It doesn't seem to change the location when passed the lat and lng in the url

**Comment by razer86** [comment]
Was never merged, might reopen the pr at some stage. I used and modified an original pr to create this one. Think the devs aren't interested in this function

**Comment by skeldoor** [comment]
It's just that I tried testing it and it didn't seem to have any effect on the map at all. Am I missing something?

**Pull request closed without merging**
