### PR TITLE
Delete requirements.txt

### PR DESCRIPTION
**Pull request by Acidvenom73**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Cleanup

The following changes were made:

The requirements.txt is redundant, the setup.bat uses the one already in the main folder.

### CODE REVIEW

**Comment by Bitti09** [comment]
setup.bat on develop branch seems to be win only  so: :-1: until there is a linux version.

**Comment by shivampaw** [comment]
What if you don't use windows?

**Comment by machadox** [comment]
i run in ubuntu server...

**Comment by Pedrock** [comment]
@Bitti09 @shivampaw @machadox This PR just deletes the requirements.txt in the Easy Setup directory. It does not delete the main requirements.txt file.

**Comment by Acidvenom73** [comment]
That shouldn't be a problem, it's still in the main. @machadox @shivampaw @Bitti09

**Comment by MonkeyLeeT** [comment]
Please rebase.

**Comment by k0mat** [comment]
Will heroku be able to get the dependecies without requirements.txt?

**Pull request closed without merging**
