### PR TITLE
Correct Dockerfile

### PR DESCRIPTION
**Pull request by jnovack**
This pull request includes a

- [X] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

* Ignore `.git/`
* Add comments where necessary.
* Move all disk changes below all meta-commands
* Hard-code `--host 0.0.0.0` to ENTRYPOINT
* Set default command to display help when no arguments are given

### CODE REVIEW

**Comment by jangrewe** [comment]
You're setting "-h" both in ENTRYPOINT and CMD, i don't think that will work. I'd rather use:

```
ENTRYPOINT ["python", "./runserver.py"]
CMD ["-h"]
```

**Comment by jnovack** [comment]
That's what I get for rushing.  I opted to recreate the file rather than rebase with merge conflicts.

**Comment by JZ6** [comment]
+1

**Comment by MonkeyLeeT** [comment]
Thanks for the prompt work!

**Pull request merged**
