### PR TITLE
make marker position draggable

### PR DESCRIPTION
**Pull request by Chlodochar**
## Description
Allows dragging of the search marker. Instead of typing the place to put the searchmarker in the sidebar, you can just drag it.

## Motivation and Context
It's convenient.

## How Has This Been Tested?
By dragging the marker on my webserver and seeing it search a different area.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Kryakz** [comment]
I cant see pokestops or gyms

**Comment by marauder37** [comment]
Really? Seemed to work ok for me

**Comment by MonkeyLeeT** [comment]
#1129 Any improvement?

**Comment by Chlodochar** [comment]
@MonkeyLeeT Most importantly, it's mergable on develop.

**Comment by Idhanta** [comment]
Unable to drag it in Safari

**Comment by Chlodochar** [comment]
@Idhanta any error you came across?

**Comment by marauder37** [comment]
There's no error in Safari, the whole map just moves when you drag the pin

**Comment by Idhanta** [comment]
exactly what marauder said.
Also, the marker moves in Chrome, but no pokemon show up.

**Comment by Idhanta** [comment]
Ran the code in debug mode and the marker was magically movable in Safari. Chrome still no pokemon.

**Comment by Chlodochar** [comment]
@Idhanta Maybe some pokemon was blocking the marker?
As for not seeing pokemon appear, is that actually related to the marker dragging or are they hidden regardless of the marker being dragged? See the sidebar and check whether "change your location" actually works.

**Comment by Idhanta** [comment]
@Chlodochar could be a pokemon blocking. Not sure. 
For chrome, no pokemon load up regardless of the marker being dragged.

**Comment by Idhanta** [comment]
@Chlodochar Little more clarity for the chrome issue, if I run on localhost, it doesn't load the pokemon, while running with 0.0.0.0, it loads them and everything works. No idea why.

**Comment by Chlodochar** [comment]
Are pokemon actually enabled in the sidebar? I've noticed there is a bug related to those filter options (localStorage). I'll check that out and make a PR if it's actually a bug and not something else. I presume localStorage differs between domains.

Also, cache maybe?

**Comment by Idhanta** [comment]
ok, so clearing cache worked. 
Everything looks good for both browsers now.

**Comment by Chlodochar** [comment]
@Idhanta yay, thanks for testing.

**Comment by Chlodochar** [comment]
@marauder37 thanks!

**Comment by Hoekynl** [comment]
Could you implement a button which resets the marker (and scan) to its original location?

**Comment by JZ6** [comment]
+1 reset please

**Comment by Chlodochar** [comment]
Hmm, it seems nicer to have a list of bookmarked locations or something like that? What would be the workflow for resetting the location?

**Comment by Chlodochar** [comment]
At the moment a server restart does reset the location. So it could probably be retrieved from commandline or config.

**Comment by Hoekynl** [comment]
Yeah I think it should be something like
Original location = (get from command execution or config file)
When the button is pressed, set location to original location

**Comment by primaxius** [comment]
Need a way to disable this!

**Comment by Kryakz** [comment]
Why? You don't have to drag it

**Comment by Hoekynl** [comment]
But if im outside, on my phone and im at the default location, walk away and want to scan tjat area. Then I drag the marker. If i walk back I want to be able to reset it

**Comment by Kryakz** [comment]
Or just drag it back...

**Comment by Hoekynl** [comment]
I use the "show scanned locations". If i drag it back its not precisely on the last location and there would be red and green circles over eachother making it hard to see pokemon.

**Comment by Chlodochar** [comment]
@Hoekynl IMO the problem in that case is that the search-cells do not align well. It would be better to split the world into a 'grid' and use the cells of that grid to search. Now you can have off-by-0.0001 errors that cause extra search-cells.

**Pull request merged**
