### PR TITLE
Alert users with a sound when a Pokemon is visible

### PR DESCRIPTION
**Pull request by NgJason**
- [x] Feature

Alert users when a Pokemon is discovered by playing the audio file: a.wav. 

This is especially useful when a user is multitasking with the -only flag.

Usage: 
pip install --upgrade -r requirements.tx
To activate audio for console, add -s flag.
To activate audio for web browser, add -sw flag.

### CODE REVIEW

**Comment by Josephvb10** [comment]
I think this would be better if implemented in the HTML client, not in the Python script.

**Comment by NgJason** [comment]
@Josephvb10 I run the program without opening any browsers. Of course I have the Pokemon's information printed out in the console. You can see that functionality in the following pull request: #341

**Comment by NgJason** [comment]
Anyone know of a way to import libraries via Travis CI so it can properly run the test?

**Comment by NgJason** [comment]
Travis-ci has issues with pip install pyaudio.

**Comment by frdmn** [comment]
I see your use case @NgJason, but I also agree with @Josephvb10 - I use the map with my friends so we just have the browser running and the server is an EC2 instance. 

I think it should be configurable then, if either the client or the server plays the alert sound.

**Comment by NgJason** [comment]
@frdmn I added the feature to play audio via web browser.  If you don't mind, please try it out and give me your feedback. 

If your EC2 is running Linux, it might require additional steps to install the pyaudio library. Travic-ci failed when it tried to compile pyaudio.

**Comment by frdmn** [comment]
Works great for me (tested only `-sw`). Nice work.

Regarding your failed Travis test case, perhaps [the shared audio libs are missing](http://stackoverflow.com/a/35708669/2940412)?

**Comment by guest136** [comment]
Hello, I tried that flag but it isnt working by me or am I doing anything wrong. I added -sw to my command like this:

python example.py -a google -u ***@gmail.com -p *** -l "40.739663 -73.992102" -st 10 -ar 3 -sw

**Pull request closed without merging**
