### PR TITLE
Add -o flag to complement -i flag

### PR DESCRIPTION
**Pull request by hhu94**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added support for the -o (--only) flag, which is mutually exclusive with the -i flag.
- Updated README.md to reflect the change.

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by medghaim** [comment]
This is awesome!

**Comment by AHAAAAAAA** [comment]
+1, clean and simple. I say we merge after someone else confirms this works for them!

**Comment by galaktb** [comment]
I can confirm this works, I made an identical addition earlier and had no problems whatsoever

**Comment by AHAAAAAAA** [comment]
rebase and we can merge!

**Comment by hhu94** [comment]
Done!

**Pull request merged**
