### PR TITLE
When removing a pokemon, set a flag so we don't try to draw it again later

### PR DESCRIPTION
**Pull request by invisiblek**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tsvetant** [comment]
I think `clearOutOfBoundsMarkers` would require a gentle touch as well with that applied.

**Comment by invisiblek** [comment]
this patch isn't right, too many things error on null later

**Comment by invisiblek** [comment]
try that

**Comment by CarlTaylor1989** [comment]
+1

**Comment by AHAAAAAAA** [comment]
+1

**Pull request merged**
