### PR TITLE
Support for lured pokestops.

### PR DESCRIPTION
**Pull request by MonkeyLeeT**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-Added support for lured pokestops, as well as option to display only those lured stops.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
Feel free to add countdown for this, but for such short-lived thing I'd say static time display is good enough.

**Comment by DerScreever** [comment]
nice :+1:

**Comment by benemorius** [comment]
Awesome. Works for me. Can you rebase?

**Comment by MonkeyLeeT** [comment]
Rebased. Good to go now.

**Comment by romreed** [comment]
good work.Can you show me were i can change radius of search?

**Pull request merged**
