### PR TITLE
Add MySQL DB details to command line parameters.

### PR DESCRIPTION
**Pull request by clbuttic**
## Description
New command line parameters:

```
  -dh DB_HOST, --db-host DB_HOST
                        MySQL DB Host or IP. Overrides value in config.ini
  -do DB_PORT, --db-port DB_PORT
                        MySQL DB port (usually 3306). Overrides value in
                        config.ini
  -dn DB_NAME, --db-name DB_NAME
                        MySQL DB name. Overrides value in config.ini
  -du DB_USER, --db-user DB_USER
                        MySQL DB User Name. Overrides value in config.ini
  -dp DB_PASS, --db-pass DB_PASS
                        MySQL DB Password. Overrides value in config.ini

```
These override whatever values are set in config.ini

## Motivation and Context

Request in discord channel, and I found it to be useful

## How Has This Been Tested?

Tested with the following tests:

1.  Ran default clean install, which uses SQLite.
2. Ran default clean install, with MySQL details in config.ini.
3. Ran default clean install, with incorrect MySQL details in config.ini and correct details in command line. Verified that the command line parameters overrode those set in config.ini.
4. Ran default clean install, with config.ini set to use SQLite, and specifying MySQL details in above parameters. MySQL server used instead of SQLite.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Parameters might be useful to mention in docs.

### CODE REVIEW

**Comment by leTokki** [comment]
How about adding a port option?

**Comment by clbuttic** [comment]
@leTokki Is it not inherited with host? host:port as the full, if no host specified, then 3306 is assumed?

**Comment by leTokki** [comment]
Not sure, but for some reason host:port never connected for me, i had to add port='' for it to finally connect

**Comment by clbuttic** [comment]
I'm happy to add it. What would you suggest as the short form? -do ? -dp is taken for --db-password

**Comment by leTokki** [comment]
-do seems good, thanks

**Comment by clbuttic** [comment]
I had to change a few other things to add a port specifier: e461e1e3ef114359aa066f41979655f39f430dcb

**Comment by Talamar1** [comment]
Someone needs to figure out how to handle sockets instead of ports, more secure and faster

**Comment by clbuttic** [comment]
@Talamar1 It's doable, but require connection string as an alternative. Peewee does accomodate this. Will have a look.

**Comment by clbuttic** [comment]
@Talamar1 I believe Peewee uses the unix socket when localhost is the given hostname. Still, a connection string might be useful. I'll leave this for another PR.

**Comment by Plop** [comment]
This is what I want ! Please merge ! :D

**Comment by invisiblek** [comment]
superseded by https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2021

**Comment by ycraaron** [comment]
Cooooooooooool!!!

**Comment by badroum** [comment]
I have seen that there is no argument / config option for the DB Port when you do want to use the non default-one. I searched through pull requests and I landed on [e461e1e](https://github.com/AHAAAAAAA/PokemonGo-Map/commit/e461e1e3ef114359aa066f41979655f39f430dcb?diff=split) where a request had already been sent. Could you tell me if you plan on putting back this option ?  had already been sent and treated

**Pull request closed without merging**
