### PR TITLE
Fix ES6 template string

### PR DESCRIPTION
**Pull request by DeWenS**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Fix ES6 template string

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by DerScreever** [comment]
@DeWenS 
you are done with this? or you want to add more?

**Comment by DeWenS** [comment]
Now think its ok

**Comment by DerScreever** [comment]
@DeWenS 
then clean it up pls....
i will merge when the code is okay.

**Comment by benwaffle** [comment]
You could just add babel to grunt

**Comment by BillyWM** [comment]
This backslash syntax is not part of the ECMAScript standard. Also you're mixing concatenation - "str" + "another str" - with the backslash multiline trick, which defeats the purpose. Might as well just do

"line" +
"next line" +
"another line"

The safest and cleanest thing IMO is a string replace, and use normal concatenation to handle multiline.

var str = "$poke is the best Pokemon" +
"like no one" +
"ever was";

str = str.replace("$poke", pokemon_name)

--------------

Babel is cool and I use it in my personal projects, but it can cause friction when using a debugger (You'll be stepping through transpiled output, and have to generate sourcemaps to get a semblance of the original back)

**Pull request closed without merging**
