### PR TITLE
Updated Label and Colors for Gyms and Pokemon

### PR DESCRIPTION
**Pull request by Djimusic**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

This makes the labels look a lot more better, and allows for the labels to be functional.
* Made the Pokemon # clickable which links to the pokedex.
* Below each of the names, it now shows a 100 x 100 picture of the pokemon. (Good for newbies who do not recognize the icons.)
* Gym Color Names are now capitalized, and have an overlay of the color.

### CODE REVIEW

**Comment by marauder37** [comment]
lgtm, merging

**Comment by marauder37** [comment]
Thank you for your PR!

**Comment by Djimusic** [comment]
Have an updated one for gyms and pokestops coming soon!

**Comment by AHAAAAAAA** [comment]
I agree with medghaim, it does seem excessive.

**Pull request merged**
