### PR TITLE
Get correct s2 cells

### PR DESCRIPTION
**Pull request by EarthlingKira**
I've fixed incorrect S2 cell retrieval, see:
https://www.reddit.com/r/pokemongodev/comments/4vo59c/psa_servers_block_visibility_of_mons_from_some/

In some cases we never got the neighboring cell by following next/prev, so I used the proper methods for this

### CODE REVIEW

**Comment by Tr4sHCr4fT** [comment]
@tejado can you upstream this please?

**Comment by medghaim** [comment]
The issue you describe _will_ indeed occur in edge cases. Here's a more extreme example:
3 10 steps front back

This issue rears itself prominently in `-st 1` situations but when building a hexagon, the ingenuity of the Hilbert curve comes into play. 10 backpath + center + 10 frontpath (21 lvl15 cells total) from each step_location builds pretty complete coverage of the desired search area. Also, using a hilbert crawl preserves the integrity of cell order, which we can definitely use to our advantage to speed things up. 

Lastly, I personally discourage changes to pogoapi from here directly. This could cause some issues down the line when Tejado inevitably adds some cool new stuff to Pogoapi, and we want to switch to a newer version -- but we've already built off of changes you made here. I suggest you submit a pull to https://github.com/tejado/pgoapi, where the changes can be discussed with the man himself :)

**Comment by AHAAAAAAA** [comment]
It's our intention to use pgoapi as a package soon, changes to the api should be directed to tejado!

**Comment by EarthlingKira** [comment]
It seems like tejado implemented a different (more complex, not necessarily better ;-) ) solution:

https://github.com/tejado/pgoapi/blob/master/pgoapi/utilities.py

**Comment by EarthlingKira** [comment]
@medghaim 
Sadly it's not so easy, you always have the problem, even with -st 15... The problem is some Pokemon not appearing on the map due to this cell problem. The server will only send you Pokemon in the 70m radius if you send the correct s2 cell id in the request, so this is always a problem

**Comment by medghaim** [comment]
image

**Comment by EarthlingKira** [comment]
@medghaim In your case it works because the "hilbert walk" luckily walked over both required s2 cells. But I have 2 cells in front of my flat where I *always* missed the pokemons in one spot with PokemonGo-Map due to this. I mean *always*, since days. And then I found out after debugging that exactly that s2 cell ID is *always* missing due to the "hilbert walk"

**Comment by medghaim** [comment]
Yeah, I'm not arguing the edge cases don't exist. They do and it is (mostly) the cause of the missing pokemon, due to the bizarre path of the hilbert curve:
image

The cleanest solution to this would be to grab radius, as @tejado is currently doing. 


As for the overlap I was mentioning, it really does generate a _lot_ of overlap, so you're more likely to grab a pokemon than miss it:

image
This image plots the level 15 s2cells that _each_ scan location pulls in (ie, this DOESN'T include the 10 forward/10backwards steps) - if this were the state of things it would be scary, but:

image
This is with all the +10/-10 paths plotted as well. As you can imagine, there's a fair bit of overlap, but definitely not enough to find all the pokemon. 

RegionCoverer is cool because we can specify min/max levels, and build an _almost_ perfect circle. outta different level cells (ie, bigger smaller).

**Comment by Dagothur** [comment]
@EarthlingKira 

Should I apply this change to my develop branch or switch over to the pogoapi-purge branch instead?

**Pull request closed without merging**
