### PR TITLE
Added parameter for single scan

### PR DESCRIPTION
**Pull request by EdenGottlieb**
Added -ss parameter that enables scanning the map once.
## Motivation and Context

#2031 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JZ6** [comment]
but why?

**Comment by EdenGottlieb** [comment]
Because #2031 asked for it. It is mentioned in the "Motivation and Context" section

**Comment by DeviantEng** [comment]
I can see a benefit to this.  My current setup is scanning 5 rural-ish towns in eastern Kentucky.  Very spread out, and if I set the location on the city name with a large number of steps, the scan will take 5-8 minutes to finish which is no good.  Instead I am using `-st 7` with coordinates, so I have to take the time to setup coordinates exactly where I want them to overlap nicely.  

Using `-ss`, I could run a loop and kick off a new scan of each city every 60 seconds.  Would keep things fresh, even though each scan is taking 5-10 minutes to finish.  That would be a 3 fold improvement on my current ~3 minute scan times with a 7 step.  

If you're interested in seeing how I have mine currently set, it's publicly available at https;//ekypokemap.com

**Comment by ewold** [comment]
I would also see the benefit of this. For example i can give the coordinates of my cell phone so the application tracks only the surrounding of my location where i'm currently at.

**Comment by DeviantEng** [comment]
Any movement with getting this merged?

**Comment by jforr** [comment]
I've been testing this and the only issue is that the shell will remain open after the search has been completed.  This is probably expected behavior if a server is also being run off this instance, however if you're using the -ns flag the shell should exit upon completion of the search.

**Comment by DeviantEng** [comment]
I plan on testing this tomorrow, as well.  I'm getting to the point with my current setup (about 35 scans running on different coordinates, 7 steps) isn't able to keep up.  Scans are taking quite a while to finish, and I'm looking to add more locations as it is.  Box is CentOS 7 with 8 CPU cores and 8GB RAM, and the CPU is definitely the limiter.  

Anyway, moving to city names for my locations and a larger radius, should work out nicely with a single scan.  I can have a script for each city that would kick off a scan, wait 60 seconds and kick off another.  Continuous loop at that point.  As long as each scan is finishing, nothing should ever be out of date more than 60 seconds.  

Also considering a multi-server setup to distribute the load (I have lots of resources sitting unused with Cloud at Cost, so I'm using them for a regional map for many users).

**Comment by jforr** [comment]
I've done some logging and testing on my own and the thread is getting locked at the line of code below.

`i, step_location, step, lock = q.get()`

**Comment by AHAAAAAAA** [comment]
Difficult to rework this into current project, but I opened an issue #3294

**Pull request closed without merging**
