### PR TITLE
small changes to NAV

### PR DESCRIPTION
**Pull request by callmebackdraft**
## Description
*Changed name of menu to Options, as there are more than just filter options in the menu
*Added horizontal bars between the several parts of the nav menu
*relocated and changed some text

## Motivation and Context
No issues being solved here, just provides a cleaner view

## How Has This Been Tested?
run several times after change to make sure the menu performed as intended on both
Desktop and mobile devices

## Screenshots (if appropriate):
capture

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

making the NAV just a tad more clean

### CODE REVIEW

**Comment by invisiblek** [comment]
+1 this is nice

**Comment by MonkeyLeeT** [comment]
Looks good.

**Comment by Hoekynl** [comment]
Messes up the Hide Common pokemon input, its now a scroll bar?

**Comment by callmebackdraft** [comment]
@Hoekynl 
thiscould be edited further so the text is somewhat smaller this makes it so that on smaller mobile screens the nav doesn't need a scrolbar

**Pull request merged**
