### PR TITLE
Revert "update get_cellid to use s2cell coverage instead of linear path"

### PR DESCRIPTION
**Pull request by JZ6**
This should fix the low pokemon problem

### CODE REVIEW

**Comment by Chlodochar** [comment]
Why is this incorrect?

**Comment by medghaim** [comment]
+1. Let's leave PoGoAPI alone. It's dangerous to build functionality into pogoapi, then build off that. Updating pogoapi would be a nightmare in the future.

**Comment by MonkeyLeeT** [comment]
+1. Better not to touch PoGoAPI.

**Comment by JZ6** [comment]
lets go

**Comment by andrewda** [comment]
Related: https://github.com/AHAAAAAAA/PokemonGo-Map/pull/671 - will prevent more changes like this unless they're done upstream.

**Comment by Chlodochar** [comment]
Can one of you please take a look at #671. I'm trying to keep it alive, because I feel it is necessary to be merged, but I have been forced to rebase it around 8 times (with conflicts each time) because of PRs like this one. It would be really helpful to get some feedback and eventually be merged.

**Pull request merged**
