### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by KevakaBuel**
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [ ] Translation
- [x] Typo in README.md

The following changes were made

Fixed typo: andriod -> android

### CODE REVIEW

**Comment by DerScreever** [comment]
@KevakaBuel pls resolve the conflicts.

**Comment by KevakaBuel** [comment]
Done, sry for that

**Comment by KevakaBuel** [comment]
Resolved conflicts with the new README

**Comment by MonkeyLeeT** [comment]
Can you update again? I don't see why you need to touch other places when you only need one change one word.

**Comment by KevakaBuel** [comment]
Im a bit new to github an the readme changed half way trough, i guess i will just try to setuo a new pull request

**Pull request closed without merging**
