### PR TITLE
Added external notification support. (Pushbullet, Slack)

### PR DESCRIPTION
**Pull request by kvangent**
## Description

Added the ability to add alarms, which trigger notifications for outside resources through channels such as Pushbullet or Slack. Which pokemon trigger alarms can be turned off or on as well. Everything is configured in the alarms.json file. 

## Motivation and Context

This was originally done by jxmorris12, but fell behind as updates were added to the map. I wanted to add this feature to the new version of the map. The goal was to make it easy to add new types of alarms and be as least invasive on the original code as possible. 

## How Has This Been Tested?

Self-tested the most recent changes but setting it up and running around town. I also put an earlier version up on Reddit, so several uses have given this a shot to try it out. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by marauder37** [comment]
Can we get this rebased onto develop please?

**Comment by Alexio35** [comment]
How does it work ?

**Comment by Kryakz** [comment]
I keep getting spam-notified on pushbullet about the same pidgey. Also, I kept getting 
```
Traceback (most recent call last):
  File "runserver.py", line 15, in <module>
    from pogom.search import search_loop
  File "C:\Users\Nolan\Desktop\PokemonGo-Map\pogom\search.py", line 13, in <module>
    from alarm.notifications import Notifications
  File "C:\Users\Nolan\Desktop\PokemonGo-Map\pogom\alarm\notifications.py", line 9, in <module>
    from slack_alarm import Slack_Alarm
  File "C:\Users\Nolan\Desktop\PokemonGo-Map\pogom\alarm\slack_alarm.py", line 4, in <module>
    from slacker import Slacker
ImportError: No module named slacker
```

**Comment by shme14** [comment]
I'm getting some errors trying to run your branch:

```
Traceback (most recent call last):
  File "runserver.py", line 15, in <module>
    from pogom.search import search_loop
  File "C:\Users\Jamie\Documents\GitHub\With Alarm\PokemonGo-Map\pogom\search.py", line 13, in <module>
    from alarm.notifications import Notifications
  File "C:\Users\Jamie\Documents\GitHub\With Alarm\PokemonGo-Map\pogom\alarm\notifications.py", line 9, in <module>
    from slack_alarm import Slack_Alarm
  File "C:\Users\Jamie\Documents\GitHub\With Alarm\PokemonGo-Map\pogom\alarm\slack_alarm.py", line 4, in <module>
    from slacker import Slacker
ImportError: No module named slacker
```

**Comment by kvangent** [comment]
I forgot to add Slacker into the requirements.txt, but I have since added it. Is there a way I can update this to the pull request?

**Comment by Kryakz** [comment]
idk if you can update to this pull request, but for everyone interested in how to fix it, In requirements.txt just put this
```
Flask==0.11.1
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
argparse==1.2.1
click==6.6
itsdangerous==0.24
peewee==2.8.1
wsgiref==0.1.2
geopy==1.11.0
protobuf==2.6.1
requests==2.10.0
s2sphere==0.2.4
gpsoauth==0.3.0
protobuf-to-dict==0.1.0
flask-cors==2.1.2
pushbullet.py==0.10.0
slacker.py

```

**Comment by Kryakz** [comment]
I keep getting notified of the same pidgey over and over again

**Comment by kvangent** [comment]
Are you sure it is the same pidgey? I've been running it for a while and never had a repeat.

**Comment by Kryakz** [comment]
I'm sure, I get 20+ notifications of a pidgey in the same location, also, I tried disabling notifications for pidgeys and it just gave me notifications of the same jiggypuff over and over

**Comment by Kryakz** [comment]
also, I was running it and i wasnt getting repeats, but the randomly they started again

**Comment by Kryakz** [comment]
I think i might be getting spam notified as they despawn or something

**Comment by Kryakz** [comment]
screenshot_20160723-211547

**Comment by Kryakz** [comment]
screenshot_20160723-211547

**Comment by kvangent** [comment]
Ok, I'm not sure what is causing it (the notification part is happening within the semaphore lock) but I will look into it tomorrow. I managed to replicate the circumstances by scanned a new area, and it only seems to happen with spawns with really long times. It's possible that its an API issue interperting the pkmn wrong and thus getting different ids, but I'll need to spend some time looking into it before I can confirm.

**Comment by Digitalxjapan** [comment]
Hello, sorry to bother you guys I currently installed the deploy method of the map, how can I get the Pushbullet to work I created an access token and added a key for push bullet and value for my access token under config variables on heroku but can't manage it takes work?

**Comment by Kryakz** [comment]
I dont use Heroku, but I'll try it and see

**Comment by Digitalxjapan** [comment]
Ok thanks. I been trying all day to get it to work but nothing. Unless I'm doing something wrong

**Comment by Kryakz** [comment]
tbh idk how to use it XD
Why do you use Heroku tho? Is there some reason you have to use it? I think its easier not to imo

**Comment by Digitalxjapan** [comment]
Well it's on the web app, how are you using it on a local root on your pc

**Comment by Kryakz** [comment]
First, download Python [here](https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi) and install. Then download [pip](https://bootstrap.pypa.io/get-pip.py) (right click that link and choose "Save Link As"), and double click the file you downloaded, assuming you installed Python correctly.

Download [Github Desktop](https://desktop.github.com/) and then click [THIS.](github-windows://openRepo/https://github.com/AHAAAAAAA/PokemonGo-Map) After you've done that, click [THIS.](github-windows://openRepo/https://github.com/AHAAAAAAA/PokemonGo-Map?branch=pr%2F1706&filepath=alarms.json&pr=1706) Go to the file location and go into the `Easy Setup` folder click setup. When it asks for your google API follow [THIS](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key) guide. After you've done that go back to the main file and `Shift + Right Click` click `Open Command Window Here` and type `python runserver.py -u [USERNAME] -p [PASSWORD] -st 10 -k [Google Maps API key] -l "[LOCATION]"`. After you've done that go to [http://localhost:5000](http://localhost:5000) and it should be there.

**Comment by theimo1221** [comment]
Hello,

Please get me detailed information, at which position you insert PB stuff?

I'll take a closer look into it today evening and I'm sure I can solve it, because I'm working with PB for quite a long time in process automation and bottling. 


Greets

**Comment by Kryakz** [comment]
@theimo1221 Well obviously i didnt make it, and tbh, I'm really a noob at this sort of stuff, but it looks like to me most the pb stuff is in pb_alarm.py, notifications.py, and alarms.json.

If you want me to look at where exacty it is and give you examples, I can try, but again I'm a noob.

**Comment by Kryakz** [comment]
I've been running it all night and I haven't gotten a single spam-notification. Idk if it was just me or something but it seems to work fine now.

**Comment by theimo1221** [comment]
I'm on a trip atm, just with tablet, smartphone and remote access,  so I'll start working today evening when I'm back home

**Comment by PoorNewb23** [comment]
I just deployed your branch and... it doesn't work with both slack and pushbullet.

I see it in log:
2016-07-24 13:45:10,467 [notifications] [   INFO] Pidgey notification has been triggered!
but there is nothing in either pusbullet or slack accounts. It is unlikely I messed up API access on both.
Can you add more logging to make troubleshooting it easier?

**Comment by PoorNewb23** [comment]
Oh, it wasn't working because True != true ...
would be nice if it dropped exception or something if it runs into variable/value it cannot recognize.

**Comment by kvangent** [comment]
@theimo1221 It's being called from the search function.

**Comment by theimo1221** [comment]
Thanks I'll take a look today evening

**Comment by kvangent** [comment]
@marauder37 I have rebased to develop branch and submitted a new pull request (#1841).

**Comment by tkSimon** [comment]
regarding PushBullet: https://www.reddit.com/r/Android/comments/4ulwls/pushbullet_blocking_push_activity_from_some/
I also got an email from them on this topic, but it seems there is no official statement on their web site.

At some point users may complain about this feature not working...

**Pull request closed without merging**
