### PR TITLE
Fix flask-compress warning

### PR DESCRIPTION
**Pull request by jangrewe**
fix #1722

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
How to reproduce? I did not see warning using last patch.

**Comment by marauder37** [comment]
Warning happens on Win10 reportedly

**Comment by jangrewe** [comment]
@MonkeyLeeT me neither, but @marauder37 posted a screenshot. seems to be a Winblows prob.

**Comment by medghaim** [comment]
I'm beginning to hate winders.

**Comment by MonkeyLeeT** [comment]
@marauder37 You have the word.

**Comment by fourbytes** [comment]
This isn't specifically a windows issue, should be global, it's because flask.ext.* [has been deprecated](https://github.com/pallets/flask/pull/1484).

**Pull request merged**
