### PR TITLE
Explicitly use http to avoid ssl certificate issues

### PR DESCRIPTION
**Pull request by springjools**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Ashex** [comment]
What sort of certificate issues does this avoid?

Certificates aren't validated.

https://github.com/geopy/geopy/blob/master/geopy/geocoders/googlev3.py#L66

**Comment by springjools** [comment]
It's the same issues as listed here: https://github.com/Mila432/Pokemon_Go_API/pull/115/commits

I don't know more exactly what's the issue but with this fix it started working for me. I assume there are other users that have this issue.

**Comment by Ashex** [comment]
I'd elect for updating the library used by the project rather than applying a single change from upstream.

**Comment by Mr-Groch** [comment]
This will have an impact if I'm using nigix reverse proxy for https access to Pogomap?

**Comment by jimdrie** [comment]
@Mr-Groch nope, as you can see in the commit this only concerns the Geolocation module, which is used to determine coordinates from a location string.

**Comment by AHAAAAAAA** [comment]
Not touching the API.

**Pull request closed without merging**
