### PR TITLE
linux setup script. Runs installation for python, pip, and google API

### PR DESCRIPTION
**Pull request by pyr0ball**
Runs installation for python, pip, and google API
## Description

New file, created as a direct analogue for setup.bat in linux environments
## Motivation and Context

Created due to the high number of people having issues with the pip install portion of the setup.
## How Has This Been Tested?

1. Created a new clone
2. Created linux analogue installation script
3. Ran script
4. Verified python requirements installed, and /config/credentials.json was successfully created including the API key, in the original file's exact syntax

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
New installation script for linux users
## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by frdmn** [comment]
The JSON part in the script seems invalid:

bildschirmfoto 2016-07-24 um 13 31 14

This should be probably look like this instead:

```
{
	"gmaps_key": "test"
}
```

**Comment by pyr0ball** [comment]
That a white space issue?

**Comment by frdmn** [comment]
No, I think you're just missing the double quotes of the keys and values:

```
echo '{' >> ../config/credentials.json
echo '"gmaps_key": "$api"' >> ../config/credentials.json
echo '}' >> ../config/credentials.json
```

**Comment by pyr0ball** [comment]
Using double quotes like that, the $api variable doesn't get passed and
stays as $api

**Comment by frdmn** [comment]
Ah, I missed that:

```
echo '{' >> ../config/credentials.json
echo '"gmaps_key": "'$api'"' >> ../config/credentials.json
echo '}' >> ../config/credentials.json
```

**Comment by frdmn** [comment]
Edited message.

**Pull request merged**
