### PR TITLE
Fixes the repeating login issue

### PR DESCRIPTION
**Pull request by JZ6**
This pull request includes a

- [ x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

-added get_token function
- added global variable global_token
- changed accesss_token geter

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by favll** [comment]
Unident register_background_thread() :)

**Comment by JZ6** [comment]
done and done :)

**Comment by marauder37** [comment]
Wonderful, thanks!

**Comment by JZ6** [comment]
@marauder37 anytime bud! also heres the discord invite link
https://discord.gg/qbpVH6b

**Pull request merged**
