### PR TITLE
Added localstroage caching of options.

### PR DESCRIPTION
**Pull request by JakeCooper**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Adds caching for options (Pokestops, gyms, pokemon) via localStorage

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by JZ6** [comment]
+1

**Comment by MichaelErmer** [comment]
+1, this is heavily required if you scan a large area (pokestops kill the browser)

**Comment by DerScreever** [comment]
+1

**Comment by euphwes** [comment]
I'm not a collaborator and have no meaningful vote, but I think this is a great addition. I typically just want to see the Pokemon, not gyms or stops, and having to toggle those back off every time I reopen the browser is frustrating. It's obviously just a minor inconvenience, but still, great addition!

**Pull request merged**
