### PR TITLE
Support providing custom Google Maps API Key

### PR DESCRIPTION
**Pull request by Ashex1**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

- Made hardcoded Google Maps API Key a default in Config
- Support providing custom Google Maps API Key via argument

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by DerScreever** [comment]
@Ashex1 you need to solve the conflicts. 

@other Collaborator maybe remove the static key? so everyone need to generate his own. so much issues because of this key...

**Comment by Ashex1** [comment]
@DerScreever Just resolved conflicts :)

**Comment by mantas7776** [comment]
Isnt theres already support for gmaps key in credentials.json?

**Comment by frdmn** [comment]
@mantas7776 Not in the `develop` branch. That one doesn't use the credentials.json at all.

**Comment by frdmn** [comment]
What about making this option required?

**Comment by Ashex1** [comment]
@frdmn Making it required only makes sense if we completely drop the hardcoded key. I'm open to this change, I'd just like to get some sort of decision from the maintainers :)

**Comment by sykhro** [comment]
I'd gladly drop the hardcoded key

**Comment by medghaim** [comment]
Yeah, I'm working on reimplementing a credentials/config.json file. Should be fixed soon!

**Comment by Ashex1** [comment]
@medghaim Shall we drop the hardcoded key then merge this PR in preparation for your fix?

**Comment by Ashex1** [comment]
I'll wait for #513 to be merged then restructure things around it.

**Comment by Ashex1** [comment]
I've reworked it to be compatible with the credentials.json @medghaim reintroduced. This allows users to either set the key in credentials.json or pass it as an argument. This method works better for people wrapping it up in containers or whatever else for deployment.

**Comment by sykhro** [comment]
Sweet, was about to implement this myself. Merging

**Pull request merged**
