### PR TITLE
Adds gym, pokestop info, ignore db journal, fix timestamps and countdown timers

### PR DESCRIPTION
**Pull request by invisiblek**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-Add gym info
-Add pokestop info
-Minor code cleanups, removal of unnecessary logging
-Add database journal to gitignore

If this is related to an existing ticket, include a link to it as well.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/510
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/589 
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/591 
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/616 
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/626

### CODE REVIEW

**Comment by mkody** [comment]
Gyms and Pokéstop are working, but it stopped displaying Pokémons for me.

**Comment by invisiblek** [comment]
Try nuking your pogom.db maybe?

**Comment by rezz3x** [comment]
He's probably using the master Release, use the develop branch for support

**Comment by mkody** [comment]
I'm using develop and I've nuked my `pogom.db`, since it prints errors if I didn't :P

**Comment by AHAAAAAAA** [comment]
Works perfectly for me, merging as soon as we get a +1

**Comment by invisiblek** [comment]
hold off a sec, there's a bug with the timestamp fix

**Comment by AHAAAAAAA** [comment]
Can you add hover to show info on marker for gym and pokestop?

**Comment by invisiblek** [comment]
yep, will do

**Comment by invisiblek** [comment]
ok, we should be good here

about the hover info - could that be annoying because those get in the way and a lot of these markers are really close to eachother? (my only concern with adding it)

**Comment by AHAAAAAAA** [comment]
You're correct and I agree. Pokestops don't have any meaningful info, unless they're lured, so no need to display on hover. Perhaps only hover display if they're lured?

**Comment by invisiblek** [comment]
k, done. this may need to be revised if/when useful information is added to the pokestops (such as being able to tell how long until its refreshed for you to get more goodies out of it)

**Comment by mantas7776** [comment]
+1, just tested, works good

**Comment by invisiblek** [comment]
guess i'll rebase again

can we get this merged soon? :hamster:

**Comment by AHAAAAAAA** [comment]
yas

**Comment by invisiblek** [comment]
be an hour or so before i can get back to finishing this rebase (it broke a lot of things =P )

**Comment by jonathan-dejong** [comment]
Looking forward to this! I'll rebase as soon as it's up and try it out

**Comment by invisiblek** [comment]
now if only niantic's servers would freaking work...

**Comment by jonathan-dejong** [comment]
lol yeah, I've been running it nonstop for 2h on both local and a droplet and it's reaaallly shaky.

**Comment by invisiblek** [comment]
k, try that

**Comment by cschmatzler** [comment]
Seems to be ignoring the -dp, -dl and -dg arguments for now, right?

**Comment by invisiblek** [comment]
oh, maybe. i'll peek at it quick

**Comment by invisiblek** [comment]
bleh, this business with the auto refresh is going to require a bit of refactoring to make that work i think

we should ship this, we can assess the rest of it in a new set of commits (i'm tired of rebasing this 😉 )

**Comment by jonathan-dejong** [comment]
If the ar require that much work this should just be added even so just to fix all other bugs like you say :) As long as the AR does not keep running (because now it's on and not working). :)

**Pull request merged**
