### PR TITLE
Add current location indicator to the map

### PR DESCRIPTION
**Pull request by rnarian**
This pull request includes a

- [x] New feature

The following changes were made

- Add current location indicator via google map custom controls

This is a better version of my previous pull request #390 as it mimics the standard google map geolocation functionality. 

juli-20-2016 17-27-05

Instead of adding the current location by default a new button is added to the controls in the bottom right. 

Clicking the button will get the users current location and add the location indicator to the map. If the map is dragged the marker gets slightly transparent (because the current location might have changed in the meantime). Clicking the button again will get the new location and update the location indicator accordingly.

### CODE REVIEW

**Comment by pix** [comment]
Custom buttons are nice ! 
I used https://github.com/ChadKillingsworth/geolocation-marker to implement the same thing #554

**Comment by rnarian** [comment]
Whoops, our pull requests have overlapped unfortunately. I haven't noticed your pull request until now. Sorry mate.

**Comment by rnarian** [comment]
I just checked out your implementation. 

While your code looks much cleaner, I feel like mine is a lot less obtrusive as it mimics the behavior of the current Google Maps website.

Plus it should still work fine when the auto refresh feature is back because the localization is requested by the user instead of forcing it on page load and having to relocate on every auto refresh.

What do you think?

**Comment by volksport** [comment]
I like the idea of the button -- this will also work nicely when I add an optional flag to redo the location based on pressing this button (again , optionally).

**Comment by rnarian** [comment]
@volksport The location is only requested by pressing this button. The Google Maps website is doing the same thing basically. I added the transparent state to advise the user that the current location might not be his actual position anymore. The button itself indicates the same thing.

**Comment by AHAAAAAAA** [comment]
rebase this we'll merge it in after a test.

**Comment by rnarian** [comment]
@AHAAAAAAA Done. You can give it another try. Remember to use a browser which lets you use [geolocalization on non-https sites](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only) (e.g. Safari).

**Comment by yashmangal9506** [comment]
how can i use it? I am unable to use it. after downloading the zip file what to do? pls comment fast

**Comment by kingeddard** [comment]
@yashmangal9506 did you download the develop branch?

**Comment by yashmangal9506** [comment]
what

**Comment by kingeddard** [comment]
@yashmangal9506 theres the master branch (stable build) and also the develop branch (newest features but not so stable) 

heres a link: https://github.com/AHAAAAAAA/PokemonGo-Map/archive/develop.zip

**Comment by yashmangal9506** [comment]
pls guide from starting @kingeddard

**Comment by yashmangal9506** [comment]
its downloading

**Comment by yashmangal9506** [comment]
@kingeddard pls help

**Comment by yashmangal9506** [comment]
i am talking about PokeGo Map i am unable to use it

**Comment by rnarian** [comment]
@yashmangal9506 Take a look at these two links:

- https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Installation-and-requirements
- https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Usage

I'm afraid you cannot use this right now without basic knowledge of programming or the command line.

**Comment by yashmangal9506** [comment]
i am studying programming ]

**Comment by andrewda** [comment]
@yashmangal9506 You're making my notifications go crazy with "HELP ME" comments. Follow the instructions that @rnarian provided, and if you need more help after that, create a new issue (or find one that is similar to what you're experiencing).

**Comment by frdmn** [comment]
Any updates on this? It's still not back in the current HEAD.

**Comment by rnarian** [comment]
Guys? Whats going on? This got merged and then removed in the following commit (df8b8665ced0ed91a6c43dc02795838ca2c77b62) by @sykhro? Why is @sykhro allowed to work directly in the develop branch when he doesn't know what he's doing at all obviously?

**Comment by AHAAAAAAA** [comment]
Sorry, that was an oversight. Project is hectic and very active, it's hard to keep track sometimes. That won't happen again. Thanks for notifying me, can you make another PR? I can add it if not, but I'd like to have the right person attributed!

**Comment by rnarian** [comment]
I could resubmit but truth be told I'm afraid it gets overridden again by @sykhro or someone else working directly in the develop branch. Why don't make them submit PRs like everyone else? If @sykhro would have sent a PR this wouldn't have happened in the first place.

**Comment by sykhro** [comment]
@rnarian I'm allowed because I'm a contributor. I know what I'm doing, but stuff happened. I had those changes made hours before this was merged, but due to a power outage it didn't get pushed. It got pushed the next morning and produced that ugly big commit.

**Comment by Pedrock** [comment]
@sykhro You had to pull before pushing, so you should have checked the diff...

**Comment by rnarian** [comment]
@sykhro You are supposed to work in a feature branch and rebase changes from main branch before pushing your stuff.

**Comment by rnarian** [comment]
If you work in feature branches and submit PRs like everyone else (even the other allowed collaborators) then this wouldn't even happen in first place.

Even @AHAAAAAAA who is obviously owning the repo is submitting pull requests for his changes. So why don't you?

**Comment by sykhro** [comment]
Because the rewrite of that was agreed with the team and they gave me the okay to push directly. I epm't explain the whole story of who the push happened automatically/accidentally because it's no use. This can be added back without issues

**Comment by rnarian** [comment]
I don't want you to explain what exactly happened (I can already imagine pretty fine). I want you to change the way you work as I cannot contribute any further without having to fear that my work gets deleted by 'accident'.

**Comment by sykhro** [comment]
It won't, as that was the only approved thing for direct push (excluding quick bugfixes)

**Comment by rnarian** [comment]
I don't know what you are trying to defend. Out of all your commits to this project a PR was made only once so don't be cross with me if i'm staying sceptic.

@AHAAAAAAA Wouldn't it make sense to just protect master and develop branch from direct pushes?

**Comment by AHAAAAAAA** [comment]
I had master protected, I will protect develop now!

**Comment by rnarian** [comment]
@AHAAAAAAA Awesome, thank you! 👍

**Comment by AHAAAAAAA** [comment]
I'd love a PR on that location feature anytime you're ready! We could make it integrate with the /mobile function pretty well!

**Comment by rnarian** [comment]
Alright, will do! 😎

**Comment by rnarian** [comment]
@AHAAAAAAA Added again in #1484

**Pull request merged**
