### PR TITLE
settings.py file

### PR DESCRIPTION
**Pull request by borisrozumnuk**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Added settings.py file to project folder
- Moved some constants to settings.py
- added logic to host and port selection when app starts

### CODE REVIEW

**Comment by DerScreever** [comment]
Approved, Test passed :+1:

**Comment by medghaim** [comment]
#130 ?

**Comment by DerScreever** [comment]
@medghaim 
i will test #130 in a second

**Comment by borisrozumnuk** [comment]
@medghaim   #130 is not a pythonic way, but if you want to get values of variables this way, you can make default value with dict.get(key, default=value_here)

**Comment by borisrozumnuk** [comment]
#130

**Comment by medghaim** [comment]
Ah, just figured since the keys aren't user input there's no chance of not finding the dict value since it's in the JSON file.

**Comment by JZ6** [comment]
I might need to ask you to rebase in a bit.

**Comment by JZ6** [comment]
outdated rebase and do new pull

**Pull request closed without merging**
