### PR TITLE
Added binding to any network interface

### PR DESCRIPTION
**Pull request by lukahn**
This pull request includes a fix to allow the code to bind to any network interface, not just 127.0.0.1. This also means that the server can also be connected to externally.

### CODE REVIEW

**Comment by frdmn** [comment]
This should not be hardcoded IMHO - same with the port setting.

**Comment by frdmn** [comment]
@MelonSmasher raised #106 for a configurable setting.

**Comment by MelonSmasher** [comment]
I agree with @frdmn, it should listen locally unless it is configured otherwise.

**Comment by DerScreever** [comment]
Alread done with #106

**Pull request closed without merging**
