### PR TITLE
improved loop logs

### PR DESCRIPTION
**Pull request by KonstantinKuklin**
This pull request includes a

- [ ] Bug fix
- [*] New feature
- [ ] Translation

The following changes were made

- Now loop logs stay on the same line

### CODE REVIEW

**Comment by KonstantinKuklin** [comment]
it seems, that location can be changed inside the loop and I broke logging new coordinates, I`ll fix it right now :)

**Comment by AHAAAAAAA** [comment]
Just tested it, you got my +1 when you sort out the coordinates!

**Comment by nborrmann** [comment]
Don't like the use of flush. It will get weird when there are error messages. (Which is inevitable when the servers crash the next time)

**Comment by KonstantinKuklin** [comment]
I'm done

**Comment by AHAAAAAAA** [comment]
This introduces more problems than it's worth, erases other error messages that might come up during pinging niantics servers. I'm sorry I'll close this PR for now

**Pull request closed without merging**
