### PR TITLE
Scanned Pokémons/Gyms/PokéStops Statistics

### PR DESCRIPTION
**Pull request by Retalyx**
This pull request includes a

- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made

-Added scan statistics in the navbar
-You can see stats for all displayed Pokémons, Pokéstops, and gyms

capture
capture

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by andrewda** [comment]
Looks good! Not sure what others prefer or think looks best, but it might be better to have the total on the bottom - that's usually the standard.

**Comment by Retalyx** [comment]
Total on bottom? Why not :) If more people prefer total on bottom, i'll change it ;)

**Comment by ditchfieldcaleb** [comment]
I'd prefer total on top. Would rather not have to scroll all the way down if there are many different pokemons.

**Comment by JZ6** [comment]
this might slow stuff done, perhaps add a toggle

**Comment by Retalyx** [comment]
Why ill this slow stuff down? It's client side and only updated when updateMap() is called :) i tested it multiple Times with hundred of pokémons without any visible slowing down

**Comment by Shulin** [comment]
This isn't populating on mobile.

**Pull request closed without merging**
