### PR TITLE
Add current location marker to the map

### PR DESCRIPTION
**Pull request by rnarian**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

- Add current location marker to the map

bildschirmfoto 2016-07-19 um 18 09 36

### CODE REVIEW

**Comment by rnarian** [comment]
These issues might be relevant: #164, #355

**Comment by volksport** [comment]
@rnarian any way you want to have this optionally send the coords to the next_loc api endpoint and have a parameter in the server startup that turns it on/off?

**Comment by rnarian** [comment]
@volksport I'm more of a front-end guy. I'm honestly not really sure what you mean by that. 😔

**Comment by sgraut** [comment]
Chrome is stating that _getCurrentPosition()_ is deprecated on insecure (http) origins. Does not work for me - neither on my mac nor on my phone

**Comment by volksport** [comment]
There is a jquery geoloc plugin that may handle cross-browser issues more friendly? Never used it though.

**Comment by sgraut** [comment]
The jquery.geolocation plugin does not work either. Feels like it is just a wrapper for the html5 geolocation functions.

**Comment by SophisticaSean** [comment]
@sgraut Chrome doesn't allow http location gathering, so you'd have to either open it in Firefox or Safari or setup SSL termination on the server you're running it on. (I think running it on localhost:someport will work too)

**Comment by rnarian** [comment]
Ok, it seems that there is no work-around in Chrome 50+ (other than running the app on https). But this doesn't change the fact that it's working in mobile safari which it was intended for. For people using the affected versions of Chrome the feature simply doesn't appear, but doesn't break any other functionality.

**Comment by mkody** [comment]
Welp, using Let's Encrypt and a reverse-proxy, it works at least :+1:

**Comment by volksport** [comment]
If this gets merged in I can add a param flag to have it update the next_loc endpoint automagically (or i might make it a button we'll see).

**Comment by rnarian** [comment]
@volksport Awesome! But maybe make it optional because this only works if only one person is using the app. In my case there are 3 people using the same app so we would override each others current location.

**Comment by rushingfitness** [comment]
I'm a rails dev, no Python, so this isn't my forté. But what I would do is have a geo flag, if the flag is present do two things. 
1.) In example.py on the location settings, check to see if there is a geolocation set in the session (whatever variable you want). If not sleep for 5 seconds (or whatever your refresh time is set as, may also need to make that flag required if geo flag is set). Then when the session geolocation variable is present, use that.
2.) On the view when you call `updateLocation()`, have it post a req to the server with the coords, which on the server side saves it as a session variable.

Idk if you can get the session varaible from the example.py file or not. But if so, I'd say this should work fine.

**Comment by nekitk** [comment]
to add next_loc support for switching search center you just need to replace popup content with
`content: 'Current location<br><a href="/next_loc?lat='+position.coords.latitude+'&lon='+position.coords.longitude+'" target="_blank">Search from here</a>'`
but I'm not sure if `next_loc` itself is working correctly now

**Comment by rushingfitness** [comment]
Ahhh! Interesting didn't see that. Well then if next_loc is working, could just add that as an ajax request in the updateLocation function.

**Comment by volksport** [comment]
I think #384 or #303 will fix next_loc

Need to merge in a dozen of these PR before it makes sense to try to work on creating an auto geo updater

**Comment by rushingfitness** [comment]
👍 Oh no doubt. Do you homie. Just trying to get it primed now while you're busy with the other PR's.
Also I'm going to look into making this a wearable apk if possible.

**Comment by rnarian** [comment]
To clarify: I did not raise this PR to support updates of the backend location calls – instead I just wanted to add an indicator of my current position when I have the map running on my iPhone while hunting for Pokemon. 

I don't wanna be the party pooper so please don't get me wrong but I think the auto update feature of the backend calls should be discussed (and added) in a separate PR. Maybe we can focus on the initial PRs intention?

**Comment by rushingfitness** [comment]
@rnarian Yes it would be a separate PR. We're just talking right now. No harm in talking things out :)

**Comment by rushingfitness** [comment]
@rnarian p.s. I can't really get this to work on my mac. It works every once in a while, but when it does (blue dot showing instead of red arrow), no pokemon show up, or if they do it's like 1. If it just shows the red arrow like usual then all of them show up (> 20 pokemon)

**Comment by rnarian** [comment]
@rushingfitness The pokemon don't show up because the servers are down right now.

**Comment by rushingfitness** [comment]
@rnarian this was happening a couple of hours ago. But let me re-pull it down and see if it works (my connection to the servers is fine fyi)

**Comment by rnarian** [comment]
@rushingfitness I just noticed the current location indicator didn't show up on the initial page load. I added another commit to fix this. Can you try again? Both the start position (red indicator) and the current location (blue indicator) should show up right away:

image

**Comment by rushingfitness** [comment]
@rnarian confirmed the icon shows up right away. Can't do any more until the servers come back.

**Comment by rnarian** [comment]
@rushingfitness Right now its working for me if you wanna give it another try. 😁

**Comment by rushingfitness** [comment]
Just got it back. Confirmed. Looks good now. Thanks!

**Pull request closed without merging**
