### PR TITLE
config.ini for dummies

### PR DESCRIPTION
**Pull request by EdenGottlieb**
The new config.ini is very neat but it is not exactly clear for the common user. It was obviously written by someone very familiar with .ini files. Rookies would probably get confused and flood the Issues section.
## Description

- Added a little bit of explanation in the end of the file that should get most people up and running.
- Uncommented username, password, location and gmaps_key to make it clear that they are required.
- Fixed typo in the port line

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JZ6** [comment]
Nice change! Glad to see my config has grown to be so robust

**Comment by JZ6** [comment]
need to rebase

**Comment by willgrnr** [comment]
@EdenGottlieb rather than uncommenting those lines, the info message should suffice. I know most users pass flags via CLI anyways. 

The flags should trump the config.ini settings no matter what, but keeping them commented is a bit cleaner.

**Comment by EdenGottlieb** [comment]
@willgrnr I agree, updated the commit

**Comment by marauder37** [comment]
wfm

**Pull request merged**
