### PR TITLE
moving Mapstyle selector to Option menu

### PR DESCRIPTION
**Pull request by callmebackdraft**
Move the map style selector to Option menu

*added dropdown menu to Option menu with map styles
*made the dropdown read localstorage so it reads the last used style
*removed mapstyle selector from map itself

More screen real estate especially on mobile
also responds to  #1674

## How Has This Been Tested?
after editing loaded page on:
Microsoft Edge 
Chrome ( Win10)
IPhone Safari
IPhone Chrome

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x?] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ingwarsw** [comment]
That would really help on mobiles..

**Comment by brycedorn** [comment]
should use [select2](https://select2.github.io/) classes to match the other `select`s; the css is already there. but +1 for moving controls into the same area!

**Comment by willgrnr** [comment]
@AHAAAAAAA I know only pull requests for the 2.1 milestone are being accepted, however this could very well classify as a bug fix. The map selector takes up valuable real estate on mobile devices

**Comment by callmebackdraft** [comment]
@brycedorn not all that farmiliar with how to change this, have been looking over the code but cant find how to do that. if this would be a critical step before merging some help would be appreciated

**Comment by willgrnr** [comment]
@callmebackdraft have you had a look at: http://select2.github.io/select2/

**Comment by callmebackdraft** [comment]
@willgrnr  yes i did, and that is pretty straightforward however trying to keep te code clean i could not see where the other select elements were coded as select2

**Comment by willgrnr** [comment]
@callmebackdraft the select2 javascript is in static/map.js

**Comment by callmebackdraft** [comment]
made new PR with the new style  #2240 

now uses select2
also enables users to change names of styles according to locale (new json files)

**Pull request closed without merging**
