### PR TITLE
Added bounce animation end on click

### PR DESCRIPTION
**Pull request by MikeDuister**
## Description
3 lines added that makes sure the animation ends when the marker is clicked

## Motivation and Context
Prevents continuous loop of bouncing pokémon ( #1955 )

## How Has This Been Tested?
By running the setup several times on Linux and Windows.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Toeler** [comment]
Why not configurable? I'd want at least a few minutes of bouncing as I'm not always watching the map, and Chrome notifications don't show up when I'm running other full screen applications.

**Comment by MikeDuister** [comment]
@Toeler I think that would be best, I just tried implementing it but I can't figure out how. I'm just going to leave it as is because I don't want to mess up the clean code.

**Comment by invisiblek** [comment]
Another option would be to make it stop bouncing once you click on it. I think adding a configuration for "bounce duration" just leads to over-configurability.

**Comment by louispires** [comment]
@invisiblek This is the best solution, as this means you have acknowledged the newly spawned Pokemon.

The 3000ms would be a joke as I am searching many places all over the world and 3000ms is honestly just too short!

**Comment by MikeDuister** [comment]
@invisiblek  @louispires Feels nice!

**Comment by chuyskywalker** [comment]
:+1: from me

**Comment by DerScreever** [comment]
tested it, work only half. when i zoom the animation start again.

**Comment by invisiblek** [comment]
@DerScreever https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1997

**Comment by MikeDuister** [comment]
@DerScreever #2017 fixed this issue, will make a new PR based on the the develop branch that now has the fix

**Pull request closed without merging**
