### PR TITLE
Translation fix for exclude/include lists and mapstyle loader

### LINKED ISSUE #2730: locale setting is not applied to the options menu
## Expected Behavior
language specific pokemon-names should be used in the exclude/notify section

## Current Behavior
the english names are being used, regardless of user selected locale

using latest develop build: #2667

### PR DESCRIPTION
**Pull request by tim95030**
## Description
Fix to something that was reverted accidently in a rebase on the types and rarity pull request. And moved the translations for the mapstyle to the language files.

Fixes #2730 

## Motivation and Context
Translations weren't happening on the exclued/include lists.

## How Has This Been Tested?
Tested locally by running with multiple languages.

## Screenshots (if appropriate):
screen shot 2016-07-30 at 10 55 42 am

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andrewda** [comment]
It would be great if you could minify those locale files.

**Comment by tim95030** [comment]
They are very hard to manage if we do that. I suppose I can run it through grunt for that.

**Comment by AHAAAAAAA** [comment]
LGTM

**Comment by tim95030** [comment]
Added to Grunt.

**Pull request merged**
