### PR TITLE
use Pokemon Go theme!

### PR DESCRIPTION
**Pull request by invisiblek**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by quagliero** [comment]
It's definitely better than the dark theme, but does completely white out venue names and icons. Which looks a bit odd (especially if you want to know what it says!)

screen shot 2016-07-21 at 15 03 39

**Comment by TGM** [comment]
@quagliero if you dislike the dark theme, you can use this patch https://github.com/TGM/PokemonGo-Map/commit/a642ae81d2913fa8242b514fbf09fc7ad0919a8e.patch

**Comment by quagliero** [comment]
Thanks @TGM, I'm running a custom theme on my own fork now 👍

**Comment by Jarrrk** [comment]
Nice looking skin +1

**Comment by jtdroste** [comment]
Personally, I'd rather have there be a toggle option between other teams than constantly changing the default one around.

**Comment by AHAAAAAAA** [comment]
I second the toggle idea. There's a reason night mode is so popular!

**Comment by Jarrrk** [comment]
@AHAAAAAAA Hi mate,

If you need someone to sort through issues and close tickets etc let me know. Been active on this project a few days and didn't know where to contact you.

Cheers.

**Comment by JZ6** [comment]
added

**Pull request closed without merging**
