### PR TITLE
Add -dg -dp -dl back in and stamped calls

### PR DESCRIPTION
**Pull request by invisiblek**
This pull request includes a

- [x] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-fix parameters for showing/hiding markers
-fix calling routes without a timestamp (many don't need it)

If this is related to an existing ticket, include a link to it as well.
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/705

### CODE REVIEW

**Comment by AHAAAAAAA** [comment]
+1 works, code style is good.

**Comment by medghaim** [comment]
This is great except for -dl.

-dp and -dg work separately, and together.

-dl doesn't show any lured pokestops, which i confirmed were there in game, and using -dp :)

**Comment by invisiblek** [comment]
@medghaim seems to be working as expected for me...

Just -dp
dp only

With -dp and -dl
dp and dl

**Comment by medghaim** [comment]
Oh oops. I could've sworn it was -dl alone :O

Eitherway, +1. Good stuff. Sorry about the mixup lol

**Comment by invisiblek** [comment]
well, we could make -dl imply -dp,  suppose that would be intuitive

**Comment by AHAAAAAAA** [comment]
I understand the confusion. Should -dl work standalone to just show lured stops without requiring -dp as well?

-dp: show all
-dl : show lured only
-dp -dl: show lured only

**Comment by medghaim** [comment]
Yeah, imo it should be used stand alone. What do others think?

**Comment by invisiblek** [comment]
yea, that probably makes the most sense, patch incoming

**Pull request merged**
