### PR TITLE
Display InfoWindow on mouse over. Persist on click

### PR DESCRIPTION
**Pull request by pix**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made: Display the InfoWindow on mouse over. Persist on click

### CODE REVIEW

**Comment by DerScreever** [comment]
Does not work for me. 
Test failed.

**Comment by pix** [comment]
Could you be more specific ?

Nothing on mouse hover ?

**Comment by nborrmann** [comment]
This doesn't even touch the Python code, your test must be failing on something else.

**Comment by DerScreever** [comment]
nothing happen. no mouse hover.

**Comment by nborrmann** [comment]
It's working for me.

**Comment by DerScreever** [comment]
someone else who say its working? :D for me nothing happend ^^

**Comment by benemorius** [comment]
works for me

**Comment by mkody** [comment]
Chrome 49 on Windows XP, can confirm it works.

**Comment by DerScreever** [comment]
k then i wait until we are ready to merge. we are splitting at the moment the example.py to multiple files and use the base from https://github.com/tejado/pgoapi

**Pull request closed without merging**
