### PR TITLE
Producer/consumer pattern for search threads instead of task batching (speedup)

### PR DESCRIPTION
**Pull request by DeirhX**
Current implementation uses optional batching of up to --threads requests yet it always waits for the entire batch to finish which equals to waiting for the slowest thread of the batch before launching new batch.  This seriously impacts scalability since the entire node does nothing when waiting for prohibitively slow responses.

## Description
Rewritten the pattern to async producer/consumer queue of configurable SEARCH_QUEUE_DEPTH so all threads can be kept busy even if requests of uneven response speed are encountered. This should speed search times considerably when using a lot of threads (tested with 25 and up to 100).

Also **added retrying** in case server responds with invalid response which can start happening in very high throughput scenarios (previously thread gave up upon encountering log.error('Scan step {:d} failed. Response dictionary key error.'.format(step), creating gaps)

This should bring multiple workers + one server scenario a step closer to reality.

## Motivation and Context
Scalability of current solution is poor as adding more search threads can start slowing the entire process due to current wait_for_join(slowest_thread_of_the_batch)

## How Has This Been Tested?
Tested thoroughly with --threads 25 and seen a dramatic rise in search performance - test for yourself and see.
Note: --threads 100 often causes niantic servers to stop responding properly if on a fast connection - we need to implement adaptive delays for such low-latency scenarios.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by medghaim** [comment]
:O

Testing!

**Comment by AHAAAAAAA** [comment]
Testing, really cool stuff! Good job. I was able to cover a huge area in minutes. Problems I've noticed so far: 
* process refuses to terminate with so many threads.
* db locks, which is expected

**Comment by AHAAAAAAA** [comment]
Been running for 45 minutes now, and tested on 2 machines. Seems pretty solid, +1

**Comment by medghaim** [comment]
This is definitely a huge improvement. +1

**Comment by AHAAAAAAA** [comment]
I wasn't sure how to do this on python, but hopefully this StackOverflow [post](https://stackoverflow.com/questions/1635080/terminate-a-multi-thread-python-program) is helpful.

**Comment by DeirhX** [comment]
Made the threads daemons, hopefully that should help with termination, at least for now using Ctrl+C. 
However in general we might want to start thinking about entirely clean shutdowns, e.g. polling some global condition and making all threads termination-aware (e.g.: post special objects into their work queue once termination is requested)?

**Comment by AHAAAAAAA** [comment]
excellent, +1. I agree, we kind of need to put the whole thing on hold and just do clean up.

**Comment by medghaim** [comment]
Restesting

**Comment by medghaim** [comment]
+1

meeeerge!

**Comment by k33k00** [comment]
I've just updated to this & i'm curoius what exactle is search queue depth? I've randomly thrown 50 threads in there and I have a sea of  "search queue depth is: 99" may be throwing in a few 94 - 98 & the odd response dictionary error

**Comment by wcastello** [comment]
Nice one! I learned something new today.

**Comment by craywong** [comment]
Hows this working for you guys. I kept getting db locks when using 25 threads. Is the error related to the number of threads used?

**Comment by k33k00** [comment]
Are you running sqlite or mysql? I'm under the impression that sqlite will really struggle with that many threads.

**Comment by adamhwang** [comment]
So far so good, but please consider #2128 that addresses a small issue introduced by this change

**Pull request merged**
