### PR TITLE
Fix: Localization should change Pokedex Link

### PR DESCRIPTION
**Pull request by blankse**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Pokedex Link with right locale

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by MonkeyLeeT** [comment]
If you take a careful look at other language's podex, you'll see that they're poorly supported for now. 

Also {{lang}} is dominating the language setting, and it's currently mapping to locale file names, which is again different from expected "us" or "jp".

So this PR is not really working as you would expect.

**Comment by blankse** [comment]
You are right. I add a switch statement before when I came to my pc ;)

**Comment by MonkeyLeeT** [comment]
So would you mind close this one and reimplement another version later after our first release (soon)?

Default en pokedex should be enough for first release.

**Comment by blankse** [comment]
Why close? I can rebase if needed.

**Comment by blankse** [comment]
@MonkeyLeeT I changed it

**Comment by MonkeyLeeT** [comment]
@blankse than a simple "-locale ja" will break it. I don't really think it's necessary to add this feature now cuz basically you need to manually map niantic's locale (us, jp) names to our locale folder's filenames (en, ja).

**Comment by blankse** [comment]
Why should "-locale ja" break it? The pokemonLang function returns "us"

**Comment by MonkeyLeeT** [comment]
But technically you should redirect them to Japanese version. We should not have incomplete codes like the switch clauses you have there.

**Comment by JZ6** [comment]
too little benefit, too much room for error, sorry.

**Pull request closed without merging**
