### PR TITLE
Credentials + credential loading - congregates credentials into one file.

### PR DESCRIPTION
**Pull request by medghaim**
This pull request includes a

- [ ] Bug fix
- [x] New feature
- [ ] Translation

The following changes were made

-
-
-

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by medghaim** [comment]
I'll add ANDROID_ID, SERVICE, and CLIENT_SIG to credentials as well. 

but i'll leave the auth links in example.py

**Comment by DerScreever** [comment]
Approved, Test passed :+1:

**Comment by medghaim** [comment]
Should be more pythonic now with .get(key, defval). Also safer, using `with open`

**Comment by medghaim** [comment]
Redoing

**Pull request closed without merging**
