### PR TITLE
cleanup map.js [DRY]

### PR DESCRIPTION
**Pull request by broglep**
Don't repeat yourself, refactored a lot of copy&pasted code

## Description
- add change listener factory for switches
- remove duplicate switch initialization
- extract API request
- extract processing of API response

## Motivation and Context
It makes the code cleaner and prepares for some other changes allowing to receive data via other then XHR

## How Has This Been Tested?
Run server with new code, scanned our test area, and verified that toggling all switches properly work.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by CarlTaylor1989** [comment]
This looks neat, I'll give it a test

**Comment by Chlodochar** [comment]
:+1+: Looks good. A step in the right direction. Tested and working.

**Comment by chuyskywalker** [comment]
I'mma take a look at this one.

**Comment by chuyskywalker** [comment]
+1 from me, code looks good, no console errors, all check marks showing as expected.

**Comment by megahambone** [comment]
FYI, ever since this PR was merged, MS Edge no longer functions. (which sucks, because I need it to debug geolocation since chrome won't do it on non https)

**Pull request merged**
