### PR TITLE
Temp fix for missing pokemon

### PR DESCRIPTION
**Pull request by medghaim**
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made

- Altered step values to accommodate issue of lack of complete coverage.

### CODE REVIEW

**Comment by CarlTaylor1989** [comment]
+1

**Comment by jangrewe** [comment]
@medghaim should the step size be increased to cover the same area?

**Comment by medghaim** [comment]
Yessir! Search space is now crammed together to get full coverage of a search area. Downside is you're going to have to increase `-st` to cover a larger area.

**Comment by jangrewe** [comment]
Great, thanks! I guess a factor of 2 would result in aproximately the same coverage?

**Pull request merged**
